### ISSUE TITLE
DataFrame.loc fails when passing a boolean

### ISSUE THREAD

**Issue by freedumb2000** [modin-project/modin#1032]
### System information
OS Platform and Distribution: Manjaro Linux
Modin installed from: pip
Modin version: 0.7.0
Python version: 3.7.4

### Describe the problem
DataFrame.loc operation fails when passing a boolean.
It seems like when passing a boolean list for one of the parameters, it expects the parameters to be switched in order. Instead of DataFrame.loc(rows, columns) it expects DataFrame.loc(columns, rows)

#### Code
```
import pandas as pd
import modin.pandas as mpd


df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=['cobra', 'viper', 'sidewinder'],
                  columns=['max_speed', 'shield'])

o = df.loc[:, ~df.columns.duplicated()]

print(f'Pandas:\n{o}')

mdf = mpd.DataFrame([[1, 2], [4, 5], [7, 8]],
                    index=['cobra', 'viper', 'sidewinder'],
                    columns=['max_speed', 'shield'])

o = mdf.loc[:, ~mdf.columns.duplicated()]

print(f'Modin:\n{o}')

```
#### Output
```
Pandas:
            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
UserWarning: Distributing <class 'list'> object. This may take some time.
Traceback (most recent call last):
  File "modint.py", line 17, in <module>
    o = mdf.loc[:, ~mdf.columns.duplicated()]
  File "/opt/anaconda/lib/python3.7/site-packages/modin/pandas/indexing.py", line 216, in __getitem__
    return self.df.__getitem__(key[1])
  File "/opt/anaconda/lib/python3.7/site-packages/modin/pandas/base.py", line 3304, in __getitem__
    return self._getitem(key)
  File "/opt/anaconda/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1896, in _getitem
    return self._getitem_array(key)
  File "/opt/anaconda/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 1926, in _getitem_array
    len(key), len(self.index)
ValueError: Item wrong length 2 instead of 3.
```

**Comment by devin-petersohn** [comment]
Hi @freedumb2000, thanks for reporting!

The source of the issue is not that the `DataFrame.loc` expects (columns, rows), it is that when no rows are provided we reroute to `DataFrame.__getitem__` to reduce code and reuse implementation. However in the case of a boolean mask, `__getitem__` will apply that to the rows. 

The fix is to special case the boolean mask within `loc`. Thanks for finding and reporting this!
