### ISSUE TITLE
ValueError on big dataframe arithmetic operations

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1058]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 19.10
- **Modin installed from (source or binary)**:
Source
- **Modin version**:
0.7.0+3.g7528bf3
- **Python version**:
Python 3.7.5
- **Exact command to reproduce**:
python3 copartition_test.py

### Describe the problem

When I run the following reproducer I get an exception like this:
```
2020-02-06 15:47:40,633 INFO resource_spec.py:216 -- Starting Ray with 81.3 GiB memory available for workers and up to 18.63 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-02-06 15:47:40,890 WARNING services.py:1365 -- WARNING: object_store_memory is not verified when plasma_directory is set.
       object_id           mjd  passband        flux   flux_err  detected
0            615  59750.421875         2 -544.810303   3.622952         1
1            615  59750.429688         1 -816.434326   5.553370         1
2            615  59750.437500         3 -471.385529   3.801213         1
3            615  59750.445312         4 -388.984985  11.395031         1
4            615  59752.406250         2 -681.858887   4.041204         1
...          ...           ...       ...         ...        ...       ...
99994      53938  60223.203125         1   -4.431781   6.641129         0
99995      53938  60223.210938         3   -8.537231   5.250393         0
99996      53938  60223.222656         4    0.185793   4.947553         0
99997      53938  60223.230469         5   -2.938326   8.078253         0
99998      53938  60226.273438         2   -1.230299   4.908180         0

[99999 rows x 6 columns]
UserWarning: `Series.__array_wrap__` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: Distributing <class 'pandas.core.series.Series'> object. This may take some time.
       object_id           mjd  passband        flux   flux_err  detected  flux_ratio_sq
0            615  59750.421875         2 -544.810303   3.622952         1   22613.378906
1            615  59750.429688         1 -816.434326   5.553370         1   21613.710938
2            615  59750.437500         3 -471.385529   3.801213         1   15378.291016
3            615  59750.445312         4 -388.984985  11.395031         1    1165.291626
4            615  59752.406250         2 -681.858887   4.041204         1   28468.689453
...          ...           ...       ...         ...        ...       ...            ...
99994      53938  60223.203125         1   -4.431781   6.641129         0       0.445321
99995      53938  60223.210938         3   -8.537231   5.250393         0       2.643934
99996      53938  60223.222656         4    0.185793   4.947553         0       0.001410
99997      53938  60223.230469         5   -2.938326   8.078253         0       0.132302
99998      53938  60226.273438         2   -1.230299   4.908180         0       0.062832

[99999 rows x 7 columns]
Traceback (most recent call last):
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/ray/pandas_on_ray/frame/partition.py", line 170, in width
    self._width_cache = ray.get(self._width_cache)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::modin.engines.ray.pandas_on_ray.frame.axis_partition.deploy_ray_func() (pid=58128, ip=10.241.131.52)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 95, in deploy_ray_func
    result = func(*args)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/axis_partition.py", line 189, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 1044, in <lambda>
    lambda df: df.reindex(joined_index, axis=axis),
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 221, in wrapper
    return func(*args, **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3976, in reindex
    return super().reindex(**kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4514, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3864, in _reindex_axes
    index, method, copy, level, fill_value, limit, tolerance
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3886, in _reindex_index
    allow_dups=False,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4577, in _reindex_with_indexers
    copy=copy,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1251, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3362, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "copartition_test.py", line 22, in <module>
    df['flux_by_flux_ratio_sq'] = df['flux'] * df['flux_ratio_sq']
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/dataframe.py", line 2022, in __setitem__
    self._query_compiler.concat(1, value._query_compiler), inplace=True
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/backends/pandas/query_compiler.py", line 123, in concat
    new_modin_frame = self._modin_frame._concat(axis, other_modin_frame, join, sort)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 1128, in _concat
    new_partitions, new_index, new_columns, new_lengths, new_widths, new_dtypes
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 64, in __init__
    self._filter_empties()
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 218, in _filter_empties
    for i in range(len(self._partitions))
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 219, in <listcomp>
    if i < len(self._row_lengths) and self._row_lengths[i] > 0
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 216, in <listcomp>
    if j < len(self._column_widths) and self._column_widths[j] > 0
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 91, in _column_widths
    self._column_widths_cache = [obj.width() for obj in self._partitions[0]]
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 91, in <listcomp>
    self._column_widths_cache = [obj.width() for obj in self._partitions[0]]
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/ray/pandas_on_ray/frame/partition.py", line 172, in width
    handle_ray_task_error(e)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/ray/utils.py", line 8, in handle_ray_task_error
    raise getattr(builtins, s.split(":")[0])("".join(s.split(":")[1:]))
ValueError:  cannot reindex from a duplicate axis
```

Also if I change the line with `read_csv` to the one without `dtypes` I get an error that connection with raylet is lost:

```
2020-02-06 15:51:34,399 INFO resource_spec.py:216 -- Starting Ray with 81.3 GiB memory available for workers and up to 18.63 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-02-06 15:51:34,655 WARNING services.py:1365 -- WARNING: object_store_memory is not verified when plasma_directory is set.
       object_id         mjd  passband        flux   flux_err  detected
0            615  59750.4229         2 -544.810303   3.622952         1
1            615  59750.4306         1 -816.434326   5.553370         1
2            615  59750.4383         3 -471.385529   3.801213         1
3            615  59750.4450         4 -388.984985  11.395031         1
4            615  59752.4070         2 -681.858887   4.041204         1
...          ...         ...       ...         ...        ...       ...
99994      53938  60223.2024         1   -4.431781   6.641129         0
99995      53938  60223.2100         3   -8.537231   5.250393         0
99996      53938  60223.2210         4    0.185793   4.947553         0
99997      53938  60223.2319         5   -2.938326   8.078253         0
99998      53938  60226.2721         2   -1.230299   4.908180         0

[99999 rows x 6 columns]
UserWarning: `Series.__array_wrap__` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: Distributing <class 'pandas.core.series.Series'> object. This may take some time.
F0206 15:51:39.968611 80132 direct_task_transport.cc:154] Lost connection with local raylet. Error: IOError: 8: Received message larger than max (4903907 vs. 4194304)
*** Check failure stack trace: ***
    @     0x7fc5f993d98d  google::LogMessage::Fail()
    @     0x7fc5f993edfc  google::LogMessage::SendToLog()
    @     0x7fc5f993d669  google::LogMessage::Flush()
    @     0x7fc5f993d881  google::LogMessage::~LogMessage()
    @     0x7fc5f97120e9  ray::RayLog::~RayLog()
    @     0x7fc5f96330c9  ray::CoreWorkerDirectTaskSubmitter::RetryLeaseRequest()
    @     0x7fc5f9635863  _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc16WorkerLeaseReplyEEZNS0_29CoreWorkerDirectTaskSubmitter24RequestNewWorkerIfNeededERKSt4pairIiSt6vectorINS0_8ObjectIDESaISC_EEEPKNS4_7AddressEEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
    @     0x7fc5f966cc3f  ray::rpc::ClientCallImpl<>::OnReplyReceived()
    @     0x7fc5f960f9d3  _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
    @     0x7fc5f960e3a5  boost::asio::detail::scheduler::run()
    @     0x7fc5f96124a3  ray::CoreWorker::RunIOService()
    @     0x7fc5f932d302  (unknown)
    @     0x7fc5fa5f3669  start_thread
    @     0x7fc5fa72f323  clone
Aborted (core dumped)
```

### Source code / logs

I couldn't create a reproducer without `read_csv` where dataframe would be created in memory. Perhaps there is some side effect of using read_csv, so download a datafile for this example. The sample data can be downloaded from https://www.kaggle.com/c/PLAsTiCC-2018/data and I tried to reduce it to a smaller size while still reproducing the problem.

```python
#import pandas as pd
import ray
ray.init(huge_pages=True, plasma_directory="/mnt/hugepages")
import modin.pandas as pd
import numpy as np

dtypes = {
    'object_id': 'int32',
    'mjd': 'float32',
    'passband': 'int32',
    'flux': 'float32',
    'flux_err': 'float32',
    'detected': 'int32'
}
# df = pd.read_csv('training_set_100000.csv.zip', compression='zip')
df = pd.read_csv('training_set_100000.csv.zip', compression='zip', dtype=dtypes)
print(df)

df['flux_ratio_sq'] = np.power(df['flux'] / df['flux_err'], 2.0)
print(df)

df['flux_by_flux_ratio_sq'] = df['flux'] * df['flux_ratio_sq']
print(df)
```

**Comment by gshimansky** [comment]
[training_set_100000.csv.zip](https://github.com/modin-project/modin/files/4167915/training_set_100000.csv.zip)

**Comment by devin-petersohn** [comment]
Thanks @gshimansky, I'll take a look.

I'm not aware of any side effect of `read_csv`, but I will dig into it. The code paths for the `__truediv__` (`/` operator) and `__mul__` (`*`) are identical, so it's a bit surprising that it works just a line before.

**Comment by devin-petersohn** [comment]
I wasn't able to reproduce this with the example on a couple of different machines. @gshimansky We can investigate further in the future. For now I'm going to unflag as a bug and remove from this release until we can get something that is reproducible on other machines.

**Comment by gshimansky** [comment]
Yes this problem is quite fragile and probably depends on data distribution. It is necessary to get lucky to reproduce it. You can try to do reproduce it again with a full `plastic` dataset from kaggle.com.

**Comment by gshimansky** [comment]
This exception about duplicate axis apparently is reproducible on Dask too:
```
Traceback (most recent call last):
  File "plasticc_cpu.py", line 160, in <module>
    train_final = etl_cpu(train,train_meta)
  File "plasticc_cpu.py", line 72, in etl_cpu
    df['flux_by_flux_ratio_sq'] = df['flux'] * df['flux_ratio_sq']
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/dataframe.py", line 1976, in __setitem__
    self._query_compiler.concat(1, value._query_compiler), inplace=True
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/backends/pandas/query_compiler.py", line 142, in concat
    new_modin_frame = self._modin_frame._concat(axis, other_modin_frame, join, sort)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 1128, in _concat
    new_partitions, new_index, new_columns, new_lengths, new_widths, new_dtypes
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 64, in __init__
    self._filter_empties()
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 218, in _filter_empties
    for i in range(len(self._partitions))
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 219, in <listcomp>
    if i < len(self._row_lengths) and self._row_lengths[i] > 0
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 216, in <listcomp>
    if j < len(self._column_widths) and self._column_widths[j] > 0
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/dask/pandas_on_dask_futures/frame/data.py", line 39, in _column_widths
    for obj in self._partitions[0]
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/distributed/client.py", line 1885, in gather
    asynchronous=asynchronous,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/distributed/client.py", line 767, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/distributed/utils.py", line 345, in sync
    raise exc.with_traceback(tb)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/distributed/utils.py", line 329, in f
    result[0] = yield future
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/distributed/client.py", line 1741, in _gather
    raise exception.with_traceback(traceback)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/axis_partition.py", line 189, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/engines/base/frame/data.py", line 1044, in <lambda>
    lambda df: df.reindex(joined_index, axis=axis),
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 227, in wrapper
    return func(*args, **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3856, in reindex
    return self._ensure_type(super().reindex(**kwargs))
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4544, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3744, in _reindex_axes
    index, method, copy, level, fill_value, limit, tolerance
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3766, in _reindex_index
    allow_dups=False,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 4613, in _reindex_with_indexers
    copy=copy,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1251, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3099, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```

**Comment by gshimansky** [comment]
I found some other strange behavior. I added `to_csv` call after first arithmetic operation, and for some reason `to_csv` outputs `int32` types as floats. This might be related to this bug:

```python
    df['flux_ratio_sq'] = np.power(df['flux'] / df['flux_err'], 2.0)
    df.to_csv("tmp.csv", index=False)
```
```
object_id,mjd,passband,flux,flux_err,detected,flux_ratio_sq
615.0,59750.42,2.0,-544.8103,3.622952,1.0,22613.379
615.0,59750.43,1.0,-816.4343,5.55337,1.0,21613.71
615.0,59750.438,3.0,-471.38553,3.801213,1.0,15378.291
```
note first, third and 6th column is integers written with decimal point. This doesn't normally happen.

**Comment by gshimansky** [comment]
Calling `obj._to_pandas` inside of `to_csv` implementation gives different results on Dask and Python engines. on Dask all columns are converted into floats for some reason, that's why CSV fils have floats instead of integers.

**Comment by gshimansky** [comment]
I wrote a simplified reproducer
```python
if __name__ == "__main__":
    import numpy as np
    import modin.pandas as pd

    dtypes = {
        'object_id': 'int32',
        'mjd': 'float32',
        'passband': 'int32',
        'flux': 'float32',
        'flux_err': 'float32',
        'detected': 'int32'
    }
    df = pd.read_csv('training_set_100000.csv', dtype=dtypes)
    print(df)

    flux = df['flux']
    flux2 = np.power(flux, 1.0)
    df['flux_ratio_sq'] = flux2
    df.to_csv("modin.csv", index=False)

    df['flux_by_flux_ratio_sq'] = df['flux'] * df['flux_ratio_sq']
    print(df)
```
In addition to an exception being thrown from the last computational line here are other differences from pandas that I've found so far:

1. Column type for `flux2` Series is `float32` on Modin and `float64` on Pandas.
2. In file written in `to_csv` call I see that integer fields `object_id`, `passband` and `detected` are output as floats on Modin and as integers on Pandas.

**Comment by gshimansky** [comment]
Ok, answer to difference number 1 is that Pandas uses `__array_ufunc__` to parse function argument types, and since power is `float` it promotes result to `float64`. If I write `flux2 = np.power(flux, np.float32(1.0))` I get `flux2` result of type `np.float32` too.
Modin doesn't parse argument types, so result type is the same as original Series type.

**Comment by devin-petersohn** [comment]
@gshimansky We should test to see if this is still an issue.

**Comment by gshimansky** [comment]
Yes the original problem is still reproducible on Ray and Dask. The problem comes from plastic benchmark and failing CI tests which run plastic are a proof that problem still exists.

**Comment by Garra1980** [comment]
I'd like to ask @YarShev to take a look since we already dag plasticc a little bit

**Comment by YarShev** [comment]
Okay, I will take a look.

**Comment by YarShev** [comment]
I wasn't able to reproduce the described problem on the current master. I used as data both `training_set.csv` and `training_set_100000.csv` and all the mentioned examples passed. There are no any discrepancies between data types Modin and pandas. @gshimansky , if you don't have any objections I will close the issue.

**Comment by gshimansky** [comment]
It looks like Plastic benchmark runs successfully now, so it means that this problem is gone. Now sure how it was fixed, but we can close the bug for now.

**Comment by devin-petersohn** [comment]
@KangTomwk thanks for posting, would you be able to create a new issue for that? It seems unrelated to this issue, and I would like to make sure it gets resolved.
