### ISSUE TITLE
pd.get_dummies fails when specifiying a prefix list

### ISSUE THREAD

**Issue by biebiep** [modin-project/modin#1070]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 16.04
- **Modin installed from (source or binary)**: Binary
- **Modin version**: 0.7.0
- **Python version**: 3.7
- **Exact command to reproduce**: 

Doesn't work:
pd.get_dummies(df,prefix=['col'])

Does work:
pd.get_dummies(df,columns=['col1','col2'])

### Describe the problem
pd.get_dummies works if you specify a column
pd.get_dummies doesn't work if you specify a prefix.

If you specify a prefix, it results in the attached traceback.

### Source code / logs
---------------------------------------------------------------------------
RayTaskError(ValueError)                  Traceback (most recent call last)
<ipython-input-57-9d7d26cbf8fa> in <module>
----> 8 df = pd.get_dummies(df,prefix=['col1','col2'])

~/anaconda3/lib/python3.7/site-packages/modin/pandas/reshape.py in get_dummies(data, prefix, prefix_sep, dummy_na, columns, sparse, drop_first, dtype)
     59             dummy_na=dummy_na,
     60             drop_first=drop_first,
---> 61             dtype=dtype,
     62         )
     63         return DataFrame(query_compiler=new_manager)

~/anaconda3/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py in get_dummies(self, columns, **kwargs)
   1301                 col_indices=columns
   1302             )._apply_full_axis(
-> 1303                 0, lambda df: pandas.get_dummies(df, **kwargs), new_index=self.index
   1304             )
   1305             untouched_frame = self.drop(columns=columns)

~/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/data.py in _apply_full_axis(self, axis, func, new_index, new_columns, dtypes)
    852         if new_columns is None:
    853             new_columns = self._frame_mgr_cls.get_indices(
--> 854                 1, new_partitions, lambda df: df.columns
    855             )
    856         if new_index is None:

~/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition_manager.py in get_indices(cls, axis, partitions, index_func)
     54                 else []
     55             )
---> 56         new_idx = ray.get(new_idx)
     57         return new_idx[0].append(new_idx[1:]) if len(new_idx) else new_idx
     58 

~/anaconda3/lib/python3.7/site-packages/ray/worker.py in get(object_ids, timeout)
   1490                     worker.core_worker.dump_object_store_memory_usage()
   1491                 if isinstance(value, RayTaskError):
-> 1492                     raise value.as_instanceof_cause()
   1493                 else:
   1494                     raise value

RayTaskError(ValueError): ray_worker (pid=12615, ip=192.168.2.200)
  File "python/ray/_raylet.pyx", line 633, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 634, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 519, in ray._raylet.deserialize_args
ray.exceptions.RayTaskError: ray_worker (pid=12615, ip=192.168.2.200)
  File "python/ray/_raylet.pyx", line 640, in ray._raylet.execute_task
  File "/home/biebiep/anaconda3/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 95, in deploy_ray_func
    result = func(*args)
  File "/home/biebiep/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/axis_partition.py", line 189, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/home/biebiep/anaconda3/lib/python3.7/site-packages/modin/engines/base/frame/data.py", line 659, in _map_reduce_func
    series_result = func(df)
  File "/home/biebiep/anaconda3/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py", line 1303, in <lambda>
    0, lambda df: pandas.get_dummies(df, **kwargs), new_index=self.index
  File "/home/biebiep/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 888, in get_dummies
    check_len(prefix, "prefix")
  File "/home/biebiep/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/reshape.py", line 886, in check_len
    raise ValueError(len_msg)
ValueError: Length of 'prefix' (2) did not match the length of the columns being encoded (0).

**Comment by devin-petersohn** [comment]
Thanks @biebiep for this report!

It is an implementation oversight and will be fixed for the next release. Thanks again!

**Comment by biebiep** [comment]
Thanks for the prompt response!

**Comment by devin-petersohn** [comment]
@biebiep For me, `get_dummies` is working with a prefix. Would you mind posting a small code sample that can reproduce the issue you're seeing? You may need to include some data that produces the error.

**Comment by biebiep** [comment]
The issue is specifically when specifying a list of prefixes.

Apparently, in the original pandas module, when your prefixes are exact matches to the column names, it still runs. However, a list of prefixes that don't exactly match column names also fail.

This is apparently just a funny behavior of the pandas module and incorrect use anyway.
I'll see if i can share a synthetic later today.

**Comment by devin-petersohn** [comment]
I see, on certain dataframes the error can happen, depending on partitioning.

The message above was strange because `Length of 'prefix' (2) did not match the length of the columns being encoded (0).` implies that there are no columns getting encoded on a partition. I will test some things, but it may be possible to just convert the list to a dictionary and it will just work.

**Comment by devin-petersohn** [comment]
Hi @biebiep I cannot reproduce the issue with any of my attempts, but I do get a pandas exception with `ValueError: Length of 'prefix' (1) did not match the length of the columns being encoded (0).` when I try to run with a list of prefix values. Would it be possible to provide a reproducible way to debug this? I know it has been some time, thanks for your patience!

**Comment by devin-petersohn** [comment]
Flagging needs more information until we can figure out how to reproduce.

**Comment by claudiobrandy** [comment]
@devin-petersohn : Has it been resolved? A colleague today came with this question and, after trying some different column selections, I believe I figured out what's happening.

**Comment by devin-petersohn** [comment]
@claudiobrandy It wasn't resolved, I wasn't able to reproduce it on any of our test data. If you have some small example that can reproduce it we can get it fixed.

**Comment by claudiobrandy** [comment]
Thanks for your reply @devin-petersohn.

The issue seems to happen when there are columns that don't need encoding.

pd.get_dummies(data, prefix=['a', 'b', 'c', 'd', 'e']) expects the _data_ DataFrame to have 5 "one_hot_encodable" columns.

If i.e. 2 of _data_'s columns are filled with 0 and 1 values only, the method will not count them as encodable and will find a mismatch between the number of columns in _data_ (5) and the number of columns it needs to to encode (3).

Sales area in my company was having an issue with a model they were trying to immplement and asked me today to review it; that's how I found this issue and it's solution. As the data used is confidential, if you need it to test my solution I would need to submit it for anonymization.

Regards,
Claudio

**Comment by claudiobrandy** [comment]
Hi @devin-petersohn . Were you able to look at my previous message? Would you need me to supply additional info?

**Comment by devin-petersohn** [comment]
Hi @claudiobrandy thanks for the update, this is very helpful. Sorry for the delay, for some reason GitHub ate the notification on this.

Based on your description I was able to create this self contained reproducer:

```python
import modin.pandas as pd
df = pd.DataFrame({"col1":[1,0,0,1,0], "col2":[0,1,1,0,1], "col3":["A", "A", "B", "A", "C"]})
pd.get_dummies(df, ["col1", "col2", "col3"])
```

This produces the following error (also on master):

```
RayTaskError(ValueError): ray::modin.engines.ray.pandas_on_ray.frame.partition.deploy_ray_func() (pid=87591, ip=192.168.0.115)
  File "python/ray/_raylet.pyx", line 442, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 464, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::modin.engines.ray.pandas_on_ray.frame.axis_partition.deploy_ray_func() (pid=87591, ip=192.168.0.115)
  File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
  File "/Users/DevinPetersohn/software_builds/modin/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 103, in deploy_ray_func
    result = func(*args)
  File "/Users/DevinPetersohn/software_builds/modin/modin/engines/base/frame/axis_partition.py", line 202, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/Users/DevinPetersohn/software_builds/modin/modin/engines/base/frame/data.py", line 963, in _map_reduce_func
    series_result = func(df)
  File "/Users/DevinPetersohn/software_builds/modin/modin/backends/pandas/query_compiler.py", line 2506, in <lambda>
    0, lambda df: pandas.get_dummies(df, **kwargs), new_index=self.index
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/reshape.py", line 884, in get_dummies
    check_len(prefix, "prefix")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/reshape/reshape.py", line 882, in check_len
    raise ValueError(len_msg)
ValueError: Length of 'prefix' (3) did not match the length of the columns being encoded (1).
```

**Comment by devin-petersohn** [comment]
As a side note, there is a simple workaround where you can omit the columns with only 0/1 to the `prefix` arg. From the previous comment example:

```python
import modin.pandas as pd
df = pd.DataFrame({"col1":[1,0,0,1,0], "col2":[0,1,1,0,1], "col3":["A", "A", "B", "A", "C"]})
# pd.get_dummies(df, ["col1", "col2", "col3"])
pd.get_dummies(df, ["col3"])
```

This will result in the correct dataframe. It is only meant as a temporary workaround until this bug is fixed. Thanks again for the report @claudiobrandy.

**Comment by mvashishtha** [comment]
@devin-petersohn your example is not a Modin bug. I get the same error from Pandas:

```
import pandas as pd
df = pd.DataFrame({"col1":[1,0,0,1,0], "col2":[0,1,1,0,1], "col3":["A", "A", "B", "A", "C"]})
pd.get_dummies(df, ["col1", "col2", "col3"])
```

`get_dummies` only converts columns with categorical variables into indicator variables. Presumably, Pandas will consider string variables, but not integer variables, to be categorical. Here's a smaller failing example with Pandas:

```
import pandas as pd
df = pd.DataFrame({"col1":[1,0]})
pd.get_dummies(df, ["col1"])
```

and it works if I convert the 0s and 1s to categories manually:

```
import pandas as pd
df = pd.DataFrame({"col1":[1,0]})
df['col1'] = df['col1'].astype('category')
pd.get_dummies(df, ["col1"])
```

but also if I use strings instead of integers:

```
import pandas as pd
df = pd.DataFrame({"col1":["1","0"]})
pd.get_dummies(df, ["col1"])
```

Should we close this Modin issue? Should we request that Pandas get_dummies() convert integer columns to category variables as well?

**Comment by karendolan** [comment]
Not sure if it's too late, but here is another example to get that ValueError
```
p0 = pd.DataFrame()
p0['weekday'] = ['Friday']
p0['fruit'] = ['Apple']
p0['value'] = [0]
p0['value2'] = [2] 
# When this column is left out of the prefix list, the ValueError is thrown
p0['another_text_column'] = ['ABCD']
print(p0)
p0 = pd.get_dummies(p0, prefix=['weekday', 'fruit'], drop_first=True, dtype=int)
# When **ALL** the columns that are categorical columns are listed in the prefix list, no ValueError is thrown
# p0 = pd.get_dummies(p0, prefix=['weekday', 'fruit', 'another_text_column'], drop_first=True, dtype=int)
print(p0)
print(p0.shape)
```
I got the ValueError when I only wanted SOME of the categorical columns to be converted to dummies. When I list ALL of the categorical columns, I don't get the error.

I really didn't want all the categorical columns converted, so I used the "columns=" workaround from this ticket to just convert the categorical columns that I wanted to convert.

**Comment by anmyachev** [comment]
Hi @karendolan, Modin's behavior is equivalent to that of pandas in your case.

According to [docs](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html?highlight=get_dummies#pandas.get_dummies):
"String to append DataFrame column names. Pass a list with length **equal to the number of columns** when calling get_dummies on a DataFrame. Alternatively, prefix can be a dictionary mapping column names to prefixes."
