### ISSUE TITLE
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1073]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 19.10
- **Modin installed from (source or binary)**:
- **Modin version**:
0.7.0+11.g2c20857
- **Python version**:
Python 3.7.5
- **Exact command to reproduce**:

### Describe the problem

Thank you for fixing #1033, it allowed me to move further in running my benchmarks. Unfortunately there are still problems related to `groupby` calls. Two benchmarks that failed on it fail different groupby calls with the same exception and slightly different stack traces. I am working on a simple reproducer, so right now I only have exception stacks:

This comes from Taxi benchmarks
```
Traceback (most recent call last):
  File "/localdisk/gashiman/omniscripts/taxi/taxibench_pandas.py", line 190, in <module>
    query(query_df)
  File "/localdisk/gashiman/omniscripts/taxi/taxibench_pandas.py", line 95, in q3
    return transformed.groupby(['passenger_count','pickup_datetime'])[['passenger_count','pickup_datetime']].count()['passenger_count']
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 249, in __getitem__
    return SeriesGroupBy(self._default_to_pandas(lambda df: df.__getitem__(key)))
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 535, in _default_to_pandas
    return self._df._default_to_pandas(groupby_on_multiple_columns)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/base.py", line 227, in _default_to_pandas
    result = op(pandas_obj, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 533, in groupby_on_multiple_columns
    return f(df.groupby(by=by, axis=self._axis, **self._kwargs), **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 652, in _get_grouper
    if not isinstance(gpr, Grouping)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 347, in __init__
    raise ValueError("Grouper for '{}' not 1-dimensional".format(t))
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
```

and this one is from mortgage:
```
Traceback (most recent call last):
  File "mortgage_cpu.py", line 518, in <module>
    run_cpu_workflow(year=year, quarter=(quarter % 4 + 1), perf_file=str(f))
  File "mortgage_cpu.py", line 91, in run_cpu_workflow
    df_features_12 = create_12_mon_features(joined_df)
  File "mortgage_cpu.py", line 285, in create_12_mon_features
    tmpdf = tmpdf.groupby(['loan_id', 'josh_mody_n'], as_index=False).agg({'delinquency_12': 'max','upb_12': 'min'})
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 383, in agg
    return self.aggregate(arg, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 277, in aggregate
    lambda df: df.aggregate(arg, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 535, in _default_to_pandas
    return self._df._default_to_pandas(groupby_on_multiple_columns)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/base.py", line 227, in _default_to_pandas
    result = op(pandas_obj, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 533, in groupby_on_multiple_columns
    return f(df.groupby(by=by, axis=self._axis, **self._kwargs), **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 652, in _get_grouper
    if not isinstance(gpr, Grouping)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 347, in __init__
    raise ValueError("Grouper for '{}' not 1-dimensional".format(t))
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
```

**Comment by devin-petersohn** [comment]
Thanks @gshimansky, #533 also reports this. I had fixed it at one point with #549, but it broke other things that had been working.

Since the other issue is older and stale, I'll close that one in favor of this.

**Comment by devin-petersohn** [comment]
I think we'll push this to 0.7.2 because there's a lot on 0.7.1 left and I'd like to release it soon.

**Comment by gshimansky** [comment]
Reproducer for exception from Taxi benchmark:
```python
import numpy as np
#import pandas as pd
import ray
ray.init(huge_pages=False, plasma_directory="/localdisk2/gashiman/plasma", memory=1024*1024*1024*200, object_store_memory=1024*1024*1024*200)
import modin.pandas as pd

df = pd.DataFrame([[1, 2, np.datetime64('2013-08-01 08:14:37')],
                   [4, 5, np.datetime64('2014-08-01 09:13:00')],
                   [7, 8, np.datetime64('2015-08-01 09:48:00')]],
                  index=[1, 2, 3],
                  columns=['max_speed', 'shield', 'timestamp'])
print(df)

transformed = df[['max_speed', 'timestamp']].transform({'max_speed': lambda x: x, 'timestamp': lambda x: pd.DatetimeIndex(x).year})
print(transformed)

df1 = transformed.groupby(['max_speed', 'timestamp'])[['max_speed', 'timestamp']].count()['max_speed']
print(df1)
```

Pandas output looks like this:
```
   max_speed  shield           timestamp
1          1       2 2013-08-01 08:14:37
2          4       5 2014-08-01 09:13:00
3          7       8 2015-08-01 09:48:00
   max_speed  timestamp
1          1       2013
2          4       2014
3          7       2015
max_speed  timestamp
1          2013         1
4          2014         1
7          2015         1
Name: max_speed, dtype: int64
```
while Modin output looks like this:
```
2020-02-12 14:06:49,951 INFO resource_spec.py:216 -- Starting Ray with 200.0 GiB memory available for workers and up to 200.0 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-02-12 14:06:50,246 WARNING services.py:1365 -- WARNING: object_store_memory is not verified when plasma_directory is set.
UserWarning: Distributing <class 'list'> object. This may take some time.
   max_speed  shield           timestamp
1          1       2 2013-08-01 08:14:37
2          4       5 2014-08-01 09:13:00
3          7       8 2015-08-01 09:48:00
UserWarning: `DataFrame.agg` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
UserWarning: Distributing <class 'pandas.core.frame.DataFrame'> object. This may take some time.
   max_speed  timestamp
1          1       2013
2          4       2014
3          7       2015
UserWarning: Multi-column groupby is a new feature. Please report any bugs/issues to bug_reports@modin.org.
UserWarning: `DataFrame.groupby_on_multiple_columns` defaulting to pandas implementation.
Traceback (most recent call last):
  File "groupby_test3.py", line 17, in <module>
    df1 = transformed.groupby(['max_speed', 'timestamp'])[['max_speed', 'timestamp']].count()['max_speed']
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 249, in __getitem__
    return SeriesGroupBy(self._default_to_pandas(lambda df: df.__getitem__(key)))
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 535, in _default_to_pandas
    return self._df._default_to_pandas(groupby_on_multiple_columns)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/base.py", line 227, in _default_to_pandas
    result = op(pandas_obj, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 533, in groupby_on_multiple_columns
    return f(df.groupby(by=by, axis=self._axis, **self._kwargs), **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 652, in _get_grouper
    if not isinstance(gpr, Grouping)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 347, in __init__
    raise ValueError("Grouper for '{}' not 1-dimensional".format(t))
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
```

**Comment by gshimansky** [comment]
Reproducer for exception from mortgage benchmark:
```python
import numpy as np
#import pandas as pd
import ray
ray.init(huge_pages=False, plasma_directory="/localdisk2/gashiman/plasma", memory=1024*1024*1024*200, object_store_memory=1024*1024*1024*200)
import modin.pandas as pd

df = pd.DataFrame([[1, 1, 2, 10],
                   [2, 4, 5, 20],
                   [3, 7, 8, 30]],
                  index=[1, 2, 3],
                  columns=['id', 'max_speed', 'shield', 'health'])
print(df)

df1 = df.groupby(['id', 'health'], as_index=False).agg({'max_speed': 'max', 'shield': 'max'})
print(df1)
```
Pandas output looks like this
```
import numpy as np
#import pandas as pd
import ray
ray.init(huge_pages=False, plasma_directory="/localdisk2/gashiman/plasma", memory=1024*1024*1024*200, object_store_memory=1024*1024*1024*200)
import modin.pandas as pd

df = pd.DataFrame([[1, 1, 2, 10],
                   [2, 4, 5, 20],
                   [3, 7, 8, 30]],
                  index=[1, 2, 3],
                  columns=['id', 'max_speed', 'shield', 'health'])
print(df)

df1 = df.groupby(['id', 'health'], as_index=False).agg({'max_speed': 'max', 'shield': 'max'})
print(df1)
```
while Modin output looks like this
```
2020-02-12 14:38:49,476 INFO resource_spec.py:216 -- Starting Ray with 200.0 GiB memory available for workers and up to 200.0 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-02-12 14:38:49,772 WARNING services.py:1365 -- WARNING: object_store_memory is not verified when plasma_directory is set.
UserWarning: Distributing <class 'list'> object. This may take some time.
   id  max_speed  shield  health
1   1          1       2      10
2   2          4       5      20
3   3          7       8      30
UserWarning: Multi-column groupby is a new feature. Please report any bugs/issues to bug_reports@modin.org.
UserWarning: `DataFrame.groupby_on_multiple_columns` defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.
Traceback (most recent call last):
  File "groupby_test4.py", line 14, in <module>
    df1 = df.groupby(['id', 'health'], as_index=False).agg({'max_speed': 'max', 'shield': 'max'})
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 383, in agg
    return self.aggregate(arg, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 277, in aggregate
    lambda df: df.aggregate(arg, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 535, in _default_to_pandas
    return self._df._default_to_pandas(groupby_on_multiple_columns)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/base.py", line 227, in _default_to_pandas
    result = op(pandas_obj, *args, **kwargs)
  File "/nfs/site/proj/scripting_tools/gashiman/modin/modin/pandas/groupby.py", line 533, in groupby_on_multiple_columns
    return f(df.groupby(by=by, axis=self._axis, **self._kwargs), **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 7894, in groupby
    **kwargs
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 2522, in groupby
    return klass(obj, by, **kwds)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 391, in __init__
    mutated=self.mutated,
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 652, in _get_grouper
    if not isinstance(gpr, Grouping)
  File "/nfs/site/home/gashiman/.local/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 347, in __init__
    raise ValueError("Grouper for '{}' not 1-dimensional".format(t))
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
```

**Comment by gshimansky** [comment]
I tried debugging the 2nd reproducer of problem with this groupby and found out that the reason for it is that `by` parameter passed to groupby is wrong. In case of Pandas it is a list `['id', 'health']` while in case of Modin I get a DataFrame object with value `id health [1: 1 10], [2: 2 20], [3: 3 30]`.

**Comment by devin-petersohn** [comment]
We have a slightly different internal way of handling groupby with multiple columns. We should be able to fix this relatively easily, but you are correct in that it is a result of how we pass a "masked dataframe" around internally to track the groupby with multiple columns.

**Comment by gshimansky** [comment]
What I mean is that when Pandas `groupby` is called, it should have a list type `by` parameter, not a DataFrame as it happens now. That's the reason why Pandas `groupby` raises an exception, it doesn't expect `by` of such type. I think the problem lies in this code

```python
        if isinstance(self._by, type(self._query_compiler)):
            by = self._by.to_pandas().squeeze() # This statement converts to pandas DataFrame that is later passed into Pandas groupby
        else:
            by = self._by

        def groupby_on_multiple_columns(df):
            return f(df.groupby(by=by, axis=self._axis, **self._kwargs), **kwargs)
```
where `by` is passed down into `groupby_on_multiple_columns` closure as a DataFrame. A list of column names should be extracted from it instead.

**Comment by devin-petersohn** [comment]
I understand now, you are correct. We also need to add a test for this.

**Comment by gshimansky** [comment]
PR #1122 has a fix which allowed Taxi benchmark query number 3 to pass, but now it fails on a more complex query number 4. Reproducer for it looks like this, and somehow groupby loses `timestamp` column:
```python
import numpy as np
#import pandas as pd
import ray
ray.init(huge_pages=False, plasma_directory="/localdisk/gashiman/plasma", memory=1024*1024*1024*200, object_store_memory=1024*1024*1024*200)
import modin.pandas as pd

df = pd.DataFrame([[2, np.datetime64('2013-08-01 08:14:37'), 1.1],
                   [5, np.datetime64('2014-08-01 09:13:00'), 2.2],
                   [8, np.datetime64('2015-08-01 09:48:00'), 3.3]],
                  index=[1, 2, 3],
                  columns=['health', 'timestamp', 'shield'])
print(df)

transformed = df[['health', 'timestamp', 'shield']].transform({
    'health': lambda x: x,
    'timestamp': lambda x: pd.DatetimeIndex(x).year,
    'shield': lambda x: x}).groupby(['health', 'timestamp', 'shield'])
print(transformed)

df1 = transformed.size().reset_index().sort_values(by=['timestamp',0],ascending=[True,False])
print(df1)
```

**Comment by devin-petersohn** [comment]
Closing via #1122

**Comment by linehammer** [comment]
Just like a lot of cryptic pandas errors,  for some or all indexes in DataFrame , you are assigning MORE THAN just one label, groupby() doesn't know which label it should use for grouping. [DataFrame groupby()](http://net-informations.com/ds/pda/gby.htm) doesn't need to care about df or which columns , groupby() only cares about one thing, a lookup table that tells it which df.index is mapped to which label (ie. group name). To solve this, get rid of the multi-index by using
