### ISSUE TITLE
read parquet returns ValueError: Length mismatch: Expected axis has 40 elements, new values have 41 elements

### ISSUE THREAD

**Issue by bharatk101** [modin-project/modin#1451]
### System information
- **OS Platform and Distribution** : elementary OS 5.1.4 Hera
- **Modin version** : 0.7.3
- **Python version**: 3.7.6
- **Code we can use to reproduce**: 
import modin.pandas as pd
df = pd.read_parquet('sales')

### Describe the problem
Reading parquet folder returns with value mismatch error

### Source code / logs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/modin/pandas/io.py", line 42, in read_parquet
    path=path, columns=columns, engine=engine, **kwargs
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/modin/data_management/factories.py", line 57, in read_parquet
    return cls._determine_engine()._read_parquet(**kwargs)
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/modin/data_management/factories.py", line 61, in _read_parquet
    return cls.io_cls.read_parquet(**kwargs)
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/modin/engines/base/io/column_stores/parquet_reader.py", line 83, in read
    return cls.build_query_compiler(path, columns, **kwargs)
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/modin/engines/base/io/column_stores/column_store_reader.py", line 113, in build_query_compiler
    dtypes = cls.build_dtypes(partition_ids[-1], columns)
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/modin/engines/base/io/column_stores/column_store_reader.py", line 104, in build_dtypes
    dtypes.index = columns
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/pandas/core/generic.py", line 5287, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/pandas/core/series.py", line 401, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/bharat/anaconda3/envs/dev_vizb/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 178, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 40 elements, new values have 41 elements

**Comment by devin-petersohn** [comment]
Hi @bharatk101 thanks for the report!

Is it possible to share the parquet file that caused this? I tried to reproduce with our test files and some other random data but haven't been able to reproduce.

**Comment by bharatk101** [comment]
Yes, you can find it here
https://drive.google.com/open?id=1vZ0eSN6Fr_ilt38LuqjWT7QlPxG2Qy4W

**Comment by devin-petersohn** [comment]
Thanks @bharatk101, I was able to reproduce, the fix was quite simple.

**Comment by bharatk101** [comment]
Is there any way I can use that in my project?

**Comment by devin-petersohn** [comment]
The PR #1454 has the fix, it will be merged in the next day or so.

Once it is merged, you can install from the master branch following the commands in the documentation: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by bharatk101** [comment]
Ok cool, thanks
