### ISSUE TITLE
Indexing DataFrameGroupBy with [["column"]] causes exception in aggregate

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1511]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+60.gaa95d57.dirty

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=[1, 2, 3],
                  columns=['max_speed', 'shield'])
print(df)

gb = df.groupby('max_speed')
print("type(gb) = ", type(gb))

col2 = gb[['max_speed']]
print("type(col2) = ", type(col2))
df2 = col2.count()
print(type(df2))
print(df2)
```

### Describe the problem

Running this code causes an exception like this:
```
Traceback (most recent call last):
  File "groupby_test.py", line 19, in <module>
    df2 = col2.count()
  File "/localdisk/gashiman/modin/modin/pandas/groupby.py", line 454, in count
    return self._groupby_reduce(
  File "/localdisk/gashiman/modin/modin/pandas/groupby.py", line 521, in _groupby_reduce
    query_compiler=groupby_qc.groupby_reduce(
  File "/localdisk/gashiman/modin/modin/backends/pandas/query_compiler.py", line 1169, in groupby_reduce
    first_column = qc.columns[0]
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3929, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
```
and PR #1510 didn't help with this problem.

**Comment by devin-petersohn** [comment]
Closing this, as it was fixed and is no longer reproducible.
