### ISSUE TITLE
GroupBy on multiple columns creates an unprintable dataframe

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1520]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+66.g6d419f4

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  index=[1, 2, 3],
                  columns=['id', 'max_speed', 'shield'])
print(df)

gb = df.groupby(['max_speed', 'shield'])
df1 = gb.all()
print(df1)
print(df1.axes)
```

### Describe the problem

When running on Modin the line `print(df1)` throws an exception:
```
Traceback (most recent call last):
  File "groupby_test9.py", line 10, in <module>
    print(df1)
  File "/localdisk/gashiman/modin/modin/pandas/base.py", line 3356, in __str__
    return repr(self)
  File "/localdisk/gashiman/modin/modin/pandas/dataframe.py", line 153, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/localdisk/gashiman/modin/modin/pandas/base.py", line 100, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()
  File "/localdisk/gashiman/modin/modin/backends/pandas/query_compiler.py", line 89, in to_pandas
    return self._modin_frame.to_pandas()
  File "/localdisk/gashiman/modin/modin/engines/base/frame/data.py", line 1293, in to_pandas
    df = self._frame_mgr_cls.to_pandas(self._partitions)
  File "/localdisk/gashiman/modin/modin/engines/base/frame/partition_manager.py", line 258, in to_pandas
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
  File "/localdisk/gashiman/modin/modin/engines/base/frame/partition_manager.py", line 258, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
  File "/localdisk/gashiman/modin/modin/engines/base/frame/partition_manager.py", line 258, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 115, in to_pandas
    dataframe = self.get()
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 48, in get
    self.drain_call_queue()
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 88, in drain_call_queue
    self.apply(lambda x: x)
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 76, in apply
    self.data = call_queue_closure(self.data, self.call_queue)
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 73, in call_queue_closure
    raise e
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 70, in call_queue_closure
    result = func(result, **kwargs)
  File "/localdisk/gashiman/modin/modin/engines/python/pandas_on_python/frame/partition.py", line 92, in <lambda>
    lambda df: pandas.DataFrame(df.iloc[row_indices, col_indices])
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 2067, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 703, in _has_valid_tuple
    self._validate_key(k, i)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/core/indexing.py", line 2009, in _validate_key
    raise IndexError("positional indexers are out-of-bounds")
IndexError: positional indexers are out-of-bounds
```

**Comment by gshimansky** [comment]
This is a result of incorrect calculation of columns in the result dataframe in `_groupby_reduce` and `_reduce`.
