### ISSUE TITLE
RuntimeError: The ray global state API cannot be used before ray.init has been called.

### ISSUE THREAD

**Issue by Sangram9693** [modin-project/modin#1528]
Hi Team,

I have python flask application, here i am using **modin.pandas** and **ray** packages.
```
ray==0.8.4
modin==0.7.3
```

Below is my code
```
import modin.pandas as pd
import ray
os.environ["MODIN_ENGINE"] = "ray"  
ray.init(plasma_directory="/", object_store_memory=10**10,ignore_reinit_error=True)
```
 **But i am getting runtime error**

```
spawned uWSGI worker 4 (pid: 8, cores: 1)
/usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/src/audiencemangement/WSGI.py", line 1, in <module>
    from filter_service import app
  File "/usr/src/audiencemangement/filter_service.py", line 11, in <module>
    import getMasterData
  File "/usr/src/audiencemangement/getMasterData.py", line 2, in <module>
    import modin.pandas as pd
  File "/usr/local/lib/python3.6/site-packages/modin/pandas/__init__.py", line 242, in <module>
    num_cpus = ray.cluster_resources()["CPU"]
  File "/usr/local/lib/python3.6/site-packages/ray/state.py", line 1209, in cluster_resources
    return state.cluster_resources()
  File "/usr/local/lib/python3.6/site-packages/ray/state.py", line 884, in cluster_resources
    self._check_connected()
  File "/usr/local/lib/python3.6/site-packages/ray/state.py", line 146, in _check_connected
    raise RuntimeError("The ray global state API cannot be used "
RuntimeError: The ray global state API cannot be used before ray.init has been called.
unable to load app 0 (mountpoint='') (callable not found or import error)
Traceback (most recent call last):
  File "/usr/src/audiencemangement/WSGI.py", line 1, in <module>
    from filter_service import app
  File "/usr/src/audiencemangement/filter_service.py", line 11, in <module>
    import getMasterData
  File "/usr/src/audiencemangement/getMasterData.py", line 2, in <module>
    import modin.pandas as pd
  File "/usr/local/lib/python3.6/site-packages/modin/pandas/__init__.py", line 242, in <module>
    num_cpus = ray.cluster_resources()["CPU"]
  File "/usr/local/lib/python3.6/site-packages/ray/state.py", line 1209, in cluster_resources
    return state.cluster_resources()
  File "/usr/local/lib/python3.6/site-packages/ray/state.py", line 884, in cluster_resources
    self._check_connected()
  File "/usr/local/lib/python3.6/site-packages/ray/state.py", line 146, in _check_connected
    raise RuntimeError("The ray global state API cannot be used "

```

Can anyone help me how to fix this?

**Comment by gshimansky** [comment]
The only change that is needed in this code is to `import modin.pandas` after `ray.init` call.

**Comment by Sangram9693** [comment]
Thanks @gshimansky ,

Now i am not getting that error. but response i am not getting. I am getting below warning.

```
UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
2020-06-04 08:56:12,086 WARNING worker.py:1072 -- The actor or task with ID 45b95b1c8bd3a9c4ffffffff0100 is pending and cannot currently be scheduled. It requires {CPU: 1.000000} for execution and {CPU: 1.000000} for placement, but this node only has remaining {node:172.17.0.5: 1.000000}, {CPU: 4.000000}, {memory: 4.589844 GiB}, {object_store_memory: 6.396484 GiB}. In total there are 1 pending tasks and 0 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```

**Comment by gshimansky** [comment]
Looking at parameters that you pass to Ray, are you sure that `/` directory is writable?
You can try to figure out Ray failures in `/tmp/ray/session_latest/logs`.

**Comment by devin-petersohn** [comment]
Yes, @gshimansky is right about checking permissions `"/"` as the plasma directory.

I also notice that Ray is saying that all resources are occupied by Actors. Is there Ray related code occupying all of the resources?

Ray cannot schedule new tasks on existing occupied resources. Ray does not allow sharing of existing Actors.

**Comment by Sangram9693** [comment]
@gshimansky thank you for your reply.

Just want to know this plasma_directory director is using for writing the file ? And it should have permission to write in to this ?

If I remove this plasma_directory parameter from init function then what will be impact ?

Actually I am new to this module. So I am asking all these things here

**Comment by gshimansky** [comment]
In my experience you will not see any files created in `plasma_directory` but you will see disk space occupied in on that filesystem while you have running Ray processes. So you need write permission and you need enough disk space. Files are memory mapped and are invisible.

**Comment by aregm** [comment]
Please, reopen the issue if you still have problems.
