### ISSUE TITLE
TypeError: unhashable type: 'Series'

### ISSUE THREAD

**Issue by loretoparisi** [modin-project/modin#1591]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
```
mbploreto:webservice loretoparisi$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```
- **Modin version** (`modin.__version__`):
```
ip-192-168-1-168:script loretoparisi$ python3 -c "import modin;print(modin.__version__);print(modin.__file__)";
0.7.3
/usr/local/lib/python3.7/site-packages/modin/__init__.py
```
- **Python version**:
```
ip-192-168-1-168:script loretoparisi$ python3 --version
Python 3.7.7
```
- **Numpy version**:
```
ip-192-168-1-168:script loretoparisi$ python3 -c "import numpy;print(numpy.__version__);print(numpy.__file__)";
1.15.4
/usr/local/lib/python3.7/site-packages/numpy/__init__.py
```
- **Code we can use to reproduce**:

### Describe the problem

Stacktrack:
```
Traceback (most recent call last):
  File "dataset.stats.py", line 18, in <module>
    import modin.pandas as pd
  File "/usr/local/lib/python3.7/site-packages/modin/pandas/__init__.py", line 14, in <module>
    import pandas
  File "/usr/local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import (
  File "/usr/local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 9, in <module>
    _np_version = np.__version__
AttributeError: module 'numpy' has no attribute '__version__'
ip-192-168-1-168:script loretoparisi$ python3 dataset.stats.py -p /root/20200605_audio_dataset_asin.csv 
Traceback (most recent call last):
  File "dataset.stats.py", line 38, in <module>
    stats['keys'][col]['count'] = len(df[col].groupby([df[col]]))
  File "/usr/local/lib/python3.7/site-packages/modin/pandas/series.py", line 649, in groupby
    drop=False,
  File "/usr/local/lib/python3.7/site-packages/modin/pandas/groupby.py", line 65, in __init__
    and all(obj in self._query_compiler.columns for obj in self._by)
  File "/usr/local/lib/python3.7/site-packages/modin/pandas/groupby.py", line 65, in <genexpr>
    and all(obj in self._query_compiler.columns for obj in self._by)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3899, in __contains__
    hash(key)
TypeError: unhashable type: 'Series'
```

### Source code / logs

```python
### built-in
import argparse
import json

### dependencies
# parallel pandas - https://github.com/modin-project/modin
import modin.pandas as pd

if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument('--path', '-p', action='store', type=str, help='Dataset file path', default='', required=True)
    args = parser.parse_args()
    
    stats = {} # holds df stats
    stats['keys'] = {}
        
    df = pd.read_csv(args.path, sep='\t')

    # prepare data holder
    for col in df.columns:
        if col not in stats['keys']:
            stats['keys'][col] = {}
    
    # calculate stats
    for col in df.columns:
        stats['keys'][col]['count'] = len(df[col].groupby([df[col]]))
        stats['keys'][col]['unique'] = len(df[col].groupby([df[col]]).nunique())
        
    print(json.dumps(stats, indent=4))
```

**Comment by Garra1980** [comment]
What is the reason to use namely [df[col]]? As far as I understand len(df[col].groupby(df[col])) could be used in the example

**Comment by loretoparisi** [comment]
@Garra1980 good catch 🥇 
I have modified it as follows:

```python
# prepare data holder
    for col in df.columns:
        if col not in stats['keys']:
            stats['keys'][col] = {}
            stats['count'] = len(df)
    
    # calculate stats
    for col in df.columns:
        stats['keys'][col]['count'] = len(df[col].groupby(df[col]))
        stats['keys'][col]['unique'] = len(df[col].groupby(df[col]).nunique())
        stats['keys'][col]['null'] = df[col].isnull().sum()
        
    print( json.dumps(stats, indent=4, cls=NumpyEncoder))
```

Now it works. The reason was definitively that one!
Since `groupby` has a list as input it worked anyways, but it was an improper use btw.
