### ISSUE TITLE
The console output of `pandas.Series` and `modin.Series` is different in the parameters

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#1646]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.2 LTS
- **Modin version**: 0.7.3
- **Python version**: 3.8.2
- **Exact command to reproduce**:
```
import pandas
import modin.pandas as pd

index = pandas.date_range("1/1/2000", periods=13, freq="T")

pandas_series = pandas.Series(range(13), index=index)
modin_series = pd.Series(range(13), index=index)

print('Pandas out:\n', pandas_series)
print('\nModin out:\n', modin_series)
```

### Describe the problem
The console output of `pandas.Series` and `modin.Series` is different in the parameters.

### Source code / logs

```
Pandas out:
 2000-01-01 00:00:00     0
2000-01-01 00:01:00     1
2000-01-01 00:02:00     2
2000-01-01 00:03:00     3
2000-01-01 00:04:00     4
2000-01-01 00:05:00     5
2000-01-01 00:06:00     6
2000-01-01 00:07:00     7
2000-01-01 00:08:00     8
2000-01-01 00:09:00     9
2000-01-01 00:10:00    10
2000-01-01 00:11:00    11
2000-01-01 00:12:00    12
Freq: T, dtype: int64

Modin out:
 2000-01-01 00:00:00     0
2000-01-01 00:01:00     1
2000-01-01 00:02:00     2
2000-01-01 00:03:00     3
2000-01-01 00:04:00     4
2000-01-01 00:05:00     5
2000-01-01 00:06:00     6
2000-01-01 00:07:00     7
2000-01-01 00:08:00     8
2000-01-01 00:09:00     9
2000-01-01 00:10:00    10
2000-01-01 00:11:00    11
2000-01-01 00:12:00    12
Freq: T, Name: __reduced__, dtype: int64
dtype: int64
```

**Comment by prutskov** [comment]
Also bug with printing pure `modin.pandas.Series` was detected.

Code for reproduce:
```
import numpy as np
import pandas
import modin.pandas as pd

pandas_series = pandas.Series(dtype=np.int64)
modin_series = pd.Series(dtype=np.int64)

print('\nPandas output:\n', pandas_series)
print('\nModin output:\n', modin_series)
```

Output:
```
UserWarning: Distributing <class 'NoneType'> object. This may take some time.

Pandas output:
 Series([], dtype: int64)

Modin output:
 Traceback (most recent call last):
  File "tester.py", line 9, in <module>
    print('\nModin output:\n', modin_series)
  File "/localdisk/aprutsko/modin/modin/pandas/base.py", line 3483, in __str__
    return repr(self)
  File "/localdisk/aprutsko/modin/modin/pandas/series.py", line 298, in __repr__
    temp_df = temp_df.iloc[:, 0]
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexing.py", line 2067, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexing.py", line 703, in _has_valid_tuple
    self._validate_key(k, i)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexing.py", line 1994, in _validate_key
    self._validate_integer(key, axis)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
I translate this issue into a bug type.

**Comment by prutskov** [comment]
Issue with pure `modin.Series` was described in #1647
