### ISSUE TITLE
Printing empty modin.Series leads to raising exception

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1647]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 1809
- **Modin version** (`modin.__version__`): 0.7.3+148.ga2d7189
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
if __name__ == "__main__":
    import modin.pandas as pd
    
    s = pd.Series()
    print(s)

```

### Describe the problem

Related code will raise an exception with that traceback:
```
Traceback (most recent call last):
  File "t2.py", line 5, in <module>
    print(s)
  File "C:\Users\dchigare\Desktop\REPOS\modin\modin\pandas\base.py", line 3471, in __str__
    return repr(self)
  File "C:\Users\dchigare\Desktop\REPOS\modin\modin\pandas\series.py", line 298, in __repr__
    temp_df = temp_df.iloc[:, 0]
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pandas\core\indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pandas\core\indexing.py", line 2067, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pandas\core\indexing.py", line 703, in _has_valid_tuple
    self._validate_key(k, i)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pandas\core\indexing.py", line 1994, in _validate_key
    self._validate_integer(key, axis)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pandas\core\indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by itamarst** [comment]
Will try to fix this.

**Comment by itamarst** [comment]
This was not caught because the `test_data` data for parameterized tests doesn't include an empty value.
