### ISSUE TITLE
Add modin-on-omnisci mode in omniscripts

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1736]
We want to add possibility to run tests in modin-on-omnisci mode in omniscripts to establish regular testing and get results in Grafana

**Comment by Garra1980** [comment]
Initial implementation:
in Omnisci:
https://github.com/intel-go/omniscidb/pull/53
in Omniscripts:
so far in branch https://github.com/intel-go/omniscripts/tree/modin_changes

WE also should think about enabling python3.8 in omniscripts

**Comment by Garra1980** [comment]
This is high priority now - we are enabling h2o, taxi and mortgage, bunch of bugs were fixed already, mostly we are struggling with type conversions between arrow and pandas.

**Comment by Garra1980** [comment]
To start using omniscripts with Modin&Omnisci:

- build omnisci with DBE enabled as mentioned here:
    https://github.com/modin-project/modin/issues/1652#issuecomment-655934599
- omniscripts master branch as usual with option -pandas_mode Modin_on_omnisci and -executable with argument that points on omnisci_server built in a step above

**Comment by amyskov** [comment]
In order to run benchmarks in Modin_on_omnisci mode it is needed to create conda environment first by running the next command
`python run_ibis_tests.py -executable /path/to/omnisci/executables -task build --env_name env_name --env_check True --save_env True --modin_path /path/to/modin`
in order to create environment to run mortgage benchmark ibis path should be also provided by adding flag
`-i /path/to/ibis/`
Note, that for `-executable` flag path should be provided with  executables in built directory (for example `.../omniscidb/build/bin/omnisci_server`)
Command to run benchmark
`python run_ibis_benchmark.py -bench_name bench_name -data_file /path/to/data -pandas_mode Modin_on_omnisci -no_ibis true`
To run Mortgage benchmark additional flag should be added `-no_ml true`

**Comment by amyskov** [comment]
Reported to MySQL database results can be found on the Grafana server in the Modin directory in `ETL execution times vs date-time for NYC taxi and Mortgage benchmarks` and `[h2o 5 GB dataset] queries execution times vs date for H2O benchmark` dashboards. Grafana server URL can be found in the Jira ticket 217.

**Comment by Garra1980** [comment]
Need to re-check this with latest Modin

**Comment by anmyachev** [comment]
fix taxi launch - https://github.com/intel-ai/omniscripts/pull/148

**Comment by anmyachev** [comment]
census:
`python run_ibis_tests.py -executable /localdisk/amyachev/omniscidb/build/bin/omnisci_server -task build,benchmark --env_name test-env-new --env_check True --save_env True --modin_path /localdisk/amyachev/modin/ -data_file '/localdisk/amyskov/benchmark_datasets/census/ipums_education2income_1970-2010.csv' -dfiles_num 1 -bench_name census  -no_ibis true -pandas_mode Modin_on_omnisci -no_ml true`

**Comment by amyskov** [comment]
Some corrections are performed in omniscripts and now results are properly reported for most of the benchmarks. Also dashboards for Census benchmark are added to the `ETL execution times vs date-time for NYC taxi, Mortgage and Census benchmarks` tables.
Next steps: prepare rest of dashboards for H2O benchmark, support `modin-on-omnisci` mode for python3.8 in omniscripts.

**Comment by Garra1980** [comment]
Mortgage seems to be broken:
``` Traceback (most recent call last):
  File "run_ibis_benchmark.py", line 425, in main
    benchmark_results = run_benchmark(parameters)
  File "/localdisk/izamyati/omniscripts/mortgage/mortgage_runner.py", line 231, in run_benchmark
    df_pd, mb_pd, etl_times_pd = _etl_pandas(parameters, acq_schema, perf_schema, etl_keys)
  File "/localdisk/izamyati/omniscripts/mortgage/mortgage_runner.py", line 49, in _etl_pandas
    pandas_mode=parameters["pandas_mode"],
  File "/localdisk/izamyati/omniscripts/mortgage/mortgage_pandas.py", line 474, in etl_pandas
    pd_dfs.append(mb.run_cpu_workflow(quarter=quarter, year=year, perf_file=fname))
  File "/localdisk/izamyati/omniscripts/mortgage/mortgage_pandas.py", line 78, in run_cpu_workflow
    names = self.pd_load_names()
  File "/localdisk/izamyati/omniscripts/mortgage/mortgage_pandas.py", line 150, in pd_load_names
    df = pd.read_csv(self.col_names_path, names=cols, delimiter="|")
  File "/localdisk/izamyati/miniconda3/envs/test-env/lib/python3.7/site-packages/modin-0.8.1+15.g333e2a0.dirty-py3.7.egg/modin/pandas/io.py", line 112, in parser_func
    return _read(**kwargs)
  File "/localdisk/izamyati/miniconda3/envs/test-env/lib/python3.7/site-packages/modin-0.8.1+15.g333e2a0.dirty-py3.7.egg/modin/pandas/io.py", line 127, in _read
    pd_obj = EngineDispatcher.read_csv(**kwargs)
  File "/localdisk/izamyati/miniconda3/envs/test-env/lib/python3.7/site-packages/modin-0.8.1+15.g333e2a0.dirty-py3.7.egg/modin/data_management/dispatcher.py", line 115, in read_csv
    return cls.__engine._read_csv(**kwargs)
  File "/localdisk/izamyati/miniconda3/envs/test-env/lib/python3.7/site-packages/modin-0.8.1+15.g333e2a0.dirty-py3.7.egg/modin/data_management/factories.py", line 56, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/localdisk/izamyati/miniconda3/envs/test-env/lib/python3.7/site-packages/modin-0.8.1+15.g333e2a0.dirty-py3.7.egg/modin/experimental/engines/omnisci_on_ray/io.py", line 198, in read_csv
    convert_options=co,
  File "pyarrow/_csv.pyx", line 583, in pyarrow._csv.read_csv
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 84, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: CSV parse error: Expected 2 columns, got 1
```

Also we need to get rid of ibis dependency for mortgage

**Comment by Garra1980** [comment]
For more precise time measurements in case of modin-on-omnisci we need to initialize calcite connection by running smth like
```    data = {"a" : [1, 2, 3]}
    df = pd.DataFrame(data);
    df = df + 1
    print(df)
```

prior a workload itself.

Also all tests have to be tested with MODIN_USE_CALCITE=True in environment

**Comment by ienkovich** [comment]
We can avoid print by doing smth like `_ = df.index`

**Comment by Garra1980** [comment]
Right, thanks, I should have changed that

**Comment by Garra1980** [comment]
https://github.com/intel-ai/modin/blob/omnisci-on-ray/modin/experimental/engines/omnisci_on_ray/io.py#L167 might be a problem since now delimiter does not set up correctly as far as I can see

**Comment by Garra1980** [comment]
We have Mortgage left which is not top priority now
