### ISSUE TITLE
Compare inexact tables obtained using different read_csv engines

### ISSUE THREAD

**Issue by anton-malakhov** [modin-project/modin#1739]
### Describe the problem
cannot compare floats while reading the same csv file using pandas and pyarrow (built into modin, but can be reproduced without one)

### Source code / logs
```
$ python t_simple3.py
t_simple3.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import (
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*- {'skiprows': 1, 'names': ['index', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE'], 'dtype': {'index': 'int64', 'CRIM': 'float64', 'ZN': 'float64', 'INDUS': 'float64', 'CHAS': 'float64', 'NOX': 'float64', 'RM': 'float64', 'AGE': 'float64', 'DIS': 'float64', 'RAD': 'float64', 'TAX': 'float64', 'PTRATIO': 'float64', 'B': 'float64', 'LSTAT': 'float64', 'PRICE': 'float64'}} *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-
Traceback (most recent call last):
  File "t_simple3.py", line 114, in <module>
    assert_almost_equal(r3, r2,
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/_testing.py", line 333, in assert_almost_equal
    assert_frame_equal(
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/_testing.py", line 1372, in assert_frame_equal
    assert_series_equal(
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/_testing.py", line 1166, in assert_series_equal
    assert_numpy_array_equal(
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/_testing.py", line 988, in assert_numpy_array_equal
    _raise(left, right, err_msg)
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/_testing.py", line 982, in _raise
    raise_assert_detail(obj, msg, left, right)
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/_testing.py", line 915, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: numpy array are different

numpy array values are different (22.13439 %)
[left]:  [0.00632, 0.02731, 0.02729, 0.03237, 0.06905, 0.02985, 0.08829, 0.14455, 0.21124, 0.17004, 0.22489, 0.11747, 0.09378, 0.62976, 0.63796, 0.62739, 1.05393, 0.7842, 0.80271, 0.7258, 1.25179, 0.85204, 1.23247, 0.98843, 0.75026, 0.84054, 0.67191, 0.95577, 0.77299, 1.00245, 1.13081, 1.35472, 1.38799, 1.15172, 1.61282, 0.06417, 0.09744, 0.08014, 0.17505, 0.02763, 0.03359, 0.12744, 0.1415, 0.15936, 0.12269, 0.17142, 0.18836, 0.22927, 0.25387, 0.21977, 0.08873, 0.04337, 0.0536, 0.04981, 0.0136, 0.01311, 0.02055, 0.01432, 0.15445, 0.10328, 0.14932, 0.17171, 0.11027, 0.1265, 0.01951, 0.03584, 0.04379, 0.05789, 0.13554, 0.12816, 0.08826, 0.15876, 0.09164, 0.19539, 0.07896, 0.09512, 0.10153, 0.08707, 0.05646, 0.08387, 0.04113, 0.04462, 0.03659, 0.03551, 0.05059, 0.05735, 0.05188, 0.07151, 0.0566, 0.05302, 0.04684, 0.03932, 0.04203, 0.02875, 0.04294, 0.12204, 0.11504, 0.12083, 0.08187, 0.0686, ...]
[right]: [0.00632, 0.02731, 0.02729, 0.032369999999999996, 0.06905, 0.02985, 0.08829, 0.14455, 0.21124, 0.17004, 0.22489, 0.11747, 0.09378, 0.62976, 0.6379600000000001, 0.62739, 1.05393, 0.7842, 0.80271, 0.7258, 1.25179, 0.8520399999999999, 1.2324700000000002, 0.9884299999999999, 0.75026, 0.84054, 0.67191, 0.9557700000000001, 0.77299, 1.00245, 1.13081, 1.3547200000000001, 1.38799, 1.15172, 1.6128200000000001, 0.06417, 0.09744, 0.08014, 0.17505, 0.027630000000000002, 0.033589999999999995, 0.12744, 0.1415, 0.15936, 0.12269000000000001, 0.17142000000000002, 0.18836, 0.22926999999999997, 0.25387, 0.21977, 0.08872999999999999, 0.04337, 0.0536, 0.04981, 0.0136, 0.01311, 0.02055, 0.01432, 0.15445, 0.10328, 0.14932, 0.17171, 0.11027, 0.1265, 0.01951, 0.03584, 0.043789999999999996, 0.05789, 0.13554000000000002, 0.12816, 0.08826, 0.15875999999999998, 0.09164, 0.19539, 0.07896, 0.09512000000000001, 0.10153, 0.08707000000000001, 0.05646, 0.08387, 0.04113, 0.04462, 0.03659, 0.03551, 0.050589999999999996, 0.05735, 0.051879999999999996, 0.07151, 0.0566, 0.053020000000000005, 0.04684, 0.03932, 0.04203, 0.02875, 0.04294, 0.12204000000000001, 0.11504, 0.12082999999999999, 0.08187, 0.0686, ...]

```

Running this script:
```
import os
import sys;
import pandas as pd
import numpy as np
import pyarrow as pa
from pyarrow.csv import read_csv, ParseOptions, ConvertOptions, ReadOptions


# os.environ["MODIN_BACKEND"] = "Omnisci"
# os.environ["MODIN_ENGINE"] = "Ray"
# sys.setdlopenflags( 1|256 )    # RTLD_LAZY+RTLD_GLOBAL
# import modin.experimental.pandas as mpd
# import modin.pandas.test

from pandas.util.testing import (
    assert_almost_equal,
    assert_frame_equal,
    assert_categorical_equal,
)

def read_arrow_csv(
        filepath_or_buffer,
        sep=",",
        delimiter=None,
        header="infer",
        names=None,
        index_col=None,
        usecols=None,
        squeeze=False,
        prefix=None,
        mangle_dupe_cols=True,
        dtype=None,
        engine=None,
        converters=None,
        true_values=None,
        false_values=None,
        skipinitialspace=False,
        skiprows=None,
        nrows=None,
        na_values=None,
        keep_default_na=True,
        na_filter=True,
        verbose=False,
        skip_blank_lines=True,
        parse_dates=False,
        infer_datetime_format=False,
        keep_date_col=False,
        date_parser=None,
        dayfirst=False,
        cache_dates=True,
        iterator=False,
        chunksize=None,
        compression="infer",
        thousands=None,
        decimal=b".",
        lineterminator=None,
        quotechar='"',
        quoting=0,
        escapechar=None,
        comment=None,
        encoding=None,
        dialect=None,
        error_bad_lines=True,
        warn_bad_lines=True,
        skipfooter=0,
        doublequote=True,
        delim_whitespace=False,
        low_memory=True,
        memory_map=False,
        float_precision=None,
    ):
    co = ConvertOptions(
        check_utf8=None, 
        column_types=None, 
        null_values=None,
        true_values=None, 
        false_values=None, 
        strings_can_be_null=None, 
        include_columns=None, 
        include_missing_columns=None, 
        auto_dict_encode=None, 
        auto_dict_max_cardinality=None)

    ro = ReadOptions(
        use_threads=True,
        block_size=None,
        skip_rows=skiprows,
        column_names=names,
        autogenerate_column_names=True)
            
    po = ParseOptions(
        delimiter = sep if sep else '\s+' if delim_whitespace else delimiter,
        quote_char=quotechar,
        double_quote=doublequote, 
        escape_char=escapechar,
        newlines_in_values=False,
        ignore_empty_lines=skip_blank_lines)

    df = pa.csv.read_csv(filepath_or_buffer, read_options=ro, parse_options=po, convert_options=co).to_pandas()
    return df

csv_file = "/users/amalakho/projects/modin/examples/data/boston_housing.csv"
for kwargs in (
    #{"sep": ','}, {"sep": None},
    {"skiprows": 1, "names": ["index","CRIM","ZN","INDUS","CHAS","NOX","RM","AGE","DIS","RAD","TAX","PTRATIO","B","LSTAT","PRICE",],
        "dtype": {'index':'int64', "CRIM":'float64', "ZN":'float64', 'INDUS':'float64', 'CHAS':'float64', 'NOX':'float64', 'RM':'float64',
        'AGE':'float64', 'DIS':'float64', 'RAD':'float64', 'TAX':'float64', 'PTRATIO':'float64', 'B':'float64', 'LSTAT':'float64', 'PRICE':'float64'}
    },
    ):
        print('*-'*15, kwargs, '*-'*15)
        # r1 = mpd.read_csv(csv_file, **kwargs)
        r2 = pd.read_csv(csv_file, **kwargs)
        r3 = read_arrow_csv(csv_file, **kwargs)
        assert_almost_equal(r3, r2,
                #check_dtype=True,
                check_datetimelike_compat=True,
                check_index_type=False,
                check_column_type=True,
                check_categorical=False,
                #check_exact=False,
                check_less_precise=2,
                )
        print('=='*15, '\n', r2, '--'*15, '\n', r3, '=='*15)
```

**Comment by devin-petersohn** [comment]
We can add a parameter to `df_equals` to ignore data type and check that values are close.
