### ISSUE TITLE
Empty column doesn't work even with explicit dtypes assignment

### ISSUE THREAD

**Issue by Garra1980** [modin-project/modin#1745]
For following csv 
```
1,2,
2,2,
3,2,
4,2,
5,2,
```

the test that looks like 
```
import os
os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd


df = pd.read_csv("null_column.csv", dtype=["int", "int", "int"])
print(df)
```
gives now
terminate called after throwing an instance of 'std::runtime_error'
  what():  null is not yet supported

We need to understand a root cause - either dtype argument is bad (doesn't work in omnisci-modin or specified incorrectly) or problem is in import

**Comment by anton-malakhov** [comment]
Seems like this form of dtype argument is not supported even by pandas itself:
```
>>> rp = pd.read_csv(csv_file, dtype=['int', 'int', 'int', 'int', 'int'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 480, in pandas._libs.parsers.TextReader.__cinit__
  File "/users/amalakho/local/miniconda3/envs/o-modin/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1874, in pandas_dtype
    npdtype = np.dtype(dtype)
TypeError: data type not understood
>>> 
```

**Comment by Garra1980** [comment]
That’s fine, feel free to rewrite the test

**Comment by anton-malakhov** [comment]
generally, pandas says:
> dtypeType name or dict of column -> type, optional
> Data type for data or columns. E.g. {‘a’: np.float64, ‘b’: np.int32, ‘c’: ‘Int64’} Use str or object together with suitable na_values settings to preserve and not interpret dtype. If converters are specified, they will be applied INSTEAD of dtype conversion.

So, either dict or one type for all

**Comment by anton-malakhov** [comment]
working pandas:
```
>>> rp = pd.read_csv(csv_file, names=['a1','b2','c3'], dtype='float64')
>>> rp
    a1   b2  c3
0  1.0  2.0 NaN
1  2.0  2.0 NaN
2  3.0  2.0 NaN
3  4.0  2.0 NaN
4  5.0  2.0 NaN
>>> 
```
