### ISSUE TITLE
Test TestDataFrameDefault::test_boxplot fails with matplotlib 3.3.0

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1747]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.4+57.g6ca8016

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

With new release test `TestDataFrameDefault::test_boxplot` produce exception:
```
Traceback (most recent call last):
  File "/localdisk/gashiman/modin/modin/pandas/test/test_dataframe.py", line 2108, in test_boxplot
    assert modin_df.boxplot() == to_pandas(modin_df).boxplot()
  File "/localdisk/gashiman/modin/modin/pandas/dataframe.py", line 589, in boxplot
    return to_pandas(self).boxplot(
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/plotting/_core.py", line 436, in boxplot_frame
    return plot_backend.boxplot_frame(
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py", line 364, in boxplot_frame
    ax = boxplot(
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py", line 343, in boxplot
    result = plot_group(columns, data.values.T, ax)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/pandas/plotting/_matplotlib/boxplot.py", line 291, in plot_group
    ax.set_xticklabels(keys, rotation=rot)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 63, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1793, in _set_ticklabels
    return self.set_ticklabels(labels, minor=minor, **kwargs)
  File "/nfs/site/home/gashiman/.local/lib/python3.8/site-packages/matplotlib/axis.py", line 1714, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (420), usually from a call to set_ticks, does not match the number of ticklabels (100).
```

**Comment by gshimansky** [comment]
I want this issue to be open to fix the problem with new version of matplotlib

**Comment by gshimansky** [comment]
Ok this doesn't look like a problem in modin. Tests fail in pure pandas code and other bugs like this start to appear on the internet: https://stackoverflow.com/questions/62953704/valueerror-the-number-of-fixedlocator-locations-5-usually-from-a-call-to-set

**Comment by stonebig** [comment]
can you relax again to any version of matplotlib ?
