### ISSUE TITLE
merge throws exception on MODIN_ENGINE=python

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#1771]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.4+66.g37b7d2c

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
if __name__ == "__main__":
    import modin.pandas as pd

    df1 = pd.read_csv("x.csv")
    df2 = pd.DataFrame({"name": [39], "position": [0]})
    df3 = df1.merge(df2, on='name', how='inner')
    print(df3)
```

### Describe the problem

When running with `MODIN_ENGINE=python` this test throws exception
```
Traceback (most recent call last):
  File "merge_test.py", line 6, in <module>
    df3 = df1.merge(df2, on='name', how='inner')
  File "/localdisk/gashiman/modin/modin/pandas/dataframe.py", line 1540, in merge
    return result.reset_index(drop=True) if is_reset_index else result
  File "/localdisk/gashiman/modin/modin/pandas/base.py", line 2301, in reset_index
    new_query_compiler = self._query_compiler.reset_index(
  File "/localdisk/gashiman/modin/modin/backends/pandas/query_compiler.py", line 442, in reset_index
    new_self = self.copy()
  File "/localdisk/gashiman/modin/modin/backends/pandas/query_compiler.py", line 217, in copy
    return self.__constructor__(self._modin_frame.copy())
  File "/localdisk/gashiman/modin/modin/engines/base/frame/data.py", line 532, in copy
    return self.__constructor__(
  File "/localdisk/gashiman/modin/modin/engines/base/frame/data.py", line 68, in __init__
    ErrorMessage.catch_bugs_and_request_email(
  File "/localdisk/gashiman/modin/modin/error_message.py", line 50, in catch_bugs_and_request_email
    raise Exception(
Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Column widths: 0 != 23
```
Test passes on Ray and Dask. It also passes when dataframe is small, so it looks like it depends on it being partitioned. Bisecting shows that this is a regression caused by commit 8b46126d6e18d81fb4c643734e26f6849913abdc. @YarShev can you please take a look? Attached is CSV file with dataframe contents.
[dataframe.zip](https://github.com/modin-project/modin/files/4963051/dataframe.zip)

**Comment by YarShev** [comment]
Yes, It is related to incorrect computing of `row_lengths` and `column_widths` when `MODIN_ENGINE=python` is set. It will be fixed with #1764 .
