### ISSUE TITLE
RuntimeError: Unable to connect to Redis. 

### ISSUE THREAD

**Issue by reporter-law** [modin-project/modin#1777]
error:
Traceback (most recent call last):
  File "J:/PyCharm项目/package_test_/modin测试/modin测试.py", line 7, in <module>
    from modin.pandas import pandas as pd
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\modin\pandas\__init__.py", line 280, in <module>
    execution_engine.subscribe(_update_engine)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\modin\__init__.py", line 93, in subscribe
    callback(self)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\modin\pandas\__init__.py", line 253, in _update_engine
    initialize_ray()
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\modin\pandas\__init__.py", line 199, in initialize_ray
    lru_evict=True,
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\worker.py", line 723, in init
    ray_params=ray_params)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\node.py", line 180, in __init__
    self.start_head_processes()
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\node.py", line 681, in start_head_processes
    self.start_redis()
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\node.py", line 502, in start_redis
    fate_share=self.kernel_fate_share)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\services.py", line 763, in start_redis
    fate_share=fate_share)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\services.py", line 957, in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
  File "D:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\ray\services.py", line 562, in wait_for_redis_to_start
    raise RuntimeError("Unable to connect to Redis. If the Redis instance "
RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.

**Comment by devin-petersohn** [comment]
Hi @reporter-law, thanks for the report!

This is an issue with initializing Ray, there is a similar issue on the Ray repo found here: https://github.com/ray-project/ray/issues/4931.

**Comment by jeongsoolee09** [comment]
I am currently running into the same issue. I'd like to switch to modin with dask for the moment, how can I make the switch?

**Comment by EUCIAN** [comment]
I am also running into the same issue. I'm running on Windows 10, and specifying that modin should be running dask as the MODIN_ENGINE. I would expect this issue to be avoided by using dask.
(Python 3.8.2)

I have included several examples of what I've tried here:
Example 1:
>>>import os
>>> os.environ["MODIN_ENGINE"] = "dask"  # Modin will use Dask
>>> import modin.pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\pandas\__init__.py", line 182, in <module>
    execution_engine.subscribe(_update_engine)
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\__init__.py", line 93, in subscribe
    callback(self)
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\pandas\__init__.py", line 118, in _update_engine
    initialize_ray()
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\engines\ray\utils.py", line 139, in initialize_ray
    ray.init(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\worker.py", line 696, in init
    _global_node = ray.node.Node(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\node.py", line 198, in __init__
    self.start_head_processes()
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\node.py", line 800, in start_head_processes
    self.start_redis()
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\node.py", line 568, in start_redis
    process_infos) = ray.services.start_redis(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\services.py", line 739, in start_redis
    port, p = _start_redis_instance(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\services.py", line 937, in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\services.py", line 552, in wait_for_redis_to_start
    raise RuntimeError("Unable to connect to Redis. If the Redis instance "
RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.


Example 2:
>>> from distributed import Client
>>> client=Client(n_workers=8)
>>> import modin.pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\pandas\__init__.py", line 182, in <module>
    execution_engine.subscribe(_update_engine)
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\__init__.py", line 93, in subscribe
    callback(self)
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\pandas\__init__.py", line 118, in _update_engine
    initialize_ray()
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\modin\engines\ray\utils.py", line 139, in initialize_ray
    ray.init(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\worker.py", line 696, in init
    _global_node = ray.node.Node(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\node.py", line 198, in __init__
    self.start_head_processes()
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\node.py", line 800, in start_head_processes
    self.start_redis()
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\node.py", line 568, in start_redis
    process_infos) = ray.services.start_redis(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\services.py", line 739, in start_redis
    port, p = _start_redis_instance(
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\services.py", line 937, in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
  File "C:\Users\Ian\.conda\envs\pytrade\lib\site-packages\ray\services.py", line 552, in wait_for_redis_to_start
    raise RuntimeError("Unable to connect to Redis. If the Redis instance "
RuntimeError: Unable to connect to Redis. If the Redis instance is on a different machine, check that your firewall is configured properly.

**Comment by devin-petersohn** [comment]
Sorry this got dropped, looking over past issues I found this.

We have some updated approach of handling the engine updates in #2580. It should not still cause this problem. Are you able to check? You will need to install from github master: https://modin.readthedocs.io/en/latest/installation.html#installing-from-the-github-master-branch

**Comment by bhavyalatha26** [comment]
@devin-petersohn I too ran into the same issue using stable version installed with `pip install modin[ray]`. Later as suggested in above comment I installed modin from the **master** branch and followed by installation of **ray**. But still run into the same issue.

> I am using modin inside a python script, not notebook

**Installed packages:**

* python 3.7.1
* modin  0.8.3+31.g77d40ce
* ray 1.1.0
* redis 3.5.3

Please find below the complete error stack trace
<details>
<summary>Error Stacktrace</summary>
<p>

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\process.py", line 191, in _process_chunk
    return [fn(*args) for args in chunk]
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\process.py", line 191, in <listcomp>
    return [fn(*args) for args in chunk]
  File "F:\DENALI\denali\scripts\market_analyzer.py", line 605, in _helper
    prev_output_dict=analyzer_input[8])
  File "F:\DENALI\denali\scripts\market_analyzer.py", line 1493, in analyze
    return mpd.DataFrame()
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\modin\pandas\dataframe.py", line 90, in __init__
    Engine.subscribe(_update_engine)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\modin\config\pubsub.py", line 107, in subscribe
    callback(cls)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\modin\pandas\__init__.py", line 114, in _update_engine
    initialize_ray()
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\modin\engines\ray\utils.py", line 159, in initialize_ray
    _lru_evict=True,
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\worker.py", line 722, in init
    ray_params=ray_params)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\node.py", line 216, in __init__
    self.start_head_processes()
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\node.py", line 767, in start_head_processes
    self.start_redis()
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\node.py", line 597, in start_redis
    fate_share=self.kernel_fate_share)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\_private\services.py", line 843, in start_redis
    fate_share=fate_share)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\_private\services.py", line 989, in _start_redis_instance
    wait_for_redis_to_start("127.0.0.1", port, password=password)
  File "D:\ProgramData\Anaconda3\envs\denali\lib\site-packages\ray\_private\services.py", line 651, in wait_for_redis_to_start
    redis_ip_address, redis_port)) from authEx
RuntimeError: Unable to connect to Redis at 127.0.0.1:6379.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\scripts\market_analyzer.py", line 1607, in start
    current_prices_dict=current_prices_json
  File ".\scripts\market_analyzer.py", line 620, in execute
    run_df_list = list(pool.map(self._helper, params))
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\process.py", line 476, in _chain_from_iterable_of_lists
    for element in iterable:
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\ProgramData\Anaconda3\envs\denali\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: Unable to connect to Redis at 127.0.0.1:6379.
```

</p>
</details>  

**Additional Details :**
* OS : Windows 10 

> I tried using `dask` engine for windows as recommended but run into a different issue as reported [here](https://github.com/modin-project/modin/issues/843), so I tried to use `ray` engine

Also I would like to know is modin suitable for use in standalone scripts or python modules ?

**Comment by devin-petersohn** [comment]
@bhavyalatha26 Thanks for the update!

Can you tell me if this works for you on windows?:

```python
import ray
ray.init()
```

Windows support for Ray is still fairly new, so any help we can give the Ray team will be great!

**Comment by devin-petersohn** [comment]
>Also I would like to know is modin suitable for use in standalone scripts or python modules ?

Yes, it is. This comment in the issue you show is how to do that with Dask: https://github.com/modin-project/modin/issues/843#issuecomment-761625592

Unfortunately, this is a property of Dask that cannot be worked around because of how it spawns new workers. Ray does not use the same mechanism for spawning new processes, so it does not have the same requirements.

**Comment by gshimansky** [comment]
There is another Ray on Windows bug with similar symptoms https://github.com/ray-project/ray/issues/13213

**Comment by aregm** [comment]
@gshimansky Can you please recheck quickly?

**Comment by gshimansky** [comment]
I checked windows version on current master branch (commit f9c99c3817d35f7bf0d91df9aa9644545ea27517) with Ray 1.4.0 now installed from pip. Statement `from modin import pandas as pd` no longer triggers Ray initialization but I made sure that Ray is initialized by creating a modin Series object and Ray initialization works fine.

I think we can close this issue.
