### ISSUE TITLE
read_excel fails when engine is set to openpyxl

### ISSUE THREAD

**Issue by deathsaber** [modin-project/modin#1921]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL 7.8
- **Modin version** (`modin.__version__`): 0.8.0
- **Python version**: 3.8.0
- **Code we can use to reproduce**:
import modin.pandas as pd
data = pd.read_excel("CREATE_SLT_WITHOUT_ERROR.xlsx", engine="openpyxl")

### Describe the problem
When I try reading any excel sheet with multiple sheets, it fails with KeyError: "There is no item named 'xl/worksheets/info.xml' in the archive"
It works fine when the excel has just one sheet but it fails when the excel has multiple sheets.
### Source code / logs
The error stacktrace look like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/modin/pandas/io.py", line 255, in read_excel
    intermediate = EngineDispatcher.read_excel(**kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/modin/data_management/dispatcher.py", line 131, in read_excel
    return cls.__engine._read_excel(**kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/modin/data_management/factories.py", line 72, in _read_excel
    return cls.io_cls.read_excel(**kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/modin/engines/base/io/file_reader.py", line 29, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/modin/engines/base/io/text/excel_reader.py", line 74, in _read
    f = z.open("xl/worksheets/{}.xml".format(sheet_name.lower()))
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/zipfile.py", line 1479, in open
    zinfo = self.getinfo(name)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/zipfile.py", line 1406, in getinfo
    raise KeyError(
KeyError: "There is no item named 'xl/worksheets/info.xml' in the archive"

The file attached can be used to re-create the scenario:
[CREATE_SLT_WITHOUT_ERROR.xlsx](https://github.com/modin-project/modin/files/5069052/CREATE_SLT_WITHOUT_ERROR.xlsx)

**Comment by hoveybr** [comment]
I have the exact same issue, haven't been able to open any Excel files with modin. Had to flip back to pandas with multiprocessing

**Comment by devin-petersohn** [comment]
Thanks @deathsaber and @hoveybr for the report and reproducible file. I can reproduce the issue.

I will make sure we get this resolved. Thanks again!

**Comment by Greybeetle** [comment]
I also met this problem. Is there any solution at present

**Comment by devin-petersohn** [comment]
This has been resolved and will be in the next release (later this week)
