### ISSUE TITLE
Binary operations when 'right' is a 'list' broken in 'Series'

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1969]
### System information
- **OmniSci branch**: [intel-go/omniscidb/gal/fix_pytests](https://github.com/intel-go/omniscidb/tree/gal/fix_pytests)
- **Modin branch**: [intel-go/modin/omnisci-on-ray](https://github.com/intel-go/modin/tree/omnisci-on-ray)
- **Code we can use to reproduce**:
```python
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"

if __name__ == "__main__":
    import modin.pandas as pd
    import pandas

    data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

    md_df = pd.DataFrame(data)
    pd_df = pandas.DataFrame(data)

    print("pd_df result:\n", pd_df + [1, 2, 3, 4, 5], sep="")
    print("md_df result:\n", md_df + [1, 2, 3, 4, 5], sep="") # Works correct

    md_series = pd.Series(data[0])
    pd_series = pandas.Series(data[0])

    print("\n\npd result:\n", pd_series + [1, 2, 3, 4, 5], sep="")
    print("md result:\n", md_series + [1, 2, 3, 4, 5], sep="") # ValueError

```

<details><summary>Output</summary>

```
pd_df result:
   0  1   2   3   4
0  2  4   6   8  10
1  7  9  11  13  15
md_df result:
   0  1   2   3   4
0  2  4   6   8  10
1  7  9  11  13  15

pd result:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Traceback (most recent call last):
  File "../TESTS/new_what.py", line 23, in <module>
    print("md result:\n", md_series + [1, 2, 3, 4, 5], sep="") # ValueError
  File "/localdisk/dchigare/repos/modin/modin/pandas/series.py", line 169, in __add__
    return self.add(right)
  File "/localdisk/dchigare/repos/modin/modin/pandas/series.py", line 374, in add
    return super(Series, new_self).add(
  File "/localdisk/dchigare/repos/modin/modin/pandas/base.py", line 362, in add
    return self._binary_op(
  File "/localdisk/dchigare/repos/modin/modin/pandas/base.py", line 237, in _binary_op
    new_query_compiler = getattr(self._query_compiler, op)(other, **kwargs)
  File "/localdisk/dchigare/repos/modin/modin/experimental/backends/omnisci/query_compiler.py", line 326, in add
    return self._bin_op(other, "add", **kwargs)
  File "/localdisk/dchigare/repos/modin/modin/experimental/backends/omnisci/query_compiler.py", line 322, in _bin_op
    new_modin_frame = self._modin_frame.bin_op(other, op_name, **kwargs)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 570, in bin_op
    raise ValueError(
ValueError: length must be 1: given 5
```

</details>

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
