### ISSUE TITLE
Astype(str) raising KeyError

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#1970]
### System information
- **OmniSci branch**: [intel-go/omniscidb/gal/fix_pytests](https://github.com/intel-go/omniscidb/tree/gal/fix_pytests)
- **Modin branch**: [intel-go/modin/omnisci-on-ray](https://github.com/intel-go/modin/tree/omnisci-on-ray)
- **Code we can use to reproduce**:
```python
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_ENGINE"] = "ray"
os.environ["MODIN_BACKEND"] = "omnisci"

if __name__ == "__main__":
    import modin.pandas as pd
    import pandas

    data = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

    md_df = pd.DataFrame(data)
    pd_df = pandas.DataFrame(data)

    print("pd_df_result:\n", pd_df.astype(str), sep="")
    print("md_df_result:\n", md_df.astype(str), sep="") # KeyError

```

<details><summary>Output</summary>

```
pd_df_result:
   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10
md_df_result:
Traceback (most recent call last):
  File "../TESTS/new_what.py", line 17, in <module>
    print("md_df_result:\n", md_df.astype(str), sep="") # KeyError
  File "/localdisk/dchigare/repos/modin/modin/pandas/base.py", line 3531, in __str__
    return repr(self)
  File "/localdisk/dchigare/repos/modin/modin/pandas/dataframe.py", line 165, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/localdisk/dchigare/repos/modin/modin/pandas/base.py", line 66, in _build_repr_df
    if len(self.index) == 0 or (
  File "/localdisk/dchigare/repos/modin/modin/pandas/base.py", line 3593, in __getattribute__
    return object.__getattribute__(self, item)
  File "/localdisk/dchigare/repos/modin/modin/pandas/base.py", line 345, in _get_index
    return self._query_compiler.index
  File "/localdisk/dchigare/repos/modin/modin/experimental/backends/omnisci/query_compiler.py", line 219, in _get_index
    return self._modin_frame.index
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 941, in _get_index
    self._execute()
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 824, in _execute
    new_partitions = self._frame_mgr_cls.run_exec_plan(
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py", line 86, in run_exec_plan
    calcite_json = CalciteSerializer().serialize(calcite_plan)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 48, in serialize
    return json.dumps({"rels": [self.serialize_item(node) for node in plan]})
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 48, in <listcomp>
    return json.dumps({"rels": [self.serialize_item(node) for node in plan]})
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 58, in serialize_item
    return self.serialize_node(item)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 84, in serialize_node
    return self.serialize_obj(node)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 94, in serialize_obj
    res[k] = self.serialize_item(v)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 64, in serialize_item
    return [self.serialize_item(v) for v in item]
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 64, in <listcomp>
    return [self.serialize_item(v) for v in item]
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 60, in serialize_item
    return self.serialize_expr(item)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 110, in serialize_expr
    return self.serialize_typed_obj(expr)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 99, in serialize_typed_obj
    res["type"] = self.serialize_dtype(obj._dtype)
  File "/localdisk/dchigare/repos/modin/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.py", line 187, in serialize_dtype
    return {"type": type(self).dtype_strings[dtype.name], "nullable": True}
KeyError: 'str'
```

</details>

**Comment by Garra1980** [comment]
Unsupported casting type

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
