### ISSUE TITLE
read_csv with Ray engine fails with parse_dates parameter passed as dict

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2073]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.7.3+350.g2ca3f34
- **Python version**: 3.8.5
- **Code we can use to reproduce**:
```
import os
os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd

test_filename = "test.csv"
csv_single_col = """col1,col2
2000-01-01,2000-01-02
2000-01-03,2000-01-04
"""

try :
    with open(test_filename, "w") as f:
        f.write(csv_single_col)

    df_pandas = pandas.read_csv(test_filename, parse_dates={"foo": ["col1", "col2"]})
    print(df_pandas)
    df_pd = pd.read_csv(test_filename, parse_dates={"foo": ["col1", "col2"]})
    repr(df_pd)
    print(df_pd)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
                         foo
0  2000-01-01 20:00:00-02:00
1  2000-01-03 20:00:00-04:00
Traceback (most recent call last):
  File "test_read_csv.py", line 20, in <module>
    repr(df_pd)
  File "/localdisk/amyskov/modin2/modin/pandas/dataframe.py", line 169, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/localdisk/amyskov/modin2/modin/pandas/base.py", line 108, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()
  File "/localdisk/amyskov/modin2/modin/pandas/indexing.py", line 377, in __getitem__
    result = super(_iLocIndexer, self).__getitem__(row_lookup, col_lookup, ndim)
  File "/localdisk/amyskov/modin2/modin/pandas/indexing.py", line 129, in __getitem__
    qc_view = self.qc.view(row_lookup, col_lookup)
  File "/localdisk/amyskov/modin2/modin/backends/pandas/query_compiler.py", line 2470, in view
    self._modin_frame.mask(row_numeric_idx=index, col_numeric_idx=columns)
  File "/localdisk/amyskov/modin2/modin/engines/base/frame/data.py", line 472, in mask
    return self.copy()
  File "/localdisk/amyskov/modin2/modin/engines/base/frame/data.py", line 643, in copy
    return self.__constructor__(
  File "/localdisk/amyskov/modin2/modin/engines/base/frame/data.py", line 73, in __init__
    ErrorMessage.catch_bugs_and_request_email(
  File "/localdisk/amyskov/modin2/modin/error_message.py", line 51, in catch_bugs_and_request_email
    raise Exception(
Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Column widths: 2 != 1
```

**Comment by YarShev** [comment]
Reopening the issue because of [this](https://github.com/modin-project/modin/pull/2884#discussion_r596580755).

**Comment by mvashishtha** [comment]
This seems to work on Modin version d231df0fb13918b40827aa5fd61ac5516e7e9dac. We need to add a test case for it.

**Comment by pyrito** [comment]
@mvashishtha What's the status of this?

**Comment by mvashishtha** [comment]
I still have to address comments on #4572: https://github.com/modin-project/modin/pull/4572#issuecomment-1164656101
