### ISSUE TITLE
import Ray shared library failed

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2096]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Windows 10`
- **Modin version** (`modin.__version__`): `master`
- **Python version**: `3.7.6`
- **Ray version**: 0.8.7
- **Code we can use to reproduce**:
```sh
pip install "ray==0.8.7"
python -c "import ray"
```

### Source code / logs

```sh
>>> import ray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\AppData\Local\Continuum\miniconda3\envs\modin\lib\site-packages\ray\__init__.py", line 54, in <module>
    CDLL(so_path, ctypes.RTLD_GLOBAL)
  File "...AppData\Local\Continuum\miniconda3\envs\modin\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by anmyachev** [comment]
Problem with import `...\AppData\Local\Continuum\miniconda3\envs\modin\lib\site-packages\ray\_raylet.pyd`

**Comment by anmyachev** [comment]
There is one more library for `ray==0.8.7` in comparison with `ray==0.8.6` - `VCRUNTIME140_1.dll`

**Comment by anmyachev** [comment]
There is working solution: https://docs.ray.io/en/latest/installation.html#windows-dependencies

**Comment by anmyachev** [comment]
just update visual studio runtime
