### ISSUE TITLE
OmniSci read_csv does not fallback to Pandas when file is a URL

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#2099]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: probably irrelevant, observed on Ubuntu 18.05
- **Modin version** (`modin.__version__`): unreleased; observed on my fork at https://github.com/vnlitvinov/modin/tree/omnisci-on-cloud but I think it would surface on any OmniSci-enabled Modin
- **Python version**: 3.7.8
- **Code we can use to reproduce**:
```python
import os
os.environ['MODIN_ENGINE'] = 'Ray'
os.environ['MODIN_BACKEND'] = 'Omnisci'

import modin.experimental.pandas as pd

df = pd.read_csv('https://foo.org/file.csv')
```

### Describe the problem

Modin does not understand that the file is not local, here's the traceback:
```
Traceback (most recent call last):
  File "a.py", line 7, in <module>
    df = pd.read_csv('https://foo.org/file.csv')
  File "/src/modin/modin/pandas/io.py", line 112, in parser_func
    return _read(**kwargs)
  File "/src/modin/modin/pandas/io.py", line 127, in _read
    pd_obj = EngineDispatcher.read_csv(**kwargs)
  File "/src/modin/modin/data_management/dispatcher.py", line 115, in read_csv
    return cls.__engine._read_csv(**kwargs)
  File "/src/modin/modin/data_management/factories.py", line 87, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/src/modin/modin/experimental/engines/omnisci_on_ray/io.py", line 181, in read_csv
    convert_options=co,
  File "pyarrow/_csv.pyx", line 573, in pyarrow._csv.read_csv
  File "pyarrow/_csv.pyx", line 512, in pyarrow._csv._get_reader
  File "pyarrow/io.pxi", line 1432, in pyarrow.lib.get_input_stream
  File "pyarrow/io.pxi", line 1399, in pyarrow.lib._get_native_file
  File "pyarrow/io.pxi", line 828, in pyarrow.lib.OSFile.__cinit__
  File "pyarrow/io.pxi", line 838, in pyarrow.lib.OSFile._open_readable
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
FileNotFoundError: [Errno 2] Failed to open local file 'https://foo.org/file.csv'. Detail: [errno 2] No such file or directory
```

### Expected behaviour
For this particular code example expected behaviour would probably be failing to find a file (as URL given in the example is most likely invalid). I've observed the same issue with existing file, and expected behaviour there would be reading it, even if through falling back to Pandas.

**Comment by vnlitvinov** [comment]
cc @amyskov @ienkovich @dchigarev

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
