### ISSUE TITLE
Invalid argument: 'C:\\...\\PycharmProjects\\libraries\\<input>

### ISSUE THREAD

**Issue by hazeyblu** [modin-project/modin#2139]
### System information
- **OS Platform and Distribution** : Windows 10 Professional x64 Build 1909
- **Modin version** : 0.8.0
- **Python version** : 3.8.1
- **Code we can use to reproduce** : 

import os
os.environ["MODIN_ENGINE"] = "dask"
import modin.pandas as pd

### Describe the problem
I have installed Modin using pip install modin[dask] on my virtual environment after having uninstalled Modin and Ray recently (I had installed modin[ray] unaware of incompatibility with Windows environment)
Now when I try to import the module, it throws an infinite error with the traceback

I had to put space around **input**, else the HTML format rendered it invisible, the spaces are non-existent in execution

>> OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\PycharmProjects\\libraries\\ < input >

### Source code / logs
UserWarning: The Dask Engine for Modin is experimental.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 125, in _main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python38\lib\runpy.py", line 262, in run_path
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python38\lib\runpy.py", line 232, in _get_code_from_file
    prepare(preparation_data)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    with io.open_code(fname) as f:
    _fixup_main_from_path(data['init_main_from_path'])OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\PycharmProjects\\libraries\\<input>'
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python38\lib\runpy.py", line 262, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python38\lib\runpy.py", line 232, in _get_code_from_file
    with io.open_code(fname) as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\PycharmProjects\\libraries\\ < input > '
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python38\lib\runpy.py", line 262, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python38\lib\runpy.py", line 232, in _get_code_from_file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    with io.open_code(fname) as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\PycharmProjects\\libraries\\ < input > '
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 125, in _main
    main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python38\lib\runpy.py", line 262, in run_path
    prepare(preparation_data)
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 236, in prepare
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python38\lib\runpy.py", line 232, in _get_code_from_file
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python38\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
        main_content = runpy.run_path(main_path,
  File "C:\Program Files\Python38\lib\runpy.py", line 262, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Program Files\Python38\lib\runpy.py", line 232, in _get_code_from_file
    Traceback (most recent call last):
  File "<string>", line 1, in <module>
with io.open_code(fname) as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\user\\PycharmProjects\\libraries\\ < input > '

**Comment by devin-petersohn** [comment]
Hi @hazeyblu thanks for posting!

This appears to be related to #843 with Dask. Ray does have windows support now, though it is experimental. Would it be possible to try with Ray? Ray doesn't have the same multiprocessing error issue that Dask has.

**Comment by pyrito** [comment]
Hi @hazeyblu are you still facing this issue? I'm going to go ahead and close this issue since the thread has gone stale.
