### ISSUE TITLE
read_csv with ray engine ints inside columns with object dtypes not set correctly

### ISSUE THREAD

**Issue by kvu35** [modin-project/modin#2247]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
`Arch Linux`
- **Modin version** (`modin.__version__`):
`0.8.1.1+12.gaa3d7fc.dirty`
- **Python version**:
`Python 3.6.11`
- **Code we can use to reproduce**:
```
import os
os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals

test_filename = "test.csv"
csv_single_col = \
"""
one,2, three, five, six, seven, eight
three,4, five, six, seven, eight, nine
one,2, three, five, six, seven, eight
one,two, three, five, six, seven, eight
one,two, three, five, six, seven, eight
one,two, three, five, six, seven, eight
three,four, five, six, seven, eight, nine
one,two, three, five, six, seven, eight
three,four, five, six, seven, eight, nine
three,four, five, six, seven, eight, nine
three,four, five, six, seven, eight, nine
three,four, five, six, seven, eight, nine
"""

try :
    with open(test_filename, "w") as f:
        f.write(csv_single_col)

    df_pandas = pandas.read_csv(test_filename, names=[0,1,2,3,4,5, 6])
    print("pandas df #####################")
    print(df_pandas)
    print(df_pandas.dtypes)
    print(f"{df_pandas.iloc[0,1]}, {type(df_pandas.iloc[0,1])}")
    df_pd = pd.read_csv(test_filename, names=[0,1,2,3,4,5, 6])
    print(df_pd)
    print(df_pd.dtypes)
    print(f"{df_pd.iloc[0,1]}, {type(df_pd.iloc[0,1])}")
```
### Describe the problem
read_csv incorrectly sets data type for columns with multiple types of columns. In the example, pandas sets the numbers in the second columns to strings because the column is of type object. Modin will make the data int.

### Source code / logs
```
FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
pandas df #####################
        0     1       2      3       4       5       6
0     one     2   three   five     six   seven   eight
1   three     4    five    six   seven   eight    nine
2     one     2   three   five     six   seven   eight
3     one   two   three   five     six   seven   eight
4     one   two   three   five     six   seven   eight
5     one   two   three   five     six   seven   eight
6   three  four    five    six   seven   eight    nine
7     one   two   three   five     six   seven   eight
8   three  four    five    six   seven   eight    nine
9   three  four    five    six   seven   eight    nine
10  three  four    five    six   seven   eight    nine
11  three  four    five    six   seven   eight    nine
0    object
1    object
2    object
3    object
4    object
5    object
6    object
dtype: object
df[0,1]=2, type=<class 'str'>
        0     1       2      3       4       5       6
0     one     2   three   five     six   seven   eight
1   three     4    five    six   seven   eight    nine
2     one     2   three   five     six   seven   eight
3     one   two   three   five     six   seven   eight
4     one   two   three   five     six   seven   eight
5     one   two   three   five     six   seven   eight
6   three  four    five    six   seven   eight    nine
7     one   two   three   five     six   seven   eight
8   three  four    five    six   seven   eight    nine
9   three  four    five    six   seven   eight    nine
10  three  four    five    six   seven   eight    nine
11  three  four    five    six   seven   eight    nine
0    object
1    object
2    object
3    object
4    object
5    object
6    object
dtype: object
df[0,1]=2, type=<class 'numpy.int64'>
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    df_equals(df_pandas, df_pd)
  File "/home/khang/git/modin/modin/pandas/test/utils.py", line 520, in df_equals
    check_categorical=False,
  File "/home/khang/anaconda3/envs/modin-dev/lib/python3.6/site-packages/pandas/_testing.py", line 1623, in assert_frame_equal
    atol=atol,
  File "/home/khang/anaconda3/envs/modin-dev/lib/python3.6/site-packages/pandas/_testing.py", line 1401, in assert_series_equal
    index_values=np.asarray(left.index),
  File "pandas/_libs/testing.pyx", line 67, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 182, in pandas._libs.testing.assert_almost_equal
  File "/home/khang/anaconda3/envs/modin-dev/lib/python3.6/site-packages/pandas/_testing.py", line 1036, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 1] (column name="1") are different

DataFrame.iloc[:, 1] (column name="1") values are different (16.66667 %)
[index]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[left]:  [2, 4, 2, two, two, two, four, two, four, four, four, four]
[right]: [2, 4, 2, two, two, two, four, two, four, four, four, four]
```

**Comment by pyrito** [comment]
Hi @kvu35 I just ran this on the latest master and this appears to be working correctly now. Please re-open this issue if the problem is persisting!
