### ISSUE TITLE
Creating a new Column inside a for loop, then trying to access raises an IndexError. 

### ISSUE THREAD

**Issue by javierabosch** [modin-project/modin#2268]
Linux Ubuntu 18.04 
Modin version 0.8.1.1
Python Version 3.7.9

When Creating a new column inside a for loop, trying to access that column raises an IndexError: List index out of range. 

Below I am assigning a new column to each item in a list. sub_topics is a column containing a list of 5 tags. 

```
for i in range(5):
    data[f'st_tag_{i}'] = data['sub_topics'].map(lambda x: x[i])
    print(data[f'st_tag_{i}'].head(2)) # Error caused here. 
```

### Source code / logs

---------------------------------------------------------------------------
RayTaskError(IndexError)                  Traceback (most recent call last)
<ipython-input-57-3c0b83124e0f> in <module>
      1 for i in range(5):
----> 2     data[f'st_tag_{i}'] = data['sub_topics'].map(lambda x: x[i])
      3     print(data[f'st_tag_{i}'].head(2))
      4     break
      5 # data.columns

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/pandas/dataframe.py in __setitem__(self, key, value)
   3222             if isinstance(value, Series):
   3223                 value = value._query_compiler
-> 3224             self._update_inplace(self._query_compiler.setitem(0, key, value))
   3225 
   3226     def __hash__(self):

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py in setitem(self, axis, key, value)
   2170                     )
   2171                     second_mask = self._modin_frame.mask(
-> 2172                         col_numeric_idx=list(range(idx + 1, len(self.columns)))
   2173                     )
   2174                     return self.__constructor__(

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/engines/base/frame/data.py in mask(self, row_indices, row_numeric_idx, col_indices, col_numeric_idx)
    564             new_col_widths,
    565             new_dtypes,
--> 566             validate_axes="all" if new_partitions.size != 0 else False,
    567         )
    568         # Check if monotonically increasing, return if it is. Fast track code path for

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/engines/base/frame/data.py in __init__(self, partitions, index, columns, row_lengths, column_widths, dtypes, validate_axes)
     81         self._dtypes = dtypes
     82         if validate_axes is not False:
---> 83             self._validate_internal_indices(mode=validate_axes)
     84         self._filter_empties()
     85 

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/engines/base/frame/data.py in _validate_internal_indices(self, mode, **kwargs)
    345 
    346         if args.get("validate_index", True):
--> 347             self._validate_axis_equality(axis=0, force=args.get("force"))
    348         if args.get("validate_columns", True):
    349             self._validate_axis_equality(axis=1, force=args.get("force"))

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/engines/base/frame/data.py in _validate_axis_equality(self, axis, force)
    280         """
    281         internal_axis = self._frame_mgr_cls.get_indices(
--> 282             axis, self._partitions, lambda df: df.axes[axis]
    283         )
    284         self_axis = self.axes[axis]

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition_manager.py in get_indices(cls, axis, partitions, index_func)
     97                 else []
     98             )
---> 99         new_idx = ray.get(new_idx)
    100         return new_idx[0].append(new_idx[1:]) if len(new_idx) else new_idx
    101 

/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/ray/worker.py in get(object_refs, timeout)
   1426                     worker.core_worker.dump_object_store_memory_usage()
   1427                 if isinstance(value, RayTaskError):
-> 1428                     raise value.as_instanceof_cause()
   1429                 else:
   1430                     raise value

RayTaskError(IndexError): ray::deploy_ray_func() (pid=17291, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 448, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 470, in ray._raylet.execute_task
ray.exceptions.RayTaskError: ray::deploy_ray_func() (pid=17265, ip=172.17.0.2)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 217, in deploy_ray_func
    partition = func(partition, **kwargs)
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/data_management/functions/mapfunction.py", line 23, in <lambda>
    lambda x: function(x, *args, **kwargs), *call_args, **call_kwds
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/pandas/core/frame.py", line 7598, in applymap
    return self.apply(infer)
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/pandas/core/frame.py", line 7541, in apply
    return op.get_result()
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_standard()
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/pandas/core/apply.py", line 255, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/pandas/core/apply.py", line 284, in apply_series_generator
    results[i] = self.f(v)
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/pandas/core/frame.py", line 7596, in infer
    return lib.map_infer(x.astype(object)._values, func)
  File "pandas/_libs/lib.pyx", line 2388, in pandas._libs.lib.map_infer
  File "/opt/conda/envs/tsuyaku_env/lib/python3.7/site-packages/modin/pandas/series.py", line 1059, in <lambda>
    if pandas.isnull(s) is not True or na_action is None
  File "<ipython-input-56-0426fc8a59f4>", line 2, in <lambda>
IndexError: list index out of range

**Comment by javierabosch** [comment]
When accessing and working on the modin DataFrame instead of Series.map, it worked. So putting an additional [] around the column accessor did the trick. I am not sure if the modin team would want to address this. 

Working version: 

for i in range(5):
    data[f'st_tag_{i}'] = data[['sub_topics']].apply(lambda x: x[i]) # Fixed Error
    print(data[f'st_tag_{i}'].head(2)) # Can access column now.
