### ISSUE TITLE
Dictionary aggregation does not support axis=1

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#2308]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 19.10

- **Modin version** (`modin.__version__`):

0.8.1.1+31.ga0a3ebb

- **Python version**:

Python 3.8.3

- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd
#import pandas as pd

df = pd.DataFrame({
    "col1": [ 1,  2,  1,  2,  1,  3,  3,  2,  3],
    "col2": [11, 12, 13, 14, 15, 16, 17, 18, 19],
    "col3": [ 4,  4,  4,  4,  5,  5,  5,  5,  5],
    "col4": [ 1,  1,  1,  1,  1,  1,  1,  1,  1]
})
print(df, '\n')

df0 = df.agg({5: 'max'}, axis=1)
print(df0, '\n')
```

### Describe the problem

Code above throws an exception because currently only `axis=0` case is handled https://github.com/modin-project/modin/blob/master/modin/pandas/base.py#L497

**Comment by mvashishtha** [comment]
On Modin version d231df0fb13918b40827aa5fd61ac5516e7e9dac, I get two errors, one in the main thread and one in a remote ray task:

<details>

<summary>Main thread stack trace </summary>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 13>()
      5 df = pd.DataFrame({
      6     "col1": [ 1,  2,  1,  2,  1,  3,  3,  2,  3],
      7     "col2": [11, 12, 13, 14, 15, 16, 17, 18, 19],
      8     "col3": [ 4,  4,  4,  4,  5,  5,  5,  5,  5],
      9     "col4": [ 1,  1,  1,  1,  1,  1,  1,  1,  1]
     10 })
     11 print(df, '\n')
---> 13 df0 = df.agg({5: 'max'}, axis=1)
     14 print(df0, '\n')

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/pandas/base.py:609, in BasePandasDataset.aggregate(self, func, axis, *args, **kwargs)
    607 if result is None:
    608     kwargs.pop("is_transform", None)
--> 609     return self.apply(func, axis=axis, args=args, **kwargs)
    610 return result

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/pandas/dataframe.py:368, in DataFrame.apply(self, func, axis, raw, result_type, args, **kwargs)
    364 """
    365 Apply a function along an axis of the ``DataFrame``.
    366 """
    367 axis = self._get_axis_number(axis)
--> 368 query_compiler = super(DataFrame, self).apply(
    369     func, axis=axis, raw=raw, result_type=result_type, args=args, **kwargs
    370 )
    371 if not isinstance(query_compiler, type(self._query_compiler)):
    372     # A scalar was returned
    373     return query_compiler

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/pandas/base.py:891, in BasePandasDataset.apply(self, func, axis, broadcast, raw, reduce, result_type, convert_dtype, args, **kwds)
    885     if len(self.columns) != len(set(self.columns)):
    886         warnings.warn(
    887             "duplicate column names not supported with apply().",
    888             FutureWarning,
    889             stacklevel=2,
    890         )
--> 891 query_compiler = self._query_compiler.apply(
    892     func,
    893     axis,
    894     args=args,
    895     raw=raw,
    896     result_type=result_type,
    897     **kwds,
    898 )
    899 return query_compiler

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:2362, in PandasQueryCompiler.apply(self, func, axis, *args, **kwargs)
   2360 kwargs = try_cast_to_pandas(kwargs)
   2361 if isinstance(func, dict):
-> 2362     return self._dict_func(func, axis, *args, **kwargs)
   2363 elif is_list_like(func):
   2364     return self._list_like_func(func, axis, *args, **kwargs)

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/core/storage_formats/pandas/query_compiler.py:2399, in PandasQueryCompiler._dict_func(self, func, axis, *args, **kwargs)
   2395     return pandas.DataFrame(df.apply(func_dict, *args, **kwargs))
   2397 func = {k: wrap_udf_function(v) if callable(v) else v for k, v in func.items()}
   2398 return self.__constructor__(
-> 2399     self._modin_frame.apply_full_axis_select_indices(
   2400         axis, dict_apply_builder, func, keep_remaining=False
   2401     )
   2402 )

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:115, in lazy_metadata_decorator.<locals>.decorator.<locals>.run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    113     elif apply_axis == "rows":
    114         obj._propagate_index_objs(axis=0)
--> 115 result = f(self, *args, **kwargs)
    116 if apply_axis is None and not transpose:
    117     result._deferred_index = self._deferred_index

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:1975, in PandasDataframe.apply_full_axis_select_indices(self, axis, func, apply_indices, numeric_indices, new_index, new_columns, keep_remaining)
   1973 if new_columns is None:
   1974     new_columns = self.columns if axis == 0 else None
-> 1975 return self.__constructor__(new_partitions, new_index, new_columns, None, None)

File ~/software_sources/modin/modin/logging/logger_metaclass.py:68, in logger_class_wrapper.<locals>.log_wrap(*args, **kwargs)
     66     logger.info(f"END::PANDAS-API::{class_name}.{method_name}")
     67     return result
---> 68 return method(*args, **kwargs)

File ~/software_sources/modin/modin/core/dataframe/pandas/dataframe/dataframe.py:188, in PandasDataframe.__init__(self, partitions, index, columns, row_lengths, column_widths, dtypes)
    186 self._partitions = partitions
    187 self._index_cache = ensure_index(index)
--> 188 self._columns_cache = ensure_index(columns)
    189 if row_lengths is not None and len(self.index) > 0:
    190     # An empty frame can have 0 rows but a nonempty index. If the frame
    191     # does have rows, the number of rows must equal the size of the
    192     # index.
    193     num_rows = sum(row_lengths)

File ~/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/pandas/core/indexes/base.py:7043, in ensure_index(index_like, copy)
   7041         return Index._with_infer(index_like, copy=copy, tupleize_cols=False)
   7042 else:
-> 7043     return Index._with_infer(index_like, copy=copy)

File ~/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/pandas/core/indexes/base.py:680, in Index._with_infer(cls, *args, **kwargs)
    678 with warnings.catch_warnings():
    679     warnings.filterwarnings("ignore", ".*the Index constructor", FutureWarning)
--> 680     result = cls(*args, **kwargs)
    682 if result.dtype == _dtype_obj and not result._is_multi:
    683     # error: Argument 1 to "maybe_convert_objects" has incompatible type
    684     # "Union[ExtensionArray, ndarray[Any, Any]]"; expected
    685     # "ndarray[Any, Any]"
    686     values = lib.maybe_convert_objects(result._values)  # type: ignore[arg-type]

File ~/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/pandas/core/indexes/base.py:508, in Index.__new__(cls, data, dtype, copy, name, tupleize_cols, **kwargs)
    505     return klass._simple_new(arr, name)
    507 elif is_scalar(data):
--> 508     raise cls._scalar_data_error(data)
    509 elif hasattr(data, "__array__"):
    510     return Index(np.asarray(data), dtype=dtype, copy=copy, name=name, **kwargs)

TypeError: Index(...) must be called with a collection of some kind, None was passed
```
</details>

<details>

<summary>Remote error</summary>

```
 2022-06-13 14:17:01,608	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::deploy_ray_func() (pid=17818, ip=127.0.0.1)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 532, in deploy_ray_func
    result = func(*args, **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 162, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
TypeError: dict_apply_builder() got an unexpected keyword argument 'internal_indices'
2022-06-13 14:17:01,609	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::deploy_ray_func() (pid=17818, ip=127.0.0.1)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 532, in deploy_ray_func
    result = func(*args, **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 162, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
TypeError: dict_apply_builder() got an unexpected keyword argument 'internal_indices'
2022-06-13 14:17:01,609	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::deploy_ray_func() (pid=17818, ip=127.0.0.1)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 532, in deploy_ray_func
    result = func(*args, **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 162, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
TypeError: dict_apply_builder() got an unexpected keyword argument 'internal_indices'
2022-06-13 14:17:01,610	ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::deploy_ray_func() (pid=17818, ip=127.0.0.1)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py", line 532, in deploy_ray_func
    result = func(*args, **kwargs)
  File "/Users/maheshvashishtha/software_sources/modin/modin/core/dataframe/pandas/partitioning/axis_partition.py", line 162, in deploy_axis_func
    result = func(dataframe, *kwargs.pop("args", ()), **kwargs)
TypeError: dict_apply_builder() got an unexpected keyword argument 'internal_indices'
```
</details>

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
