### ISSUE TITLE
`DataFrame.mean` is broken in case of axis=1 and numeric_only=None

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2313]
### Describe the problem
`mean` produces an empty frame in case of applying on `axis=1`, However, other reduction operations works fine with `axis=1`

Reproducer:
```python
import modin.pandas as pd
import pandas
from modin.pandas.test.utils import (
    test_data_diff_dtype,
    df_equals,
)

pd_df = pandas.DataFrame(test_data_diff_dtype)
md_df = pd.DataFrame(test_data_diff_dtype)

reduction_operation = ["max", "min", "median", "skew", "kurt", "sem", "std", "var"]

for op in reduction_operation:
    df_equals(getattr(md_df, op)(axis=1), getattr(pd_df, op)(axis=1)) # works fine

df_equals(md_df.mean(axis=1), pd_df.mean(axis=1)) # AssertionError
```

<details><summary> Traceback </summary>

```

Traceback (most recent call last):
  File "../TESTS/t2.py", line 108, in <module>
    df_equals(md_df.mean(axis=1), pd_df.mean(axis=1))
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/test/utils.py", line 520, in df_equals
    assert_series_equal(df1, df2, check_dtype=False, check_series_type=False)
  File "/localdisk/dchigare/miniconda3/envs/modin_tests/lib/python3.7/site-packages/pandas/_testing.py", line 1401, in assert_series_equal
    index_values=np.asarray(left.index),
  File "pandas/_libs/testing.pyx", line 67, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 182, in pandas._libs.testing.assert_almost_equal
  File "/localdisk/dchigare/miniconda3/envs/modin_tests/lib/python3.7/site-packages/pandas/_testing.py", line 1036, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Series are different

Series values are different (100.0 %)
[index]: [0, 1, 2, 3]
[left]:  [nan, nan, nan, nan]
[right]: [-2.5, -2.1333333333333333, 6.033333333333334, 8.0]
```

</details>

**Comment by YarShev** [comment]
Before [this commit](https://github.com/modin-project/modin/commit/55e345951818761ad26711cde91bb0d2b296aa5f) there was the exception.
```
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
After the commit the result is the following:
```
0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64
```
May be, it will help somehow.
