### ISSUE TITLE
read_csv tests should be enabled in the `cloud` mode

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2340]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin version** (`modin.__version__`): 0.8.1.1+34.ga571e10
- **Python version**: 3.8.6
- **Code we can use to reproduce**:

### Describe the problem

Currently `read_csv` unit tests are xfailed.
### Source code / logs

```
_
modin/pandas/test/utils.py:731: in eval_io
    eval_general(
modin/pandas/test/utils.py:691: in eval_general
    comparator(*values)
modin/pandas/test/utils.py:518: in df_equals
    assert_frame_equal(
../miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexes/base.py:338: in __new__
    return _maybe_asobject(dtype, DatetimeIndex, data, copy, name, **kwargs)
../miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexes/base.py:5872: in _maybe_asobject
    return klass(data, dtype=dtype, copy=copy, name=name, **kwargs)
../miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py:271: in __new__
    dtarr = DatetimeArray._from_sequence(
../miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py:316: in _from_sequence
    subarr, tz, inferred_freq = sequence_to_dt64ns(
../miniconda3/envs/modin/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py:1965: in sequence_to_dt64ns
    if data.dtype != DT64NS_DTYPE:
../miniconda3/envs/modin/lib/python3.8/site-packages/rpyc/core/netref.py:194: in __ne__
    return syncreq(self, consts.HANDLE_CMP, other, '__ne__')
../miniconda3/envs/modin/lib/python3.8/site-packages/rpyc/core/netref.py:76: in syncreq
    return conn.sync_request(handler, proxy, *args)
modin/experimental/cloud/rpyc_proxy.py:160: in sync_request
    return super().sync_request(handler, *args)
../miniconda3/envs/modin/lib/python3.8/site-packages/rpyc/core/protocol.py:469: in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <AsyncResult object (ready) at 0x7f8511af9cc0>

    @property
    def value(self):
        """Returns the result of the operation. If the result has not yet
        arrived, accessing this property will wait for it. If the result does
        not arrive before the expiry time elapses, :class:`AsyncResultTimeout`
        is raised. If the returned result is an exception, it will be raised
        here. Otherwise, the result is returned directly.
        """
        self.wait()
        if self._is_exc:
>           raise self._obj
E           _get_exception_class.<locals>.Derived: Cannot interpret 'dtype('<M8[ns]')' as a data type
E
E           ========= Remote Traceback (1) =========
E           Traceback (most recent call last):
E             File "/localdisk/amyskov/miniconda3/envs/modin/lib/python3.8/site-packages/rpyc/core/protocol.py", line 320, in _dispatch_request
E               res = self._HANDLERS[handler](self, *args)
E             File "/localdisk/amyskov/miniconda3/envs/modin/lib/python3.8/site-packages/rpyc/core/protocol.py", line 585, in _handle_cmp
E               return self._access_attr(type(obj), op, (), "_rpyc_getattr", "allow_getattr", getattr)(obj, other)
E           TypeError: Cannot interpret 'dtype('<M8[ns]')' as a data type

../miniconda3/envs/modin/lib/python3.8/site-packages/rpyc/core/async_.py:102: TypeError
```

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
