### ISSUE TITLE
join function for a dataframe including NaN doesn't work

### ISSUE THREAD

**Issue by okapies** [modin-project/modin#2341]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): 0.8.1.1
- **Python version**: 3.8.1
- **Code we can use to reproduce**: see the below

### Describe the problem
Joining a dataframe including `NaN` value with another one make modin crash.

```python
>>> import modin.pandas as pd
>>> df = pd.DataFrame(range(3))
UserWarning: Distributing <class 'range'> object. This may take some time.
>>> df
   0
0  0
1  1
2  2

>>> df.shift(1)
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
UserWarning: Due to https://github.com/pandas-dev/pandas/issues/35092, Pandas ignores sort=False; Modin correctly does not sort.
     0
0  NaN
1    0
2    1

>>> df.shift(3).join(df, lsuffix='_0')
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
   0_0  0
0  NaN  0
1  NaN  1
2  NaN  2

>>> df.shift(1).join(df, lsuffix='_0')
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
UserWarning: Due to https://github.com/pandas-dev/pandas/issues/35092, Pandas ignores sort=False; Modin correctly does not sort.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 1472, in join
    query_compiler=self._query_compiler.concat(
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/backends/pandas/query_compiler.py", line 265, in concat
    new_modin_frame = self._modin_frame._concat(axis, other_modin_frame, join, sort)
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/engines/base/frame/data.py", line 1773, in _concat
    new_partitions = self._frame_mgr_cls.concat(axis, left_parts, right_parts)
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/engines/base/frame/partition_manager.py", line 392, in concat
    return np.concatenate([left_parts] + right_parts, axis=axis)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1
```

If you try to join a dataframe with another dataframe _including `NaN`_, things get even worse:

#### dask backend
```python
>>> df.join(df.shift(1), lsuffix='_0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 1472, in join
    query_compiler=self._query_compiler.concat(
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/backends/pandas/query_compiler.py", line 265, in concat
    new_modin_frame = self._modin_frame._concat(axis, other_modin_frame, join, sort)
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/engines/base/frame/data.py", line 1773, in _concat
    new_partitions = self._frame_mgr_cls.concat(axis, left_parts, right_parts)
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/engines/base/frame/partition_manager.py", line 392, in concat
    return np.concatenate([left_parts] + right_parts, axis=axis)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2
>>> distributed.worker - WARNING -  Compute Failed
Function:  lambda
args:      ([     0
0  NaN
1    0
2    1])
kwargs:    {}
Exception: IndexError('list index out of range')
```

#### ray backend
```python
>>> df.join(df.shift(1), lsuffix='_0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 1472, in join
    query_compiler=self._query_compiler.concat(
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/backends/pandas/query_compiler.py", line 265, in concat
    new_modin_frame = self._modin_frame._concat(axis, other_modin_frame, join, sort)
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/engines/base/frame/data.py", line 1773, in _concat
    new_partitions = self._frame_mgr_cls.concat(axis, left_parts, right_parts)
  File "/home/user/.pyenv/versions/3.8.1/lib/python3.8/site-packages/modin/engines/base/frame/partition_manager.py", line 392, in concat
    return np.concatenate([left_parts] + right_parts, axis=axis)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2
(pid=872713) F1030 10:34:55.044065 872713 872713 core_worker.cc:1604]  Check failed: object_ids.size() == metadatas.size() 
(pid=872713) *** Check failure stack trace: ***
(pid=872713)     @     0x7fc4252266ed  google::LogMessage::Fail()
(pid=872713)     @     0x7fc42522784c  google::LogMessage::SendToLog()
(pid=872713)     @     0x7fc4252263c9  google::LogMessage::Flush()
(pid=872713)     @     0x7fc4252265e1  google::LogMessage::~LogMessage()
(pid=872713)     @     0x7fc4251dd789  ray::RayLog::~RayLog()
(pid=872713)     @     0x7fc424eaa9b3  ray::CoreWorker::AllocateReturnObjects()
(pid=872713)     @     0x7fc424e28b17  __pyx_f_3ray_7_raylet_10CoreWorker_store_task_outputs()
(pid=872713)     @     0x7fc424dfb7d8  __pyx_f_3ray_7_raylet_task_execution_handler()
(pid=872713)     @     0x7fc424dd572c  std::_Function_handler<>::_M_invoke()
(pid=872713)     @     0x7fc424eac882  ray::CoreWorker::ExecuteTask()
(pid=872713)     @     0x7fc424e3f6cb  std::_Function_handler<>::_M_invoke()
(pid=872713)     @     0x7fc424ec9ced  _ZZN3ray28CoreWorkerDirectTaskReceiver14HandlePushTaskERKNS_3rpc15PushTaskRequestEPNS1_13PushTaskReplyESt8functionIFvNS_6StatusES7_IFvvEESA_EEENKUlvE_clEv
(pid=872713)     @     0x7fc424ec7fe3  ray::SchedulingQueue::Add()
(pid=872713)     @     0x7fc424ecb030  ray::CoreWorkerDirectTaskReceiver::HandlePushTask()
(pid=872713)     @     0x7fc424e8e08b  _ZN5boost4asio6detail18completion_handlerIZN3ray10CoreWorker14HandlePushTaskERKNS3_3rpc15PushTaskRequestEPNS5_13PushTaskReplyESt8functionIFvNS3_6StatusESB_IFvvEESE_EEEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(pid=872713)     @     0x7fc425287c3f  boost::asio::detail::scheduler::do_run_one()
(pid=872713)     @     0x7fc425288a01  boost::asio::detail::scheduler::run()
(pid=872713)     @     0x7fc425289952  boost::asio::io_context::run()
(pid=872713)     @     0x7fc424ea9318  ray::CoreWorkerProcess::RunTaskExecutionLoop()
(pid=872713)     @     0x7fc424d9ed46  __pyx_pw_3ray_7_raylet_10CoreWorker_5run_task_loop()
(pid=872713)     @     0x559955062d98  method_vectorcall_NOARGS
(pid=872713)     @     0x559954e85492  _PyEval_EvalFrameDefault
(pid=872713)     @     0x559954e7eac7  function_code_fastcall
(pid=872713)     @     0x559954e85492  _PyEval_EvalFrameDefault
(pid=872713)     @     0x559954f5c4d0  _PyEval_EvalCodeWithName
(pid=872713)     @     0x559954f5c573  PyEval_EvalCode
(pid=872713)     @     0x559954fa75ee  PyRun_FileExFlags
(pid=872713)     @     0x559954fa784d  PyRun_SimpleFileExFlags
(pid=872713)     @     0x559954e8a2e0  Py_RunMain
(pid=872713)     @     0x559954e8a796  Py_BytesMain
(pid=872713)     @     0x7fc427c5a0b3  __libc_start_main
(pid=872713)     @     0x559954e894ca  _start
E1030 10:34:55.171507 872613 872856 core_worker.cc:411] Will resubmit task after a 5000ms delay: Type=NORMAL_TASK, Language=PYTHON, Resources: {CPU: 1, }, function_descriptor={type=PythonFunctionDescriptor, module_name=modin.engines.ray.pandas_on_ray.frame.axis_partition, class_name=, function_name=deploy_ray_func, function_hash=3d75e707cde97077eae3889b958ff841bbadf285}, task_id=fa2b6be6dc9835d3ffffffff01000000, task_name=deploy_ray_func(), job_id=01000000, num_args=16, num_returns=6
```

**Comment by YarShev** [comment]
Hi @okapies , thanks for posting! There was the issue in the Modin release 0.8.1.1 but now the one is fixed. We are having new release on this week. Could you please update your Modin version after our release and check it? As for now I am closing the issue but if there is still the problem, feel free to reopen the issue.
