### ISSUE TITLE
read_excel error "Internal and external indices on axis 1 do not match." When multiple empty columns on first line

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#2404]
This error comes from a mismatch in Modin pandas behavior when naming columns. The pandas naming convention is not completely consistent so further investigation is required.

Error stacktrace:
```
>>> pd.read_excel('test_emptyline.xlsx')
UserWarning: Parallel `read_excel` is a new feature! Please email bug_reports@modin.org if you run into any problems.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\foo\modin\pandas\dataframe.py", line 183, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "c:\foo\modin\pandas\base.py", line 168, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()
  File "c:\foo\modin\backends\pandas\query_compiler.py", line 233, in to_pandas
    return self._modin_frame.to_pandas()
  File "c:\foo\modin\engines\base\frame\data.py", line 2063, in to_pandas
    f"Internal and external indices on axis {axis} do not match.",
  File "c:\foo\modin\error_message.py", line 63, in catch_bugs_and_request_email
    " caused this error.\n{}".format(extra_log)
Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 1 do not match.
```

**Comment by devin-petersohn** [comment]
As a temporary workaround, setting `df.columns = df.columns` fixes the mismatch, but the columns will not be `"Unnamed X"`. In the case these names are thrown away later it will not matter.

**Comment by vnlitvinov** [comment]
@devin-petersohn do you have a reproducer or at least a sample? It's unclear to me how to reproduce the issue.

**Comment by devin-petersohn** [comment]
This should be able to be reproduced with an excel file with a blank first line.

**Comment by vnlitvinov** [comment]
Yeah, got that showing up using a cooked-up excel file. Thanks!

**Comment by vnlitvinov** [comment]
Note: this happens only with "parallel Excel reader" (i.e. with `MODIN_ENGINE` != `Python`).
