### ISSUE TITLE
Named aggregation doesn't work with Series objects

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#2405]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.8.2.1+6.g2b0b755

- **Python version**:

Python 3.7.8

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

s1 = pd.Series([10, 10, 10, 1, 1, 1, 2, 3])
s1.name = "data"

print(s1)
print(type(s1))
gb = s1.groupby(level=0)
print(gb.groups)
s2 = gb.agg(result=("max"))
print(s2)
print(type(s2))
```

### Describe the problem

On Modin this code throws exception from Pandas `reconstruct_func` because it doesn't accept such arguments.
```
Traceback (most recent call last):
  File "groupby_test24.py", line 10, in <module>
    s2 = gb.agg(result=("max"))
  File "/localdisk/gashiman/modin/modin/pandas/groupby.py", line 376, in aggregate
    func, **kwargs
  File "/localdisk/gashiman/modin/modin/pandas/groupby.py", line 364, in _reconstruct_func
    func, **kwargs
  File "/localdisk/gashiman/miniconda3/envs/modin_on_omnisci/lib/python3.7/site-packages/pandas/core/aggregation.py", line 86, in reconstruct_func
    raise TypeError("Must provide 'func' or tuples of '(column, aggfunc).")
TypeError: Must provide 'func' or tuples of '(column, aggfunc).
```

**Comment by pyrito** [comment]
I am able to reproduce this bug on the latest master.
