### ISSUE TITLE
Problem with using MODIN_ON_RAY_PLASMA_DIR environment variable

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2473]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **Modin version** (`modin.__version__`): f7f1f7ac553dc3cc6595204fb7566db0e8f7f85f
- **Python version**: 3.8.6
- **Code we can use to reproduce**:
```
export MODIN_ON_RAY_PLASMA_DIR=/some/path/tmp
python -c "import modin.pandas as pd"
```

### Source code / logs

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/modin/modin/pandas/__init__.py", line 178, in <module>
    Engine.subscribe(_update_engine)
  File "/modin/modin/config/pubsub.py", line 95, in subscribe
    callback(cls)
  File "/modin/modin/pandas/__init__.py", line 119, in _update_engine
    initialize_ray()
  File "/modin/modin/engines/ray/utils.py", line 139, in initialize_ray
    ray.init(
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/worker.py", line 713, in init
    _global_node = ray.node.Node(
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/node.py", line 207, in __init__
    self.start_ray_processes()
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/node.py", line 825, in start_ray_processes
    ray._private.services.determine_plasma_store_config(
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/_private/services.py", line 1575, in determine_plasma_store_config
    raise ValueError(f"The file {plasma_directory} does not "
ValueError: The file /Some/Path/Tmp does not exist or is not a directory.
```

**Comment by vnlitvinov** [comment]
This is caused by my https://github.com/modin-project/modin/pull/2189, so I'm taking this issue.
