### ISSUE TITLE
Dask engine can only have 4 partitions - Pull Requests #2492 

### ISSUE THREAD

**Issue by zhfanrui** [modin-project/modin#2498]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS release 6.5 (Final)
- **Modin version** (`modin.__version__`): 0.8.2 installed from conda-forge channel
- **Python version**: 3.7.3
- **Code we can use to reproduce**:
```python
from distributed import Client
client = Client(n_workers=10)
import modin.pandas as pd
df = pd.read_csv(filename)
```

### Describe the problem

Hi there, I recently got a really huge CSV file to read and found that no matter how I declare the number of the worker by using
```python
from distributed import Client
client = Client(n_workers=10)
import modin.pandas as pd
```
The partition of the Dataframe object is still 4 causing the efficiency really low.

So I reviewed some of the code briefly (actually it takes me a whole afternoon to track the problem) and found `pd.DEFAULT_NPARTITIONS` is 4 defaulted (in file `modin/modin/pandas/__init__.py`) and the init function (`_update_engine`) didn't change the value of it when using Dask engine.

Hence, I change `pd.DEFAULT_NPARTITIONS` after importing `pd` by 
```python
pd.DEFAULT_NPARTITIONS = 10
```
and it works well!

So I decided to add a line of code to solve this problem (See Pull Requests #2492 ). However, it failed in `test_read_csv_datetime`. Really confused about that.

**Comment by devin-petersohn** [comment]
Hi @zhfanrui, thanks for the report!

I can reproduce the issue, and your PR does fix the issue. I am not sure why the tests failed in that way because I do not see the issue when locally running the tests with that change.

Relevant Test Traceback:
```
  File "/modin/modin/pandas/__init__.py", line 138, in _update_engine
    num_cpus = len(dask_client.nthreads())
TypeError: object of type 'coroutine' has no len()
```

Any ideas here?

**Comment by YarShev** [comment]
@devin-petersohn , when running locally I got the same error. Maybe that is related to how we execute `_update_engine` via `Engine.subcribe`. @vnlitvinov , are there any thoughts on this?
The log from the PR can be found here ([link](https://github.com/modin-project/modin/pull/2492#issuecomment-736242901)).

**Comment by devin-petersohn** [comment]
@YarShev which tests did you run to reproduce? I ran the I/O tests and did not have the error.

**Comment by YarShev** [comment]
@devin-petersohn , I ran `pytest modin/pandas/test/test_io.py::TestReadCSV::test_read_csv_datetime`. After some digging it was found out we fall down into this [place](https://github.com/dask/distributed/blob/f018007fba3b5d82e7b1a484ba758d2c302abd25/distributed/client.py#L826). That's why we can see the error.

**Comment by YarShev** [comment]
The reason of IO tests failure for Dask has been found out. It is related to how pytest runs a test with different types of parameters. When we use something from `modin.pandas` as a parameter of the test, Dask workers initialization is occurred in asynchronous mode and `ncores` always returns a coroutine. Thus, we should avoid use of whatever from `modin.pandas` as a parameter of the test.

Inside of a test we can use whatever from `modin.pandas`.

**Comment by NQ31** [comment]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python@3.7/3.7.11/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/huangxiaoqi/project_data/pycharm_project/test_project/m_collection.py", line 24, in <module>
    d.collection()
  File "/Users/huangxiaoqi/project_data/pycharm_project/test_project/m_collection.py", line 15, in collection
    df_d['onlie']=df_d.apply(lambda x:get_online(x,df_detail,df_banbiao),axis=1)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/pandas/dataframe.py", line 362, in apply
    func, axis=axis, raw=raw, result_type=result_type, args=args, **kwargs
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/pandas/base.py", line 861, in apply
    **kwds,
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py", line 2343, in apply
    return self._callable_func(func, axis, *args, **kwargs)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py", line 2483, in _callable_func
    axis, lambda df: df.apply(func, axis=axis, *args, **kwargs)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/engines/base/frame/data.py", line 1402, in apply_full_axis
    other=None,
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/engines/base/frame/data.py", line 1811, in broadcast_apply_full_axis
    keep_partitioning=True,
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/engines/base/frame/partition_manager.py", line 421, in broadcast_axis_partitions
    preprocessed_map_func = cls.preprocess_func(apply_func)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/engines/base/frame/partition_manager.py", line 113, in preprocess_func
    return cls._partition_class.preprocess_func(map_func)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/modin/engines/dask/pandas_on_dask/frame/partition.py", line 268, in preprocess_func
    return default_client().scatter(func, hash=False, broadcast=True)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/client.py", line 2155, in scatter
    hash=hash,
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/client.py", line 841, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/client.py", line 2042, in _scatter
    timeout=timeout,
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/core.py", line 874, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/core.py", line 667, in send_recv
    raise exc.with_traceback(tb)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/scheduler.py", line 5639, in scatter
    nthreads, data, rpc=self.rpc, report=False
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/utils_comm.py", line 150, in scatter_to_workers
    for address, v in d.items()
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/utils.py", line 210, in All
    result = await tasks.next()
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/core.py", line 874, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/Users/huangxiaoqi/env_workspaces/env_3.7.11/lib/python3.7/site-packages/distributed/core.py", line 669, in send_recv
    raise Exception(response["exception_text"])
Exception: TypeError("object of type 'coroutine' has no len()")

I also encountered this problem? Is there a solution now?

**Comment by YarShev** [comment]
Hi @NQ31 , could you give a bit more advanced description (Modin release, script itself, machine configuration, dataset)?

**Comment by surenjanath** [comment]
Hi I am getting this coroutine error when trying to do the following : 

```
def ReturnAmount(data):
    i = data
    # print('-'*10, 'Running Process', '-'*10)
    PolicyNumber = i['PolicyNumber'].strip()
    # print(f'[*] {PolicyNumber}')
    try:
        x = trans1[trans1['Policy Number'].isin([PolicyNumber])]
        if len(x) > 0:
            Val = x[x['Date'].isin([pd.to_datetime(i['LastRunDate'])])].iloc[-1].to_dict()
            return Val
    except IndexError:
        return None
    except AttributeError:
        return None
    except TypeError:
        return None
cis1.apply(ReturnAmount, axis=1)
```


trans1 is another dataframe with atleast 300k data.
No matter what I do it gives the same error.


Error : 
![image](https://user-images.githubusercontent.com/42503383/180276655-294551a8-e535-442d-94ca-4612f5f79cf1.png)

![image](https://user-images.githubusercontent.com/42503383/180276711-70a83095-6c42-411e-b845-af7bb426089b.png)


My imported Libraries : 
![Uploading image.png…]()

**Comment by YarShev** [comment]
Hi @surenjanath, could you please create a new issue for your problem where we can discuss it in more details?
