### ISSUE TITLE
Calling print or to_pandas function on dataframe with objects in index causes exception

### ISSUE THREAD

**Issue by richardlin047** [modin-project/modin#2521]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.15.7 
- **Modin version** (`modin.__version__`): 0.8.1.1+25.g544de0d9
- **Python version**: Python 3.8.5
- **Code we can use to reproduce**:
```
import modin.pandas as pd
class MyObject(object):
     def __init__(self, obj):
         self.obj = obj
 
df = pd.DataFrame({"a": [1,2]}, index=[MyObject(None),MyObject(None)])
print(df)
```
 or 
```
df = pd.DataFrame({"a": [1,2]}, index=[MyObject(None),MyObject(None)])
df._to_pandas()
```

### Describe the problem

Only tested on Ray backend so far.
The `to_pandas` function throws an exception if the dataframe has objects in its index. The print function will also throw this exception because it calls the `to_pandas` function when creating a repr pandas dataframe to print. 
_modin/pandas/base.py:168_
`return self.iloc[indexer]._query_compiler.to_pandas()`
_modin/engines/base/frame/data.py:1889_
`df = self._frame_mgr_cls.to_pandas(self._partitions)`

The `to_pandas` function retrieves the objects in the partition objects, which result in different memory addresses for the objects in the pandas dataframe compared to the modin dataframe.
_modin/engines/base/frame/partition_manager.py:427_
`retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]`

After the partitions are converted to a pandas dataframes, the following code checks that the axes i.e. row index and column index of the pandas dataframe and modin dataframe match. However, since the objects in the index have different memory addresses, the axes are not equal.
_modin/engines/base/frame/data.py:1897_
```            
ErrorMessage.catch_bugs_and_request_email(
    not df.axes[axis].equals(self.axes[axis]),
    f"Internal and external indices on axis {axis} do not match.",
)
```

### Source code / logs

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/richard/Documents/CS262/modin/modin/pandas/base.py", line 2614, in __str__
    return repr(self)
  File "/Users/richard/Documents/CS262/modin/modin/pandas/dataframe.py", line 182, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/Users/richard/Documents/CS262/modin/modin/pandas/base.py", line 168, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()
  File "/Users/richard/Documents/CS262/modin/modin/backends/pandas/query_compiler.py", line 199, in to_pandas
    return self._modin_frame.to_pandas()
  File "/Users/richard/Documents/CS262/modin/modin/engines/base/frame/data.py", line 1897, in to_pandas
    ErrorMessage.catch_bugs_and_request_email(
  File "/Users/richard/Documents/CS262/modin/modin/error_message.py", line 60, in catch_bugs_and_request_email
    raise Exception(
Exception: Internal Error. Please email bug_reports@modin.org with the traceback and command that caused this error.
Internal and external indices on axis 0 do not match.
```

**Comment by richardlin047** [comment]
Related, setting the index to a column with objects does not work as expected.
**Code**
```
import modin.pandas as pd
class MyObject(object):
    def __init__(self, obj):
        self.obj = obj
df = pd.DataFrame({"a": [1,2,], "b":[MyObject(None),MyObject(None)]})
print(df)
df.set_index("b")
print(df)
```
**Output**
```
   a                                          b
0  1  <__main__.MyObject object at 0x3785d23a0>
1  2  <__main__.MyObject object at 0x37afa5160>
   a                                          b
0  1  <__main__.MyObject object at 0x37aef4850>
1  2  <__main__.MyObject object at 0x37aef4f70>
```

**Comment by pyrito** [comment]
I am able to reproduce this bug on the latest master.
