### ISSUE TITLE
read_csv with Ray engine works incorrectly with date data and names parameter provided

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2529]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 19.10
- **Modin version**: 25928495ed5bf69ae54067952e41a05306fc596b
- **Python version**: 3.8.6
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd
from modin.pandas.test.utils import df_equals

test_filename = "modin/pandas/test/data/test_time_parsing.csv"

kwargs = {
    "filepath_or_buffer": test_filename,
    "names": ['timestamp', 'symbol', 'high', 'low', 'open', 'close', 'spread', 'volume'],
}
df_pandas = pandas.read_csv(**kwargs)
df_modin = pd.read_csv(**kwargs)

df_equals(df_modin, df_pandas)
```

### Source code / logs

```
Traceback (most recent call last):
  File "test.py", line 359, in <module>
    df_equals(df_modin, df_pandas)
  File "/modin/modin/pandas/test/utils.py", line 520, in df_equals
    assert_frame_equal(
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/pandas/_testing.py", line 1611, in assert_frame_equal
    assert_series_equal(
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/pandas/_testing.py", line 1394, in assert_series_equal
    _testing.assert_almost_equal(
  File "pandas/_libs/testing.pyx", line 67, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 182, in pandas._libs.testing.assert_almost_equal
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/pandas/_testing.py", line 1036, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 2] (column name="high") are different

DataFrame.iloc[:, 2] (column name="high") values are different (50.0 %)
[index]: [0, 1, 2, 3]
[left]:  [high, 93.52600, 93.475, 93.421]
[right]: [high, 93.52600, 93.47500, 93.42100]
```

**Comment by pyrito** [comment]
I'm able to reproduce this bug on the latest master.

**Comment by anmyachev** [comment]
Looks like https://github.com/modin-project/modin/pull/5507 should fix this issue.
