### ISSUE TITLE
concat fails with ValueError: all the input array dimensions...

### ISSUE THREAD

**Issue by v1gnesh** [modin-project/modin#2586]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10
- **Modin version** (`modin.__version__`): 0.8.2
- **Python version**: 3.8.6
- **Code we can use to reproduce**:

df on the left:
```
df:
(4000000, 3)
SERNO                    uint64
START            datetime64[ns]
END              datetime64[ns]
```

df on the right:
```
mask = df['end].dt.dayofweek - df['start'].dt.dayofweek == 1
df_day2 = df.loc[mask].copy()

(88891, 3)
SERNO                    uint64
START            datetime64[ns]
END              datetime64[ns]
```

In short, `df_day2` is a portion of `df`

### Describe the problem
Modin `concat` seems to think the shape of array at index 0 is different.

### Source code / logs
```
Traceback (most recent call last):
  File "D:/heatmap/reading-modin.py", line 359, in <module>
    df, rt2 = f2_midnight_splits(df)
  File "D:/heatmap/reading-modin.py", line 153, in f2_midnight_splits
    df = pd.concat([df, df_day2], ignore_index=True)
  File "C:\Program Files\Python38\lib\site-packages\modin\pandas\general.py", line 362, in concat
    new_query_compiler = list_of_objs[0].concat(
  File "C:\Program Files\Python38\lib\site-packages\modin\backends\pandas\query_compiler.py", line 303, in concat
    new_modin_frame = self._modin_frame._concat(axis, other_modin_frame, join, sort)
  File "C:\Program Files\Python38\lib\site-packages\modin\engines\base\frame\data.py", line 1854, in _concat
    new_partitions = self._frame_mgr_cls.concat(axis, left_parts, right_parts)
  File "C:\Program Files\Python38\lib\site-packages\modin\engines\base\frame\partition_manager.py", line 406, in concat
    return np.concatenate([left_parts] + right_parts, axis=axis)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 3
```

**Comment by anmyachev** [comment]
Tried the following example as an attempt at repro on 0.14.0 release. Error not reproducible.
```python
import modin.pandas as pd
import numpy as np

df1 = pd.DataFrame(np.zeros((100, 3)))
df1["date"] = pd.date_range(start='1/1/2018', periods=100)
df2 = df1.loc[[True, False]*50].copy()
print(pd.concat([df1, df2], ignore_index=True))
```

@v1gnesh thanks for posting! Feel free to reopen the issue if needed.
