### ISSUE TITLE
omnisci engine doesn't work with numpy==1.20.0

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#2680]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`): 03ea9b2c3728a83cd9247a89b72677409cdc7dfd
- **Python version**: `3.7.9`
- **Code we can use to reproduce**:
```python
python modin/examples/docker/taxi-on-omnisci/nyc-taxi-omnisci.py
```

### Source code / logs

```
Traceback (most recent call last):
  File "/home/modin/nyc-taxi-omnisci.py", line 108, in <module>
    main()
  File "/home/modin/nyc-taxi-omnisci.py", line 101, in main
    df = measure('Reading', read)
  File "/home/modin/nyc-taxi-omnisci.py", line 95, in measure
    res = func(*args, **kw)
  File "/home/modin/nyc-taxi-omnisci.py", line 53, in read
    parse_dates=dates_only,
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/pandas/io.py", line 115, in parser_func
    return _read(**kwargs)
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/pandas/io.py", line 133, in _read
    pd_obj = EngineDispatcher.read_csv(**kwargs)
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/data_management/factories/dispatcher.py", line 104, in read_csv
    return cls.__engine._read_csv(**kwargs)
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/data_management/factories/factories.py", line 87, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/experimental/engines/omnisci_on_ray/io.py", line 141, in read_csv
    column_types = {c: cls._dtype_to_arrow(t) for c, t in dtype.items()}
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/experimental/engines/omnisci_on_ray/io.py", line 141, in <dictcomp>
    column_types = {c: cls._dtype_to_arrow(t) for c, t in dtype.items()}
  File "/home/modin/miniconda/envs/modin/lib/python3.7/site-packages/modin/experimental/engines/omnisci_on_ray/io.py", line 227, in _dtype_to_arrow
    return pa.from_numpy_dtype(tname)
  File "pyarrow/types.pxi", line 2591, in pyarrow.lib.from_numpy_dtype
  File "pyarrow/error.pxi", line 107, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Did not pass numpy.dtype object
```

**Comment by Garra1980** [comment]
Sad news it seems - https://github.com/numpy/numpy/issues/17913
