### ISSUE TITLE
GroupBy.size is broken for OmniSci backend

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#2856]
### System information
- **Modin version** (`modin.__version__`): 7c3218f
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import os
os.environ["MODIN_EXPERIMENTAL"] = True
os.environ["MODIN_BACKEND"] = "omnisci"

import modin.pandas as pd

df = pd.DataFrame({"col1": ["a", "b", "b"], "col2": [1, 2, 3]})
grp = df.groupby("col1")
print(grp.size()) # Error

```

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "rofl.py", line 5, in <module>
    print(df.groupby("col1").size()) # Error
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/base.py", line 2807, in __str__
    return repr(self)
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/series.py", line 254, in __repr__
    temp_df = self._build_repr_df(num_rows, num_cols)
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/base.py", line 152, in _build_repr_df
    if len(self.index) == 0 or (
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/base.py", line 2836, in __getattribute__
    return object.__getattribute__(self, item)
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/base.py", line 510, in _get_index
    return self._query_compiler.index
  File "/localdisk/dchigare/repos/modin_bp/modin/experimental/backends/omnisci/query_compiler.py", line 334, in _get_index
    return self._modin_frame.index
  File "/localdisk/dchigare/repos/modin_bp/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1137, in _get_index
    self._execute()
  File "/localdisk/dchigare/repos/modin_bp/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 1010, in _execute
    self._op, self._index_cols, self._dtypes, self._table_cols
  File "/localdisk/dchigare/repos/modin_bp/modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py", line 176, in run_exec_plan
    curs = omniSession.executeRA(cmd_prefix + calcite_json)
  File "/localdisk/dchigare/repos/modin_bp/modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py", line 64, in executeRA
    r = cls._server.executeRA(query)
  File "dbe.pyx", line 196, in dbe.PyDbEngine.executeRA
RuntimeError: expressions in ELSE clause must be of the same or compatible types as those in the THEN clauses.

```

</details>

### Describe the problem
The caused exceptions just hides the original problem, we see this error because of `fillna` call for the result of groupby [(this line)](https://github.com/modin-project/modin/blob/7c3218fd9a28b9612228d0dcd694693842ac971e/modin/pandas/groupby.py#L536). If we'll remove `fillna` and run the code above again we'll see the cause of that exception:
```
modin result:
col1
a    a
b    b
Name: __reduced__, dtype: category
dtype: category
Categories (2, object): ['a', 'b']

pandas result:
col1
a    1
b    2
dtype: int64
```
Instead of returning the group sizes it just returns us the name of groups. GroupBy size implementation at omnisci backend is similar to `df.groupby(by).agg({df.columns[0]: "size"})`. Futher experiments revealed this behaviour:
```python
df.groupby("col1").agg({"col2": "size"}) # works fine
df.groupby("col1").agg({"col1": "size"}) # don't works fine
```
So it seems, that attempt to aggregate the same column that we're grouping on becomes an issue here, and since we're dropping all the other columns instead of by-cols at `groupby.size` at the API level, it crashes all the time.

**Comment by dchigarev** [comment]
this is a blocker for #1294
