### ISSUE TITLE
Modin tests fail with ray nightly build

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#2985]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: 3de608449ce55521c8f6a089943e4ffec2797a23
- **Python version**: 3.8.8

### Describe the problem

It was found that `test-ray-master` CI fails for several Modin commits with message:
```
E                       ray.exceptions.RayTaskError: ray::deploy_ray_func() (pid=538, ip=172.17.0.3)
E                         File "python/ray/_raylet.pyx", line 458, in ray._raylet.execute_task
E                         File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
E                         File "python/ray/_raylet.pyx", line 349, in ray._raylet.raise_if_dependency_failed
E                       ray.exceptions.RayTaskError: ray::deploy_ray_func() (pid=457, ip=172.17.0.3)
E                         File "python/ray/_raylet.pyx", line 458, in ray._raylet.execute_task
E                         File "python/ray/_raylet.pyx", line 479, in ray._raylet.execute_task
E                         File "python/ray/_raylet.pyx", line 349, in ray._raylet.raise_if_dependency_failed
E                       ray.exceptions.RaySystemError: System error: No module named 'modin'
E                       traceback: Traceback (most recent call last):
E                         File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 248, in deserialize_objects
E                           obj = self._deserialize_object(data, metadata, object_ref)
E                         File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 190, in _deserialize_object
E                           return self._deserialize_msgpack_data(data, metadata_fields)
E                         File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 168, in _deserialize_msgpack_data
E                           python_objects = self._deserialize_pickle5_data(pickle5_data)
E                         File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/serialization.py", line 158, in _deserialize_pickle5_data
E                           obj = pickle.loads(in_band)
E                       ModuleNotFoundError: No module named 'modin'
```

Looks like the reason of fail is not related to CI themself since Ray from pip wheel gives the same error.

**Comment by devin-petersohn** [comment]
It is an issue only with that test it seems.

**Comment by mvashishtha** [comment]
@amyskov I don't see this bug in push-to-master tests for modin any more.
