### ISSUE TITLE
[OmniSci] merge failed when using None in 'suffixes' parameter

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3065]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): e4fa1409d6ee048dcdcafc092a10bdc90d965303
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```python
import numpy as np
from modin.pandas import DataFrame

df1 = DataFrame(np.random.randint(10**6, size=(500000, 512)), columns=[f"col{x}" for x in range(512)])
df2 = DataFrame(np.random.randint(10**6, size=(500000, 512)), columns=[f"col{x}" for x in range(512)])

df1.merge(df2, on="col1", how="left", suffixes=("left_", None), sort=False)._query_compiler._modin_frame._execute()
```

### Source code / logs

```bash
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
Traceback (most recent call last):
  File "benchmarks/test.py", line 41, in <module>
    execute(df1.merge(df2, on="col1", how="left", suffixes=("left_", None), sort=False))
  File ".../modin/pandas/dataframe.py", line 1167, in merge
    validate=validate,
  File ".../modin/experimental/backends/omnisci/query_compiler.py", line 46, in method_wrapper
    return method(self, *args, **kwargs)
  File ".../modin/experimental/backends/omnisci/query_compiler.py", line 158, in merge
    suffixes=suffixes,
  File ".../modin/experimental/engines/omnisci_on_ray/frame/data.py", line 563, in join
    new_columns.append(c + suffix)
TypeError: can only concatenate str (not "NoneType") to str

```

Pandas docs says: `pass a value of None instead of a string to indicate that the column name from left or right should be left as-is, with no suffix. At least one of the values must not be None.`

**Comment by AndreyPavlenko** [comment]
Closing as not reproducible. If you could reproduce the issue, please reopen.
