### ISSUE TITLE
[OmniSci] NotImplementedError appears when using merge operation on index

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3071]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): e4fa1409d6ee048dcdcafc092a10bdc90d965303
- **Python version**: 3.7.10
- **Code we can use to reproduce**:

```python
import numpy as np
from modin.pandas import DataFrame

df1 = DataFrame(np.random.randint(10**6, size=(500000, 64)), columns=[f"col{x}" for x in range(64)])
df2 = DataFrame(np.random.randint(10**6, size=(500000, 64)), columns=[f"col{x}" for x in range(64)])

df1.merge(df2, how="inner",left_index=True, right_index=True)._query_compiler._modin_frame._execute()
```

### Source code / logs

```python
Traceback (most recent call last):
    df1.merge(df2, how="inner",left_index=True, right_index=True)
  File ".../modin/pandas/dataframe.py", line 1151, in merge
    right, how=how, lsuffix=suffixes[0], rsuffix=suffixes[1], sort=sort
  File ".../modin/pandas/dataframe.py", line 1076, in join
    1, [obj._query_compiler for obj in other], join=how, sort=sort
  File ".../modin/experimental/backends/omnisci/query_compiler.py", line 46, in method_wrapper
    return method(self, *args, **kwargs)
  File ".../modin/experimental/backends/omnisci/query_compiler.py", line 395, in concat
    axis, other_modin_frames, join=join, sort=sort, ignore_index=ignore_index
  File ".../modin/experimental/engines/omnisci_on_ray/frame/data.py", line 689, in _concat
    raise NotImplementedError("concat requiring join is not supported yet")
NotImplementedError: concat requiring join is not supported yet

```

**Comment by anmyachev** [comment]
duplicate of #3042, sorry
