### ISSUE TITLE
OmniSci engine can't drop rows from dataframe 

### ISSUE THREAD

**Issue by anmyachev** [modin-project/modin#3077]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version** (`modin.__version__`): e4fa1409d6ee048dcdcafc092a10bdc90d965303
- **Python version**: 3.7.10
- **Code we can use to reproduce**:

```python
import numpy as np
import modin.pandas as pd

df1 = pd.DataFrame(np.random.randint(10**6, size=(10_000, 10)), columns=[f"col{x}" for x in range(10)])

labels = df1.axes[0][:10]
print(df1.drop(labels, axis=0))
```

### Source code / logs

```python
Traceback (most recent call last):
  File "benchmarks/test.py", line 10, in <module>
    print(df1.drop(labels, axis=0))
  File "modin/pandas/base.py", line 1088, in drop
    index=axes["index"], columns=axes["columns"]
  File "modin/experimental/backends/omnisci/query_compiler.py", line 46, in method_wrapper
    return method(self, *args, **kwargs)
  File "modin/experimental/backends/omnisci/query_compiler.py", line 409, in drop
    assert index is None, "Only column drop is supported"
AssertionError: Only column drop is supported

```

**Comment by RehanSD** [comment]
Hi @anmyachev! I'm converting this to a feature request, since it seems this is a new feature that has to be implemented!

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
