### ISSUE TITLE
`read_csv` with OmniSci backend doesn't handle duplicated columns

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3080]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: 563f26d031d3b50b02d1b7a1540dc11a009350cc
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_STORAGE_FORMAT"] = "hdk"

import modin.pandas as pd

test_filename = "test_csv.csv"

data = "col,col,col,col\n5, 6, 7, 8\n9, 10, 11, 12\n"


try:
    with open(test_filename, "w") as f:
        f.write(data)

    df_modin = pd.read_csv(test_filename)
    print(df_modin)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
Traceback (most recent call last):
  File "test.py", line 487, in <module>
    print(df_modin)
  File "/modin/modin/pandas/base.py", line 2804, in __str__
    return repr(self)
  File "/modin/modin/pandas/dataframe.py", line 183, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/modin/modin/pandas/base.py", line 202, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()
  File "/modin/modin/pandas/indexing.py", line 730, in __getitem__
    result = super(_iLocIndexer, self).__getitem__(row_lookup, col_lookup, ndim)
  File "/modin/modin/pandas/indexing.py", line 276, in __getitem__
    qc_view = self.qc.view(row_lookup, col_lookup)
  File "/modin/modin/experimental/backends/omnisci/query_compiler.py", line 46, in method_wrapper
    return method(self, *args, **kwargs)
  File "/modin/modin/experimental/backends/omnisci/query_compiler.py", line 166, in view
    self._modin_frame.mask(row_numeric_idx=index, col_numeric_idx=columns)
  File "/modin/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 181, in mask
    force_execution_mode=self._force_execution_mode,
  File "/modin/modin/experimental/engines/omnisci_on_ray/frame/data.py", line 98, in __init__
    ), f"unaligned dtypes ({dtypes}) and table columns ({self._table_cols})"
AssertionError: unaligned dtypes ([col    int64
col    int64
col    int64
col    int64
dtype: object]) and table columns (['col', 'col', 'col', 'col'])
```

**Comment by RehanSD** [comment]
Hi @amyskov! Is this issue still present on master?

**Comment by Garra1980** [comment]
@AndreyPavlenko please check this one

**Comment by AndreyPavlenko** [comment]
The issue is reproducible. Probably, #4896 should be extended to cover this issue.
