### ISSUE TITLE
`read_csv` with OmniSci backend and `skip_blank_lines` parameter works incorrectly

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3084]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: b1c6e75f4c8442195e8551b561ba62479cac75c4
- **Python version**: 3.7.10
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_EXPERIMENTAL"] = "True"
os.environ["MODIN_STORAGE_FORMAT"] = "hdk"

import modin.pandas as pd
from modin.pandas.test.utils import df_equals

import pandas

test_filename = "test_csv.csv"

data = """col1,col2,col3,col4,col5,col6
50,2000-01-01,50,05:00:00,qHCfaAldpZ,5794.818569288046

"""

kwargs = {"skip_blank_lines": False}

try:
    with open(test_filename, "w") as f:
        f.write(data)

    df_modin = pd.read_csv(test_filename, **kwargs)
    df_pandas = pandas.read_csv(test_filename, **kwargs)

    df_equals(df_pandas, df_modin)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
Traceback (most recent call last):
  File "test.py", line 538, in <module>
    df_equals(df_pandas, df_modin)
  File "/modin/modin/pandas/test/utils.py", line 534, in df_equals
    check_categorical=False,
  File "/miniconda3/envs/modin_on_omnisci/lib/python3.7/site-packages/pandas/_testing.py", line 1716, in assert_frame_equal
    atol=atol,
  File "/miniconda3/envs/modin_on_omnisci/lib/python3.7/site-packages/pandas/_testing.py", line 1484, in assert_series_equal
    index_values=np.asarray(left.index),
  File "pandas/_libs/testing.pyx", line 46, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 161, in pandas._libs.testing.assert_almost_equal
  File "/miniconda3/envs/modin_on_omnisci/lib/python3.7/site-packages/pandas/_testing.py", line 1073, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 1] (column name="col2") are different

DataFrame.iloc[:, 1] (column name="col2") values are different (50.0 %)
[index]: [0, 1]
[left]:  [2000-01-01, nan]
[right]: [2000-01-01, ]
```

**Comment by anmyachev** [comment]
Problem fixed.
