### ISSUE TITLE
modin/pandas/test/test_io.py::TestCsv::test_read_csv_compression tests fail with numpy>1.20.3

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3182]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04.1 LTS

- **Modin version** (`modin.__version__`):

0.10.0+6.gf9c99c38

- **Python version**:

Python 3.8.6

- **Code we can use to reproduce**:

Update numpy to the latest version (currently 1.21.0) and run modin/pandas/test/test_io.py::TestCsv::test_read_csv_compression tests. When they are ran together, tests with python engine fail with exception.

```
Traceback (most recent call last):
  File "/localdisk/gashiman/modin/modin/pandas/test/utils.py", line 668, in execute_callable
    pd_result = fn(pandas_df, **pd_kwargs)
  File "/localdisk/gashiman/modin/modin/pandas/test/utils.py", line 756, in applyier
    result = getattr(module, fn_name)(*args, **kwargs)
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 2502, in read
    data = self._convert_data(data)
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 2582, in _convert_data
    return self._convert_to_ndarrays(
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 1704, in _convert_to_ndarrays
    cvals, na_count = self._infer_types(
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/io/parsers.py", line 1765, in _infer_types
    na_count = isna(result).sum()
  File "/localdisk/gashiman/miniconda3/envs/modin/lib/python3.8/site-packages/numpy/core/_methods.py", line 48, in _sum
    return umr_sum(a, axis, dtype, out, keepdims, initial, where)
TypeError: int() argument must be a string, a bytes-like object or a number, not '_NoValueType'
```

**Comment by gshimansky** [comment]
Reopened because we want to find out why new version of numpy doesn't work.
