### ISSUE TITLE
`DataFrame.apply` doesn't work with dictionary functions

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3221]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version** (`modin.__version__`): 027e1fba53286bf8b7ceccd11b8c6d04ff5b9ab3
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import modin.pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
print(df.apply({"a": "sum"}))
```

<details><summary>Output</summary>

```
Traceback (most recent call last):
  File "repr2.py", line 4, in <module>
    print(df.apply({"a": "sum"}))
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/dataframe.py", line 360, in apply
    func, axis=axis, raw=raw, result_type=result_type, args=args, **kwds
  File "/localdisk/dchigare/repos/modin_bp/modin/pandas/base.py", line 817, in apply
    **kwds,
  File "/localdisk/dchigare/repos/modin_bp/modin/backends/pandas/query_compiler.py", line 2345, in apply
    return self._dict_func(func, axis, *args, **kwargs)
  File "/localdisk/dchigare/repos/modin_bp/modin/backends/pandas/query_compiler.py", line 2414, in _dict_func
    axis, dict_apply_builder, func, keep_remaining=False
  File "/localdisk/dchigare/repos/modin_bp/modin/engines/base/frame/data.py", line 1464, in apply_full_axis_select_indices
    return self.__constructor__(new_partitions, new_index, new_columns, None, None)
  File "/localdisk/dchigare/repos/modin_bp/modin/engines/base/frame/data.py", line 80, in __init__
    self._index_cache = ensure_index(index)
  File "/localdisk/dchigare/miniconda3/envs/modin_tests/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5918, in ensure_index
    return Index(index_like)
  File "/localdisk/dchigare/miniconda3/envs/modin_tests/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 372, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, None was passed

```

</details>

### Describe the problem
Modin implementation raises an exception when the applied function is a dictionary

**Comment by mvashishtha** [comment]
I no longer get the error in the original post by @dchigarev. The error as of version bd326f1c4175102489f08d271a53cf374bd9125e is in #4828.
