### ISSUE TITLE
GroupBy and Agg Breaking with Multiple Parameters 

### ISSUE THREAD

**Issue by aunell1** [modin-project/modin#3262]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
- **Modin version** (`modin.__version__`): 0.9.1
- **Python version**: 3.7.9 Intel Corporation
- **Code we can use to reproduce**: please contact alyssa.unell@intel.com for more information on the code and the dataset

te = gf.iloc[px].groupby(col)[tar].agg(['mean','count'])

### Describe the problem
When using the agg command on a SeriesGroupBy object, an error occurs regarding a key error for the columns, even though the column name matches this key error. When only one command is passed in as a parameter to agg instead of a list of parameters, this discrepancy doesn't occur.

### Source code / logs
Please contact alyssa.unell@intel.com for more information on the code and dataset.

Traceback (most recent call last):
  File "deeplearning/RecSys2020/02_ModelsCompetition/XGBoost1/1-reply-build-TE.py", line 369, in <module>
    train[fname] = MultiTE_gpu( train, c, t, 20, 0 )
  File "deeplearning/RecSys2020/02_ModelsCompetition/XGBoost1/1-reply-build-TE.py", line 265, in MultiTE_gpu
    te = gf.iloc[px].groupby(col)[tar].agg(['mean','count'])
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/groupby.py", line 394, in aggregate
    **kwargs,
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/groupby.py", line 980, in _default_to_pandas
    return self._df._default_to_pandas(groupby_on_multiple_columns, *args, **kwargs)
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/base.py", line 400, in _default_to_pandas
    result = op(pandas_obj, *args, **kwargs)
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/groupby.py", line 974, in groupby_on_multiple_columns
    by=by, axis=self._axis, squeeze=self._squeeze, **self._kwargs
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/pandas/core/frame.py", line 6727, in groupby
    dropna=dropna,
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 568, in __init__
    dropna=self.dropna,
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 811, in get_grouper
    raise KeyError(gpr)
KeyError: 'b_user_id'

**Comment by YarShev** [comment]
This should be related to #3252. @dchigarev , take a look, please.

**Comment by Garra1980** [comment]
Closing as dup of #3252
