### ISSUE TITLE
Incorrect `read_csv` output type with heterogeneous data

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#3278]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: d03ed30
- **Python version**: 3.8.10
- **Code we can use to reproduce**:
```
from io import StringIO
import os
import pandas
from modin.config import NPartitions
from modin.pandas.test.utils import df_equals

NPartitions.put(2)

import modin.pandas as pd

test_filename = "test.csv"
data = """col1,col2
1,2
3,4

5,6
7,8
"""
kwargs = {
    "header": None,
    "skip_blank_lines": False,
    # "dtype": "str", # workaround
}


try :
    with open(test_filename, "w") as f:
        f.write(data)
    
    pandas_df = pandas.read_csv(test_filename, **kwargs)
    pd_df = pd.read_csv(test_filename, **kwargs)
    print(pandas_df.iloc[1, 0], type(pandas_df.iloc[1, 0])) # 1 <class 'str'>
    print(pandas_df.iloc[4, 0], type(pandas_df.iloc[4, 0])) # 5 <class 'str'>
    print(pd_df.iloc[1, 0], type(pd_df.iloc[1, 0])) # 1st partition: 1 <class 'str'>
    print(pd_df.iloc[4, 0], type(pd_df.iloc[4, 0])) # 2nd partition: 5.0 <class 'numpy.float64'>

    df_equals(pandas_df, pd_df)

finally:
    os.remove(test_filename)
```

### Describe the problem

Modin `read_csv` can output incorrect data type during reading heterogeneous data.

### Source code / logs

```
1 <class 'str'>
5 <class 'str'>
1 <class 'str'>
5.0 <class 'numpy.float64'>
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    df_equals(pandas_df, pd_df)
  File "modin/modin/pandas/test/utils.py", line 527, in df_equals
    assert_frame_equal(
  File "miniconda3/envs/modin/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1308, in assert_frame_equal
    assert_series_equal(
  File "miniconda3/envs/modin/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1077, in assert_series_equal
    _testing.assert_almost_equal(
  File "pandas/_libs/testing.pyx", line 53, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 168, in pandas._libs.testing.assert_almost_equal
  File "miniconda3/envs/modin/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 665, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 0] (column name="0") are different

DataFrame.iloc[:, 0] (column name="0") values are different (50.0 %)
[index]: [0, 1, 2, 3, 4, 5]
[left]:  [col1, 1, 3, nan, 5, 7]
[right]: [col1, 1, 3.0, nan, 5.0, 7.0]
```

**Comment by amyskov** [comment]
Also can be related to https://github.com/modin-project/modin/issues/2845.

**Comment by RehanSD** [comment]
Confirmed that this is reproducible on master!
