### ISSUE TITLE
OOM on Dataframe.apply

### ISSUE THREAD

**Issue by RAbraham** [modin-project/modin#3287]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 18.04)**:
- **Modin version** (`modin.__version__`): 0.10.1
- **Ray**: 1.4.1, 1.5.0*
- **Python version**: 3.7
- **Code we can use to reproduce**:
```python
import modin.pandas as pd
import numpy as np
import ray
ray.init(num_cpus=4)
frame_data = np.random.randint(0, 100, size=(2**20, 2**8)) # 2GB each
df = pd.DataFrame(frame_data).add_prefix("col")
big_df = pd.concat([df for _ in range(1000)]) # 1000x2GB frames. You can try with lower numbers too here. 
print(big_df)

def function(row):
    col0 = row["col0"]
    col1 = row["col1"]
    col2 = row["col2"]
    data = ["a" for _ in range(100000)]
    row["row1"] = data
    row["row2"] = data
    row["row3"] = data
    return row

big_df = big_df.apply(function, axis=1)
print("Done")
#
```

### Describe the problem
Based on this dicussion(https://discuss.modin.org/t/alternative-to-dataframe-apply-func-for-accessing-multiple-columns-as-input-without-oom-error/220/5), using `apply` on a dataframe results in an OOM.

Error Message:
Note. In real code, I see more than the below messages. See for e.g. (https://discuss.modin.org/t/alternative-to-dataframe-apply-func-for-accessing-multiple-columns-as-input-without-oom-error/220/4?u=rabraham) 
```


UserWarning: User-defined function verification is still under development in Modin. The function provided is not verified.
2021-07-26 20:52:21,183 WARNING worker.py:1123 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/rajiv/Documents/dev/bht/layoutlm/venv/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/home/rajiv/Documents/dev/bht/layoutlm/venv/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 207, in _run
    self.update_load_metrics()
  File "/home/rajiv/Documents/dev/bht/layoutlm/venv/lib/python3.8/site-packages/ray/autoscaler/_private/monitor.py", line 169, in update_load_metrics
    response = self.gcs_node_resources_stub.GetAllResourceUsage(
  File "/home/rajiv/Documents/dev/bht/layoutlm/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/rajiv/Documents/dev/bht/layoutlm/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
  status = StatusCode.DEADLINE_EXCEEDED
  details = "Deadline Exceeded"
  debug_error_string = "{"created":"@1627347120.438788430","description":"Error received from peer ipv4:172.27.246.178:39423","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>

2021-07-26 21:22:57,346 WARNING worker.py:1123 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. Task ID: 27c0dca5954f99afffffffffffffffffffffffff01000000 Worker ID: 0cf55fb2b9832592acdcd6810ee8183080bc6f334a3324b361905355 Node ID: d669dac450d8edb8cc84e8af0e4f9297a3c198bcfea797d0cefefc07 Worker IP address: 172.27.246.178 Worker port: 35157 Worker PID: 972216
2021-07-26 21:42:12,143 WARNING worker.py:1123 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. Task ID: 139e431dd460af76ffffffffffffffffffffffff01000000 Worker ID: d02b174ea614b73d9feb789fafc93bf5ce6589cad8c366d0f428b04c Node ID: d669dac450d8edb8cc84e8af0e4f9297a3c198bcfea797d0cefefc07 Worker IP address: 172.27.246.178 Worker port: 33371 Worker PID: 972215

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Additional:
* Testing for OOM crashed my server and it's taking some time to come back. For Ray 1.5.0, therefor I tested on my laptop and saw it rising until I stopped it at 29.2 G(max memory 31.1G) to avoid crashing my laptop

**Comment by RehanSD** [comment]
Hi @RAbraham! I'm marking this issue as resolved since it hasn't been updated recently! If you have any further questions, please feel free to reopen this issue, or open a new one!
