### ISSUE TITLE
Dataframe shift breaks with Modin distribution but not stock pandas

### ISSUE THREAD

**Issue by aunell1** [modin-project/modin#3292]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`): 0.10.1
- **Python version**: 3.7.9
- **Code we can use to reproduce**:
-  contact alyssa.unell@intel.com for information regarding the code and dataset

### Describe the problem
Shifting of a dataframe using modin distribution breaks

### Source code / logs
UserWarning: Distributing <class 'NoneType'> object. This may take some time.
Traceback (most recent call last):
  File "deeplearning/RecSys2020/02_ModelsCompetition/XGBoost2/sub040_1_save_public.py", line 731, in <module>
    add_timeshift(train, test, shift=1)
  File "deeplearning/RecSys2020/02_ModelsCompetition/XGBoost2/sub040_1_save_public.py", line 339, in add_timeshift
    gf["b_user_id_shifted"] = gf["b_user_id"].shift(periods=shift)
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/series.py", line 1361, in shift
    periods=periods, freq=freq, axis=axis, fill_value=fill_value
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/base.py", line 2319, in shift
    new_frame.index = self.index.copy()
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/pandas/base.py", line 562, in _set_index
    self._query_compiler.index = new_index
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/backends/pandas/query_compiler.py", line 91, in set_axis
    self._modin_frame.index = idx
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/engines/base/frame/data.py", line 250, in _set_index
    new_index = self._validate_set_axis(new_index, self._index_cache)
  File "/localdisk/alyssa/anaconda3/envs/aikit-modin/lib/python3.7/site-packages/modin/engines/base/frame/data.py", line 212, in _validate_set_axis
    "new values have %d elements" % (old_len, new_len)
ValueError: Length mismatch: Expected axis has 199999 elements, new values have 200000 elements

**Comment by prutskov** [comment]
The issue is occurred in case `index` has duplicates. Reproducer:

```python
from pandas.core.arrays.sparse import dtype
from modin.distributed.dataframe.pandas.partitions import unwrap_partitions
import ray
import modin.pandas as pd
ray.init()

ser = pd.DataFrame([0,1,2,3,], index=[0,1,2,0])
print(ser.shift(periods=-1))
```
Traceback:
```bash
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(ser.shift(periods=-1))
  File "/localdisk/aprutsko/modin/modin/pandas/base.py", line 2349, in shift
    new_frame.index = self.index.copy()
  File "/localdisk/aprutsko/modin/modin/pandas/dataframe.py", line 2487, in __setattr__
    object.__setattr__(self, key, value)
  File "/localdisk/aprutsko/modin/modin/pandas/base.py", line 562, in _set_index
    self._query_compiler.index = new_index
  File "/localdisk/aprutsko/modin/modin/backends/pandas/query_compiler.py", line 91, in set_axis
    self._modin_frame.index = idx
  File "/localdisk/aprutsko/modin/modin/engines/base/frame/data.py", line 250, in _set_index
    new_index = self._validate_set_axis(new_index, self._index_cache)
  File "/localdisk/aprutsko/modin/modin/engines/base/frame/data.py", line 210, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 3 elements, new values have 4 elements
```
