### ISSUE TITLE
Error `EOFError: stream has been closed` in `"modin in the cloud"` mode

### ISSUE THREAD

**Issue by Lozovskii-Aleksandr** [modin-project/modin#3329]
### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 0.10.1
- **Python version**: 3.8.11
- **Code we can use to reproduce**:

To get an error:

1. Open the file `modin/pandas/test/test_io.py`;
2. Find the test `TestCsv::test_read_csv_squeeze`;
3. Remove `xfail` for `--simulate-cloud`
4. Run the test with the command:

   ```shell
   set MODIN_EXPERIMENTAL=1
   set MODIN_ENGINE=Python
   python -m pytest --simulate-cloud=normal modin/pandas/test/test_io.py::TestCsv::test_read_csv_squeeze
   ```

### Describe the problem

If you disable `xfail` for the `test_read_csv_squeeze` test and run the `test_io` file in the `"modin in the cloud"` mode, we get the error `EOFError: stream has been closed`. Moreover, this error will be not only for this test, but also for all tests that come after it. In other words, before executing this test, all tests will work correctly, and after this test fails, all tests will stop working correctly and will give the error `EOFError: stream has been closed`.

### Source code / logs

Here are some logs that are obtained in different ways.

<details>
<summary>Pytest log:</summary>

   ```py
   self = <rpyc.core.stream.ClosedFile object at 0x000001F127B4C900>, name = 'send'

       def __getattr__(self, name):
           if name.startswith("__"):  # issue 71
               raise AttributeError("stream has been closed")
   >       raise EOFError("stream has been closed")
   E       EOFError: stream has been closed

   C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\stream.py:94: EOFError
   ```

</details>

The following logs can be obtained by setting the environment variable `MODIN_LOG_RPYC`. Then the command to run this test will be as follows:

   ```shell
   set MODIN_EXPERIMENTAL=1
   set MODIN_ENGINE=Python
   set MODIN_LOG_RPYC=1
   python -m pytest --simulate-cloud=normal modin/pandas/test/test_io.py::TestCsv::test_read_csv_squeeze
   ```

When setting this variable, the files `rpyc.log` and `rpyc.out` will be created. These files can be found in the temp folder. For Windows 10, you can find them if you open File Explorer and enter `%temp%` in the address field. This folder will contain the files `rpyc.log` and `rpyc.out`.

<details>
<summary>rpyc.log:</summary>

   ```shell
   DEBUG:SLAVE/18813:Exception caught
   Traceback (most recent call last):
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
       res = self._HANDLERS[handler](self, *args)
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 609, in _handle_getattr
       return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 537, in _access_attr
       return accessor(obj, name, *args)
   AttributeError: 'numpy.ndarray' object has no attribute '_typ'
   ```

</details>

<details>
<summary>rpyc.out:</summary>

During an error, an infinite recursion occurs.

   ```shell
   Traceback (most recent call last):
     File "C:\prog\modin\modin\pandas\dataframe.py", line 2460, in __getattr__
       return object.__getattribute__(self, key)
     File "C:\prog\modin\modin\pandas\dataframe.py", line 251, in _get_columns
       return self._query_compiler.columns
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\generic.py", line 5478, in __getattr__
       return object.__getattribute__(self, name)
   AttributeError: 'Series' object has no attribute 'columns'

   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 320, in _dispatch_request
       res = self._HANDLERS[handler](self, *args)
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\rpyc\core\protocol.py", line 593, in _handle_call
       return obj(*args, **dict(kwargs))
     File "C:\prog\modin\modin\pandas\dataframe.py", line 209, in __repr__
       result = repr(self._build_repr_df(num_rows, num_cols))
     File "C:\prog\modin\modin\pandas\base.py", line 154, in _build_repr_df
       columns=self.columns if hasattr(self, "columns") else None,
     File "C:\prog\modin\modin\pandas\dataframe.py", line 2462, in __getattr__
       if key not in _ATTRS_NO_LOOKUP and key in self.columns:
     File "C:\prog\modin\modin\pandas\dataframe.py", line 2462, in __getattr__
       if key not in _ATTRS_NO_LOOKUP and key in self.columns:
     File "C:\prog\modin\modin\pandas\dataframe.py", line 2462, in __getattr__
       if key not in _ATTRS_NO_LOOKUP and key in self.columns:
     [Previous line repeated 973 more times]
     File "C:\prog\modin\modin\pandas\base.py", line 3036, in __getattribute__
       attr = super().__getattribute__(item)
     File "C:\prog\modin\modin\pandas\dataframe.py", line 251, in _get_columns
       return self._query_compiler.columns
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\generic.py", line 5475, in __getattr__
       and self._info_axis._can_hold_identifiers_and_holds_name(name)
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\indexes\base.py", line 4648, in _can_hold_identifiers_and_holds_name
       if self.is_object() or self.is_categorical():
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\indexes\base.py", line 2257, in is_object
       return is_object_dtype(self.dtype)
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\common.py", line 187, in is_object_dtype
       return _is_dtype_type(arr_or_dtype, classes(np.object_))
     File "C:\Users\alozovsk\Anaconda3\envs\modin\lib\site-packages\pandas\core\dtypes\common.py", line 1596, in _is_dtype_type
       if isinstance(arr_or_dtype, np.dtype):
   RecursionError: maximum recursion depth exceeded while calling a Python object
   ```

</details>

**Comment by anmyachev** [comment]
Not relevant due to https://github.com/modin-project/modin/pull/6408
