### ISSUE TITLE
`slice_shift` creates a copy of DataFrame/Series instead of view

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3358]
### Describe the problem

```python
import ray
import modin.pandas as pd
import pandas

from modin.pandas.test.utils import df_equals
ray.init()

data = [0,1,2,3,]

pd_df = pandas.DataFrame(data)
md_df = pd.DataFrame(data)

pd_df2 = pd_df.slice_shift()
md_df2 = md_df.slice_shift()

pd_df.iloc[0, 0] = 777
md_df.iloc[0, 0] = 777

df_equals(pd_df2, md_df2)
```
Output
```bash
FutureWarning: The 'slice_shift' method is deprecated and will be removed in a future version. You can use DataFrame/Series.shift instead
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    df_equals(pd_df2, md_df2)
  File "/localdisk/aprutsko/modin/modin/pandas/test/utils.py", line 527, in df_equals
    assert_frame_equal(
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1308, in assert_frame_equal
    assert_series_equal(
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1077, in assert_series_equal
    _testing.assert_almost_equal(
  File "pandas/_libs/testing.pyx", line 53, in pandas._libs.testing.assert_almost_equal
  File "pandas/_libs/testing.pyx", line 168, in pandas._libs.testing.assert_almost_equal
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 665, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 0] (column name="0") are different

DataFrame.iloc[:, 0] (column name="0") values are different (33.33333 %)
[index]: [1, 2, 3]
[left]:  [777, 1, 2]
[right]: [0, 1, 2]
```

**Comment by Tanu1201** [comment]
Can I work upon on this issue?

**Comment by mvashishtha** [comment]
See also related #4650. It's quite hard to reproduce copy semantics with Modin dataframes.
