### ISSUE TITLE
read parquet file in custom S3 file system

### ISSUE THREAD

**Issue by raphaelauv** [modin-project/modin#3383]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 20.04.3
- **Modin version** (`modin.__version__`): 0.10.2
- **Python version**:  python 3.8.10
- **Code we can use to reproduce**:

```python
import pandas as pd
dict_ecs = {'client_kwargs': {'endpoint_url': 'http://localhost:4566'}}

df = pd.read_parquet(path=bucket_uri, storage_options=dict_ecs)
print(df.head())
```

work correctly ( the bucket is on public read , no need to give credentials )

but

```python
os.environ["MODIN_ENGINE"] = "ray"
import modin.pandas as pd

dict_ecs = {'client_kwargs': {'endpoint_url': 'http://localhost:4566'}}

df = pd.read_parquet(path=bucket_uri, storage_options=dict_ecs)
print(df.head())
```

throw an error
```
PermissionError: The AWS Access Key Id you provided does not exist in our records.
```

### Source code / logs

```
Traceback (most recent call last):
  File "/home/raphael/REPO/test/project/toto.py", line 50, in <module>
    read_modin()
  File "/home/raphael/REPO/test/project/toto.py", line 25, in read_modin
    df = pd.read_parquet(path=bucket_uri, storage_options=dict_ecs)
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/modin/pandas/io.py", line 212, in read_parquet
    query_compiler=FactoryDispatcher.read_parquet(
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/modin/data_management/factories/dispatcher.py", line 167, in read_parquet
    return cls.__factory._read_parquet(**kwargs)
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/modin/data_management/factories/factories.py", line 196, in _read_parquet
    return cls.io_cls.read_parquet(**kwargs)
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/modin/engines/base/io/file_dispatcher.py", line 67, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/modin/engines/base/io/column_stores/parquet_dispatcher.py", line 109, in _read
    pd = ParquetDataset(path, filesystem=fs)
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/pyarrow/parquet.py", line 1332, in __init__
    self.metadata_path) = _make_manifest(
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/pyarrow/parquet.py", line 1559, in _make_manifest
    if _is_path_like(path_or_paths) and fs.isdir(path_or_paths):
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 88, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 69, in sync
    raise result[0]
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/s3fs/core.py", line 1161, in _isdir
    return bool(await self._lsdir(path))
  File "/home/raphael/REPO/test/project/venv/lib/python3.8/site-packages/s3fs/core.py", line 597, in _lsdir
    raise translate_boto_error(e)
PermissionError: The AWS Access Key Id you provided does not exist in our records.
```

**Comment by raphaelauv** [comment]
If I try myself with S3FS it also work

```python
import s3fs
import pyarrow.parquet as pq

fs = s3fs.S3FileSystem(anon=False, client_kwargs={'endpoint_url': 'http://localhost:4566'})
dataset = pq.ParquetDataset(bucket_uri, filesystem=fs)
table = dataset.read()
df = table.to_pandas()
print(df.head())
```

**Comment by devin-petersohn** [comment]
Hi @raphaelauv I think this is the same issue as #2301, which is planned for being fixed in the next release.
