### ISSUE TITLE
Modin XGB failed when `X` and `y` dataframes have unaligned `_row_lengths`

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3394]
### Describe the problem

If case `X` (data) and `y` (label) Modin DataFrames have a different `_row_lengths` the next exception is occurred:

<details><summary>Traceback</summary>

```bash
(modin) nnlmlp01$ python test.py
2021-09-02 09:30:41,369 INFO services.py:1272 -- View the Ray dashboard at http://127.0.0.1:8265
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
2021-09-02 09:30:44,119 WARNING worker.py:1123 -- WARNING: 6 PYTHON workers have been started on a node of the id: 60be9ed829753b4f4e1c2d0aecae7713b5ac3e66234bff681bd9f9c1 and address: 10.125.130.30. This could be a result of using a large number of actors, or it could be a consequence of using nested tasks (see https://github.com/ray-project/ray/issues/3644) for some a discussion of workarounds.
(pid=3637089) [09:30:45] task [modin.xgboost]:1 got new rank 1
(pid=3637090) [09:30:45] task [modin.xgboost]:0 got new rank 0
(pid=3637165) [09:30:45] task [modin.xgboost]:2 got new rank 2
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    model = xgb.train(
  File "/localdisk/aprutsko/modin/modin/experimental/xgboost/xgboost.py", line 192, in train
    result = _train(dtrain, params, *args, num_actors=num_actors, evals=evals, **kwargs)
  File "/localdisk/aprutsko/modin/modin/experimental/xgboost/xgboost_ray.py", line 543, in _train
    result = ray.get(fut[0])
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/ray/worker.py", line 1495, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(XGBoostError): ray::ModinXGBoostActor.train() (pid=3637090, ip=10.125.130.30)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/localdisk/aprutsko/modin/modin/experimental/xgboost/xgboost_ray.py", line 159, in train
    bst = xgb.train(
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/training.py", line 189, in train
    bst = _train_internal(params, dtrain,
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/training.py", line 81, in _train_internal
    bst.update(dtrain, i, obj)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 1499, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/core.py", line 210, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [09:30:45] ../src/data/data.cc:583: Check failed: labels_.Size() == num_row_ (20 vs. 70) : Size of labels must equal to number of rows.
Stack trace:
  [bt] (0) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x9133f) [0x7fa8eaeee33f]
  [bt] (1) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x110fcc) [0x7fa8eaf6dfcc]
  [bt] (2) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x1b90e7) [0x7fa8eb0160e7]
  [bt] (3) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x1b99bc) [0x7fa8eb0169bc]
  [bt] (4) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x50) [0x7fa8eaedded0]
  [bt] (5) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fd7f76e59dd]
  [bt] (6) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7fd7f76e5067]
  [bt] (7) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0xa56) [0x7fd7f76fff96]
  [bt] (8) /localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x1590c) [0x7fd7f770090c]
```
</details>

<details><summary>Script to reproduce</summary>

```python
from sklearn import datasets

import ray
ray.init(num_cpus=2)

import modin.pandas as pd
import modin.experimental.xgboost as xgb
from modin.config.envvars import NPartitions

NPartitions.put(2)
# Load iris dataset from sklearn
iris = datasets.load_iris()

# Create Modin DataFrames
X = pd.DataFrame(iris.data)
y = pd.Series(iris.target)

y_first, y_second  = y.iloc[:20], y.iloc[20:]
y  = pd.concat([y_first, y_second], axis=0)

X_first, X_second  = X.iloc[:70], X.iloc[70:]
X = pd.concat([X_first, X_second], axis=0)

# Create DMatrix
dtrain = xgb.DMatrix(X, y)
dtest = xgb.DMatrix(X, y)

# Set training parameters
xgb_params = {
    "eta": 0.3,
    "max_depth": 3,
    "objective": "multi:softprob",
    "num_class": 3,
    "eval_metric": "mlogloss",
}
steps = 20

# Create dict for evaluation results
evals_result = dict()

# Run training
model = xgb.train(
    xgb_params,
    dtrain,
    steps,
    num_actors=3,
    evals=[(dtrain, "train")],
    evals_result=evals_result
)

# Print evaluation results
print(f'Evals results:\n{evals_result}')

# Predict results
prediction = model.predict(dtest)

# Print prediction results
print(f'Prediction results:\n{prediction}')
```
</details>

**Comment by RehanSD** [comment]
@prutskov has this issue been resolved?
