### ISSUE TITLE
Improved shuffling mechanism for Ray

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#3535]
Currently, we do not have a good general purpose shuffle. Ideally, we would have a mechanism that could split the data based on some split function or based on some features of the data (e.g. the quantiles of the column for numeric data).

**Comment by mvashishtha** [comment]
I have been testing an implementation of a numerical sort (not a general purpose shuffle) using Ray actors on an 800 MB test dataset [here](https://drive.google.com/file/d/1pMm8As4IdR_-PfAeI9ZdIuDpCllO8pF7/view?usp=sharing). You can view my latest script [here](https://github.com/mvashishtha/modin/blob/0a3acc150b0856b858fd90f0afe7b0bcd146579b/sort_non_modin.py). On my Mac (16-inch MacBook Pro, 2019, with MacOS Big Sur 11.5.2, Ray version 1.8.0, Python 3.8.8), I compared three alternatives:

1) The sort script with Ray actors linked above. The sort takes about 253 seconds. 

2) Sorting with Modin by defaulting to Pandas as follows:
```python
import modin.pandas as pd
df = pd.read_csv("test_1mx256.csv")
%time df.sort_values(["col2"])
```

This took 401 seconds.

3) Sorting with Pandas:
```python
import pandas as pd
df = pd.read_csv("test_1mx256.csv")
%time df.sort_values(["col2"])
```
This took 2.58 seconds.

On @devin-petersohn's Windows Machine (Windows 10, Ray 1.7.1, Python 3.8.5), I get:

1) sort script with ray actors: 6.42 seconds
2) Sorting with Modin by defaulting to Pandas: 3.58 seconds
3) Sorting with Pandas: 2.24 seconds

The difference in Modin performance between Mac and Windows is [Ray Issue 20388](https://github.com/ray-project/ray/issues/20388). On Windows, the Actor approach takes about 3x as long as Pandas. and about 2x as long as Modin with default to Pandas. I don't think my implementation performs well enough to add to Modin. Does anyone have any suggestions on how to improve it? Should we use Ray actors at all?

**Comment by vnlitvinov** [comment]
What would happen if we try to simulate a case of not fitting in a single node? I mean, no defaulting is crucial if you have so much data that it won't fit in any single node, then some distributed logic is needed regardless of performance.

Also how does the scaling work here, what if we take a 10m rows input? A 100m rows?

**Comment by mvashishtha** [comment]
@vnlitvinov, @devin-petersohn is looking into setting up a distributed testing environment. Meanwhile, are you able to test the script with 10m or 100m rows of input? Given how slow it was on my computer on the 1m row file from my previous comment, I don't think I'll be able to test those locally.

**Comment by vnlitvinov** [comment]
I wonder how did you make your input data, could you share a script or other means of generating that?

**Comment by mvashishtha** [comment]
@vnlitvinov Sure, this is how I got the input data:

```python
import numpy as np
import modin.pandas as pd

df = pd.DataFrame(np.random.randint(0, 100, size=(2**20, 2**8))).add_prefix("col")
```

**Comment by anmyachev** [comment]
These results can be misleading, since the current Modin implementation (in big datasets) is faster than pure pandas, although message about defaulting to pandas appears. However, internally only sorting of the pandas is used, the `reindex` operation is performed by Modin itself. Shouldn't we stop showing the message?

### Results
<details>
<summary>Comparison of `sort_values` implementations (all times in seconds)</summary>

![image](https://user-images.githubusercontent.com/45976948/145248357-fed429eb-6e12-4c8d-b30d-1904885aee89.png)
</details>

<details>
<summary>Prototype scalability</summary>

![image](https://user-images.githubusercontent.com/45976948/145248603-dc2ccfa5-66f5-4b4e-b5ec-8fc6b6f9f155.png)
</details>

<details>
<summary>Current Modin implementation</summary>

![image](https://user-images.githubusercontent.com/45976948/145248738-88f1e778-9c79-4b60-adc9-e517ad3468bd.png)
</details>


I couldn't get results for dataset with 100M rows due to out of memory:
<details> <summary>prototype error</summary>

```bash
	2021-12-08 15:57:29,080 WARNING worker.py:1215 -- The actor or task with ID e788aad55c0377b5f52597f2084589fe866a0a2115908deb cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
	Required resources for this actor or task: {CPU: 1.000000}
	Available resources on this node: {0.000000/8.000000 CPU, 551.207606 GiB/551.207606 GiB memory, 186.264515 GiB/186.264515 GiB object_store_memory, 1.000000/1.000000 node:10.125.130.30}
	In total there are 47 pending tasks and 0 pending actors on this node.
	Traceback (most recent call last):
	  File "sort_values_non_modin.py", line 152, in <module>
	    # sorted_dataframe, defaulting_modin, sort_by_pandas
	  File "sort_values_non_modin.py", line 124, in sorted_dataframe
	    ]
	  File "miniconda3/envs/modin/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
	    return func(*args, **kwargs)
	  File "miniconda3/envs/modin/lib/python3.8/site-packages/ray/worker.py", line 1621, in get
	    raise value.as_instanceof_cause()
	ray.exceptions.RayTaskError: ray::ShuffleActor.combine_and_apply_dfs() (pid=2409094, ip=10.125.130.30, repr=<sort_values_non_modin.ShuffleActor object at 0x7f363d90daf0>)
	ray.exceptions.ObjectStoreFullError: Failed to put object 2f41f345ddf68417a8782fa603827f3700652efb0100000001000000 in object store because it is full. Object size is 28017495444 bytes.
	The local object store is full of objects that are still in scope and cannot be evicted. Tip: Use the `ray memory` command to list active objects in the cluster.
```
  </details>
<details><summary>current Modin implementation error</summary>

```bash
	2021-12-08 17:09:11,680 WARNING worker.py:1215 -- Traceback (most recent call last):	
	  File "python/ray/_raylet.pyx", line 723, in ray._raylet.spill_objects_handler
	  File "python/ray/_raylet.pyx", line 726, in ray._raylet.spill_objects_handler
	  File "/miniconda3/envs/modin/lib/python3.8/site-packages/ray/external_storage.py", line 522, in spill_objects
	    return _external_storage.spill_objects(object_refs, owner_addresses)
	  File "miniconda3/envs/modin/lib/python3.8/site-packages/ray/external_storage.py", line 277, in spill_objects
	    return self._write_multiple_objects(f, object_refs,
	  File "miniconda3/envs/modin/lib/python3.8/site-packages/ray/external_storage.py", line 136, in _write_multiple_objects
	    written_bytes = f.write(payload)
	OSError: [Errno 28] No space left on device
	An unexpected internal error occurred while the IO worker was spilling objects: [Errno 28] No space left on device
	SORT_VALUES time: 1492.286622285843
```
</details>
<details> <summary>frequent warnings</summary>

```bash
	Warning
		2021-12-07 23:19:23,395 WARNING worker.py:1215 -- The actor or task with ID ffffffffffffffff66ecd7e592db6fa5e6436cfa01000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
		Required resources for this actor or task: {CPU: 1.000000}
		Available resources on this node: {26.000000/32.000000 CPU, 552.116908 GiB/552.116908 GiB memory, 186.264515 GiB/186.264515 GiB object_store_memory, 1.000000/1.000000 node:10.125.130.30}
		In total there are 256 pending tasks and 26 pending actors on this node.
	Warning
		2021-12-08 14:09:14,445 WARNING worker.py:1215 -- WARNING: 334 PYTHON worker processes have been started on node: a63fead710fca53f131514508b9451e3325860f9f368a4d972114fd3 with address: 10.125.130.30. This could be a result of using a large number of actors, or due to tasks blocked in ray.get() calls (see https://github.com/ray-project/ray/issues/3644 for some discussion of workarounds).
```
</details>

**Comment by anmyachev** [comment]
@RehanSD yes, let me do it

**Comment by anmyachev** [comment]
> > @RehanSD yes, let me do it
> 
> Thank you @anmyachev!

@RehanSD benchmark results in previous comment

**Comment by RehanSD** [comment]
> > > @RehanSD yes, let me do it
> > 
> > 
> > Thank you @anmyachev!
> 
> @RehanSD benchmark results in previous comment

Thank you @anmyachev - what size of data were you using for these numbers?

**Comment by anmyachev** [comment]
> > > > @RehanSD yes, let me do it
> > > 
> > > 
> > > Thank you @anmyachev!
> > 
> > 
> > @RehanSD benchmark results in previous comment
> 
> Thank you @anmyachev - what size of data were you using for these numbers?

df with shape: 1M rows x 256 cols  (created by `pd.DataFrame(np.random.standard_cauchy((1000000, 256)))`)
