### ISSUE TITLE
FEAT: Add support of s3 buckets for `read_excel`

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3565]
### System information
- **Modin installed from (source or binary)**: source
- **Modin version**: 01a5de21c8fb3f6da0f9f887f6a659b7037136a0
- **Python version**: 3.8
- **Exact command to reproduce**:

```python
import modin.pandas as pd

df = pd.read_excel("s3://modin-datasets/testing/test_data.xlsx")
print(df) 
```

### Log

```bash
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    df = pd.read_excel("s3://modin-datasets/testing/test_data.xlsx")
  File "/localdisk/aprutsko/modin/modin/pandas/io.py", line 347, in read_excel
    intermediate = FactoryDispatcher.read_excel(**kwargs)
  File "/localdisk/aprutsko/modin/modin/core/execution/dispatching/factories/dispatcher.py", line 215, in read_excel
    return cls.__factory._read_excel(**kwargs)
  File "/localdisk/aprutsko/modin/modin/core/execution/dispatching/factories/factories.py", line 256, in _read_excel
    return cls.io_cls.read_excel(**kwargs)
  File "/localdisk/aprutsko/modin/modin/core/io/file_dispatcher.py", line 143, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/localdisk/aprutsko/modin/modin/core/io/text/excel_dispatcher.py", line 118, in _read
    with ZipFile(io) as z:
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 's3://modin-datasets/testing/test_data.xlsx'
```

### Describe the problem

`modin.pandas.read_excel` doesn't work with s3-like paths due to specific files handling. Future implementation should support `storage_options` parameter.

Possible solution is using of https://github.com/modin-project/modin/blob/01a5de21c8fb3f6da0f9f887f6a659b7037136a0/modin/core/io/file_dispatcher.py#L31 but need to keep in mind https://github.com/modin-project/modin/blob/01a5de21c8fb3f6da0f9f887f6a659b7037136a0/modin/core/io/text/excel_dispatcher.py#L84-L99

**Comment by RehanSD** [comment]
Confirmed that this is reproducible on master!
