### ISSUE TITLE
Taxi example is broken for modin-omnisci

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#3637]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 21.10

- **Modin version** (`modin.__version__`):

0.11.1+35.ge995bfac.dirty

- **Python version**:

21.10

- **Code we can use to reproduce**:

### Describe the problem

Taxi example for omnisci no longer works. This line https://github.com/modin-project/modin/blob/master/examples/docker/modin-omnisci/nyc-taxi-omnisci.py#L147 triggers an exception:

```
Traceback (most recent call last):
  File "/home/gregory/work/modin/examples/docker/modin-omnisci/nyc-taxi-omnisci.py", line 209, in <module>
    main()
  File "/home/gregory/work/modin/examples/docker/modin-omnisci/nyc-taxi-omnisci.py", line 201, in main
    df = measure("Reading", read, sys.argv[1])
  File "/home/gregory/work/modin/examples/docker/modin-omnisci/nyc-taxi-omnisci.py", line 189, in measure
    res = func(*args, **kw)
  File "/home/gregory/work/modin/examples/docker/modin-omnisci/nyc-taxi-omnisci.py", line 147, in read
    ].frame_id = OmnisciServer().put_arrow_to_omnisci(
  File "/home/gregory/work/modin/modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py", line 211, in put_arrow_to_omnisci
    table = cls.cast_to_compatible_types(table)
  File "/home/gregory/work/modin/modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py", line 150, in cast_to_compatible_types
    schema = table.schema
  File "/home/gregory/work/miniconda3/envs/modin-conda/lib/python3.9/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'schema'
```

**Comment by ienkovich** [comment]
This error happens when this test is run with no proper env vars set to use omnisci_on_native.

**Comment by anmyachev** [comment]
@ienkovich most likely problem is that `get` returns `pandas_df` instead of `pyarrow.Table` https://github.com/modin-project/modin/blob/ac8e2d18826ebe7666bfd3c48fd0489b6b0426ea/modin/experimental/engines/omnisci_on_native/frame/partition.py#L90

@YarShev can you take a look?

**Comment by ienkovich** [comment]
> @ienkovich most likely problem is that `get` returns `pandas_df` instead of `pyarrow.Table`
> 

IIRC this might happen only when a frame has unsupported data.

**Comment by Garra1980** [comment]
I’m wondering when it began to fail

**Comment by YarShev** [comment]
I ran the example on our NN machine and it worked fine with current master. Did you try setting `MODIN_EXPERIMENTAL=true MODIN_STORAGE_FORMAT=omnisci MODIN_ENGINE=native`?

**Comment by ienkovich** [comment]
I can run this test OK as well. Guess Docker was broken by 
```
commit b37bcf8796dff452562b48704fae1ea60a297ece
Author: Devin Petersohn <devin-petersohn@users.noreply.github.com>
Date:   Wed Oct 13 06:05:04 2021 -0500

    REFACTOR-#2957: Restructure project files (#3210)

    Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>
    Co-authored-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>
    Co-authored-by: Myachev <anatoly.myachev@intel.com>
```
because of new env var names. But it was later fixed by
```
commit 7a8158873e77cb5f1a5a3b89be4ddac89f576269
Author: Yaroslav Igoshev <yaroslav.igoshev@intel.com>
Date:   Wed Oct 27 15:06:51 2021 +0300

    FIX-#3412: Correct the stuff in the code to be in line with the project structure (#3537)
```

**Comment by anmyachev** [comment]
ok, I see. `modin-omnisci==0.11.2` package still contains the old name of env variable: `MODIN_BACKEND`, this dockerfile should work after new Modin release, and since it is possible today, nothing needs to be done.

**Comment by sign60intel** [comment]
when I open commented lines in rerpo from https://github.com/modin-project/modin/issues/3533
```
def main():
    if len(sys.argv) != 2:
        print(
            f"USAGE: python nyc-taxi-omnisci.py <data file name>"
        )
        return
    for i in range(0, 20):
        print("Iteration #", i+1)
        df = measure("Reading", read, sys.argv[1])
        measure("Q1", q1_omnisci, df)           # <----- was commented
        #measure("Q2", q2_omnisci, df)
        #measure("Q3", q3_omnisci, df.copy())
        #measure("Q4", q4_omnisci, df.copy())


if __name__ == "__main__":
    main()
```
I've got Segmentation Fault on nnlmlp01
```
python3 repro_i3533.py trips_xaa.csv
Iteration # 1
Thrift: Tue Nov  2 16:17:47 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:47 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Thrift: Tue Nov  2 16:17:48 2021 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused
Reading: 21.886179208755493 sec
Segmentation fault (core dumped)
```

**Comment by Garra1980** [comment]
0.11.3 released - is this ok now?

**Comment by gshimansky** [comment]
I think the correct resolution for this bug is that wrong environment variable was used to specify omnisci backend/storage format. The code works correctly if appropriate variable is used. Sorry for confusion.
