### ISSUE TITLE
Bug when using ``black`` in modin-env installed with conda

### ISSUE THREAD

**Issue by Rubtsowa** [modin-project/modin#3665]
When I try formatting code with used ``black`` in  modin-env installed with conda, I have next error:

```
$ black modin/
Traceback (most recent call last):
  File "/localdisk/mrubtsov/miniconda/envs/modin/bin/black", line 5, in <module>
    from black import patched_main
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/black/__init__.py", line 48, in <module>
    from black.files import find_project_root, find_pyproject_toml, parse_pyproject_toml
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/black/files.py", line 26, in <module>
    from black.handle_ipynb_magics import jupyter_dependencies_are_installed
  File "/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/black/handle_ipynb_magics.py", line 15, in <module>
    from typing_extensions import TypeGuard
ImportError: cannot import name 'TypeGuard' from 'typing_extensions' (/localdisk/mrubtsov/miniconda/envs/modin/lib/python3.8/site-packages/typing_extensions.py)
```

**Comment by vnlitvinov** [comment]
I think this was fixed in some `black` update in conda-forge. It runs fine on my system with `black` being
```
> conda list | findstr black
black                     22.3.0             pyhd8ed1ab_0    conda-forge
```
