### ISSUE TITLE
Simple join on default indices doesn't work on OmniSci engine

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#3740]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
- **Modin version** (`modin.__version__`): 5ca6d40f0ab9e6fede0dd5e77a415231a394fa90
- **OmniSci version**: [`intel-ai/omniscidb/modin`](https://github.com/intel-ai/omniscidb) branch (commit [`7871987`](https://github.com/intel-ai/omniscidb/commit/78719870905474b9f6cc7c79e9e19b75126a22c7)) or the latest OmniSci 5.8.0 release ([`linux-64/pyomniscidbe-5.8.0-py37h1234567_1_cpu`](https://anaconda.org/conda-forge/pyomniscidbe/files))
- **Python version**: 3.7.5
- **Code we can use to reproduce**:
```python
import modin.pandas as pd
import modin.config as cfg
import numpy as np

cfg.StorageFormat.put("Omnisci")
cfg.Engine.put("Native")
cfg.IsExperimental.put(True)

N = 1001

df1 = pd.DataFrame({"a": np.arange(N)})
df2 = pd.DataFrame({"b": np.arange(N)})

custom_index = pd.RangeIndex(1, len(df1) + 1)

print(df1.set_index(custom_index).join(df2.set_index(custom_index)))  # Works
print(df1.join(df2))  # Fails

```

<details><summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/localdisk1/dchigare/repos/modin_bp/tst.py", line 9, in <module>
    print(df1.join(df2))
  File "/localdisk1/dchigare/repos/modin_bp/modin/pandas/base.py", line 3054, in __str__
    return repr(self)
  File "/localdisk1/dchigare/repos/modin_bp/modin/pandas/dataframe.py", line 210, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/localdisk1/dchigare/repos/modin_bp/modin/pandas/base.py", line 151, in _build_repr_df
    if len(self.index) == 0 or (
  File "/localdisk1/dchigare/repos/modin_bp/modin/pandas/base.py", line 3071, in __getattribute__
    attr = super().__getattribute__(item)
  File "/localdisk1/dchigare/repos/modin_bp/modin/pandas/base.py", line 575, in _get_index
    return self._query_compiler.index
  File "/localdisk1/dchigare/repos/modin_bp/modin/experimental/core/storage_formats/omnisci/query_compiler.py", line 423, in _get_index
    return self._modin_frame.index
  File "/localdisk1/dchigare/repos/modin_bp/modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py", line 1853, in _get_index
    self._execute()
  File "/localdisk1/dchigare/repos/modin_bp/modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py", line 1638, in _execute
    new_partitions = self._partition_mgr_cls.run_exec_plan(
  File "/localdisk1/dchigare/repos/modin_bp/modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition_manager.py", line 252, in run_exec_plan
    curs = omniSession.executeRA(cmd_prefix + calcite_json)
  File "/localdisk1/dchigare/repos/modin_bp/modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py", line 110, in executeRA
    r = cls._server.executeRA(query)
  File "dbe.pyx", line 196, in omniscidbe.PyDbEngine.executeRA
RuntimeError: TException - service has thrown: TOmniSciException(error_msg=Hash join failed, reason(s): Could not build a 1-to-1 correspondence for columns involved in equijoin | Cannot join on rowid | Cannot fall back to loop join for non-trivial inner table size)
```

</details>

### Describe the problem
When the frames have default indices to join on: `RangeIndex(frame_length)`, OmniSci backend performs join on the internal meta-column called 'rowid'. There is a bug in the engine that makes such joins fail.

The issue at the OmniSci part to track: intel-ai/omniscidb#214

**Comment by anmyachev** [comment]
The reproducer works on [master](https://github.com/modin-project/modin/commit/f32a9bda4be075e9c5c99252bfeeb23d5d135d4c).
