### ISSUE TITLE
Remove providing of `address` for `ray.init` in case local cluster is used

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#3749]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Modin installed from (source or binary)**: source
- **Modin version**: 72a3e51aeeae3465a1a3076d962aef95af689dde
- **Python version**: 3.8.12
- **Exact command to reproduce**:

```python
import modin.pandas as pd
from modin.config import RayRedisAddress
RayRedisAddress.put("127.0.0.1:8080")

df = pd.DataFrame([])
print(df)
```

### Describe the problem

Current set of `ray.init` kwrags is incompatible in a case of local cluster using. Need to exclude providing of parameter `address` for Ray local cluster case
https://github.com/modin-project/modin/blob/72a3e51aeeae3465a1a3076d962aef95af689dde/modin/core/execution/ray/common/utils.py#L165-L173

### Source code / logs

```bash
Traceback (most recent call last):
  File "test4.py", line 5, in <module>
    df = pd.DataFrame([])
  File "/localdisk/aprutsko/modin/modin/pandas/dataframe.py", line 109, in __init__
    Engine.subscribe(_update_engine)
  File "/localdisk/aprutsko/modin/modin/config/pubsub.py", line 213, in subscribe
    callback(cls)
  File "/localdisk/aprutsko/modin/modin/pandas/__init__.py", line 127, in _update_engine
    initialize_ray()
  File "/localdisk/aprutsko/modin/modin/core/execution/ray/common/utils.py", line 175, in initialize_ray
    ray.init(**ray_init_kwargs)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/localdisk/aprutsko/miniconda3/envs/modin/lib/python3.8/site-packages/ray/worker.py", line 801, in init
    raise ValueError(
ValueError: When connecting to an existing cluster, num_cpus and num_gpus must not be provided.
```

**Comment by vnlitvinov** [comment]
@prutskov 
Ray is complaining about `num_cpus` and `num_gpus`, why do you want to remove _address_?..

**Comment by prutskov** [comment]
Because `address` should be provided only in a case of existing cluster usage. In case of local cluster usage we should provide other arguments to configure local cluster (like `num_cpus`, `num_gpus`).  Providing of `address` is forced Ray to connect to existing cluster
