### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#3905]
### Describe the problem
Trying to insert data into a new sqlite database, ran into a lock error.

### Source code / logs

```
In [5]: df.to_sql("millionrow", "sqlite:///test.db")
---------------------------------------------------------------------------
RayTaskError(OperationalError)            Traceback (most recent call last)
<ipython-input-5-c33a78b687f6> in <module>
----> 1 df.to_sql("millionrow", "sqlite:///test.db")

~\software_sources\modin\modin\pandas\base.py in to_sql(self, name, con, schema, if_exists, index, index_label, chunksize, dt
ype, method)
   2788         )
   2789
-> 2790         FactoryDispatcher.to_sql(
   2791             new_query_compiler,
   2792             name=name,

~\software_sources\modin\modin\core\execution\dispatching\factories\dispatcher.py in to_sql(cls, *args, **kwargs)
    270     @_inherit_docstrings(factories.BaseFactory._to_sql)
    271     def to_sql(cls, *args, **kwargs):
--> 272         return cls.__factory._to_sql(*args, **kwargs)
    273
    274     @classmethod

~\software_sources\modin\modin\core\execution\dispatching\factories\factories.py in _to_sql(cls, *args, **kwargs)
    369             Arguments to the writer method.
    370         """
--> 371         return cls.io_cls.to_sql(*args, **kwargs)
    372
    373     @classmethod

~\software_sources\modin\modin\core\execution\ray\generic\io\io.py in to_sql(cls, qc, **kwargs)
     63             return pandas.DataFrame()
     64
---> 65         result = qc._modin_frame.apply_full_axis(1, func, new_index=[], new_columns=[])
     66         # FIXME: we should be waiting for completion less expensievely, maybe use _modin_frame.materialize()?
     67         result.to_pandas()  # blocking operation

~\software_sources\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in apply_full_axis(self, axis, func, new_index, n
ew_columns, dtypes)
   1450         The data shape may change as a result of the function.
   1451         """
-> 1452         return self.broadcast_apply_full_axis(
   1453             axis=axis,
   1454             func=func,

~\software_sources\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in broadcast_apply_full_axis(self, axis, func, ot
her, new_index, new_columns, apply_indices, enumerate_partitions, dtypes)
   1892         )
   1893         if new_index is not None:
-> 1894             result.synchronize_labels(0)
   1895         if new_columns is not None:
   1896             result.synchronize_labels(1)

~\software_sources\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in synchronize_labels(self, axis)
    348         self._filter_empties()
    349         if axis is None or axis == 0:
--> 350             cum_row_lengths = np.cumsum([0] + self._row_lengths)
    351         if axis is None or axis == 1:
    352             cum_col_widths = np.cumsum([0] + self._column_widths)

~\software_sources\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in _row_lengths(self)
    115         if self._row_lengths_cache is None:
    116             if len(self._partitions.T) > 0:
--> 117                 self._row_lengths_cache = [
    118                     obj.length() for obj in self._partitions.T[0]
    119                 ]

~\software_sources\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in <listcomp>(.0)
    116             if len(self._partitions.T) > 0:
    117                 self._row_lengths_cache = [
--> 118                     obj.length() for obj in self._partitions.T[0]
    119                 ]
    120             else:

~\software_sources\modin\modin\core\execution\ray\implementations\pandas_on_ray\partitioning\partition.py in length(self)
    294                 )
    295         if isinstance(self._length_cache, ObjectIDType):
--> 296             self._length_cache = ray.get(self._length_cache)
    297         return self._length_cache
    298

~\anaconda3\lib\site-packages\ray\_private\client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106
    107     return wrapper

~\anaconda3\lib\site-packages\ray\worker.py in get(object_refs, timeout)
   1711                     worker.core_worker.dump_object_store_memory_usage()
   1712                 if isinstance(value, RayTaskError):
-> 1713                     raise value.as_instanceof_cause()
   1714                 else:
   1715                     raise value

RayTaskError(OperationalError): ray::deploy_ray_func() (pid=62632, ip=127.0.0.1)
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

ray::deploy_ray_func() (pid=62632, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 618, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 659, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 625, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 629, in ray._raylet.execute_task
  File "C:\Users\devin\software_sources\modin\modin\core\execution\ray\implementations\pandas_on_ray\partitioning\axis_partit
ion.py", line 211, in deploy_ray_func
    result = func(*args)
  File "C:\Users\devin\software_sources\modin\modin\core\dataframe\pandas\partitioning\axis_partition.py", line 160, in deplo
y_axis_func
    result = func(dataframe, **kwargs)
  File "C:\Users\devin\software_sources\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 1181, in _map_reduce_
func
    series_result = func(df, *args, **kwargs)
  File "C:\Users\devin\software_sources\modin\modin\core\execution\ray\generic\io\io.py", line 62, in func
    df.to_sql(**kwargs)
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\core\generic.py", line 2872, in to_sql
    sql.to_sql(
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\io\sql.py", line 717, in to_sql
    pandas_sql.to_sql(
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\io\sql.py", line 1761, in to_sql
    sql_engine.insert_records(
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\io\sql.py", line 1350, in insert_records
    raise err
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\io\sql.py", line 1340, in insert_records
    table.insert(chunksize=chunksize, method=method)
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\io\sql.py", line 967, in insert
    exec_insert(conn, keys, chunk_iter)
  File "C:\Users\devin\anaconda3\lib\site-packages\pandas\io\sql.py", line 882, in _execute_insert
    conn.execute(self.table.insert(), data)
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1286, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1779, in _execute_context
    self.dialect.do_executemany(
  File "C:\Users\devin\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 714, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

cc @Garra1980

**Comment by vnlitvinov** [comment]
@devin-petersohn I wonder if there's a usable repro for this issue?..

**Comment by mvashishtha** [comment]
It seems that sqlite can't support a high level of concurrency. See here: https://stackoverflow.com/a/3172950/17554722

**Comment by jbrockmendel** [comment]
are multiple working processes trying to write to the database concurrently?  That's a recipe for a bad time.
