### ISSUE TITLE
`StorageFormat` config doesn't work with OmniSci IO functions

### ISSUE THREAD

**Issue by amyskov** [modin-project/modin#4017]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: 9782a027568d9ad16bf2c3dea434646cec5e4898
- **Python version**: 3.8.12
- **Code we can use to reproduce**:
```
import modin.pandas as pd

import modin.config as cfg
cfg.StorageFormat.put('omnisci')

# df = pd.DataFrame([1]) # works fine
df = pd.read_csv("test") # fails
```

### Source code / logs

```
Traceback (most recent call last):
  File "/modin2/modin/core/execution/dispatching/factories/dispatcher.py", line 129, in _update_factory
    cls.__factory = getattr(factories, factory_name)
AttributeError: module 'modin.core.execution.dispatching.factories.factories' has no attribute 'OmnisciOnRayFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample.py", line 46, in <module>
    df = pd.read_csv("test") # fails
  File "/modin2/modin/pandas/io.py", line 135, in read_csv
    return _read(**kwargs)
  File "/modin2/modin/pandas/io.py", line 56, in _read
    from modin.core.execution.dispatching.factories.dispatcher import FactoryDispatcher
  File "/modin2/modin/core/execution/dispatching/factories/dispatcher.py", line 297, in <module>
    Engine.subscribe(FactoryDispatcher._update_factory)
  File "/modin2/modin/config/pubsub.py", line 213, in subscribe
    callback(cls)
  File "/modin2/modin/core/execution/dispatching/factories/dispatcher.py", line 150, in _update_factory
    raise FactoryNotFoundError(
modin.core.execution.dispatching.factories.dispatcher.FactoryNotFoundError: Cannot find a factory for partition 'Omnisci' and execution engine 'Ray'. Potential reason might be incorrect environment variable value for MODIN_STORAGE_FORMAT or MODIN_ENGINE
```

**Comment by amyskov** [comment]
Issue wasn't recognized by CI because, CI tests also set `MODIN_EXPERIMENTAL` and `MODIN_ENGINE` environment variables (which eliminates issue triggering), so to avoid such misses, it is desirable to leave only `MODIN_STORAGE_FORMAT` variable (can be made in the PR with fix for this issue).
