### ISSUE TITLE
dataframe.to_sql write data to sql server issues!

### ISSUE THREAD

**Issue by EnderWuBinHao** [modin-project/modin#4048]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: windows server
- **Modin version** (`modin.__version__`): 0.12.1
- **Python version**:3.8.12
- **Code we can use to reproduce**: may be

### Describe the problem

when I use modin.pandas to load dataframe to sql server.
cnn=create_engine('mssql+pymssql:// xxxx)
Dataframe.to_sql('Test_Table',cnn,if_exists='replace')
then it will return a issues code : can not pickle 'sqlalchemy.cprocessors.UnicodeResultProcessor' object
If I change to pandas and used the same code to write data  this issue not occurred.

**Comment by amyskov** [comment]
Hi @EnderWuBinHao!
Thanks for reporting! I can reproduce your issue using Postgresql DBMS, see reproducer below:
```
import modin.pandas as pd
from sqlalchemy import create_engine

table_name = "test_table"
conn_str = "postgresql://username:password@localhost/db_name"
conn = create_engine(conn_str)

df = pd.DataFrame({"col1": [1,2,3], "col2": [4,5,6]})
df.to_sql(table_name, conn, index=False)
```

<details> 
  <summary>Output</summary>

```
Traceback (most recent call last):
  File "test.py", line 688, in <module>
    df.to_sql(table_name, conn, index=False)
  File "C:\Modin\modin\modin\pandas\base.py", line 2790, in to_sql
    FactoryDispatcher.to_sql(
  File "C:\Modin\modin\modin\core\execution\dispatching\factories\dispatcher.py", line 272, in to_sql
    return cls.__factory._to_sql(*args, **kwargs)
  File "C:\Modin\modin\modin\core\execution\dispatching\factories\factories.py", line 371, in _to_sql
    return cls.io_cls.to_sql(*args, **kwargs)
  File "C:\Modin\modin\modin\core\execution\ray\implementations\pandas_on_ray\io\io.py", line 116, in to_sql
    result = qc._modin_frame.apply_full_axis(1, func, new_index=[], new_columns=[])
  File "C:\Modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 109, in run_f_on_minimally_updated_metadata
    result = f(self, *args, **kwargs)
  File "C:\Modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 1824, in apply_full_axis
    return self.broadcast_apply_full_axis(
  File "C:\Modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 109, in run_f_on_minimally_updated_metadata
    result = f(self, *args, **kwargs)
  File "C:\Modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py", line 2241, in broadcast_apply_full_axis
    new_partitions = self._partition_mgr_cls.broadcast_axis_partitions(
  File "C:\Modin\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py", line 423, in broadcast_axis_partitions
    preprocessed_map_func = cls.preprocess_func(apply_func)
  File "C:\Modin\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py", line 113, in preprocess_func
    return cls._partition_class.preprocess_func(map_func)
  File "C:\Modin\modin\modin\core\execution\ray\implementations\pandas_on_ray\partitioning\partition.py", line 277, in preprocess_func
    return ray.put(func)
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\worker.py", line 1682, in put
    object_ref = worker.put_object(
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\worker.py", line 292, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\serialization.py", line 334, in serialize
    return self._serialize_to_msgpack(value)
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\serialization.py", line 314, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\serialization.py", line 274, in _serialize_to_pickle5
    raise e
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\serialization.py", line 270, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "C:\Users\username\.conda\envs\modin2\lib\site-packages\ray\cloudpickle\cloudpickle_fast.py", line 580, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'sqlalchemy.cprocessors.UnicodeResultProcessor' object
```

</details>

As temporary solution you can use `conn_str` instead of `conn` or you can use try out Modin pickable connection object `ModinDatabaseConnection` (see details [here](https://modin.readthedocs.io/en/latest/getting_started/faq.html#how-do-i-connect-modin-to-a-database-via-read-sql)), both these solutions provide parallel reading from database.

**Comment by devin-petersohn** [comment]
@amyskov We should have a better error message here. Can we check the type of `conn` in `to_sql` like we do in `read_sql`?

**Comment by devin-petersohn** [comment]
Great, I will schedule for 0.14 release.

**Comment by EnderWuBinHao** [comment]
@amyskov Thanks!  I have tried the "ModinDatabaseConnection", but seem it does not support the mssql DB?
report error message "unsupported database library pymysql"
I will use the default pandas implementation until the new version release~ thanks a lot!

**Comment by devin-petersohn** [comment]
cc @mvashishtha

**Comment by vnlitvinov** [comment]
Should be something similar to https://github.com/modin-project/modin/pull/712

**Comment by mvashishtha** [comment]
** For those who are seeing this error **

The workaround for now is to pass a connection string (see sqlalchemy docs [here](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine) in case you're using sqlalchemy) rather than a connection object.

For @modin-project/modin-contributors  and @modin-project/modin-core : Modin should do a fix like #712 where we extract the URL from the engine and then send the URL to workers in the case of sqlalchemy. If we can't get a URL, we should default to pandas. Finally, the long term solution for connection objects in `to_sql` is #5626.
