### ISSUE TITLE
Readthedocs build failed

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#4115]
### Describe the problem

Building of documentation is failing now (https://readthedocs.org/projects/modin/builds/15930731/, https://readthedocs.org/projects/modin/builds/15933959/)
```bash
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

**Comment by prutskov** [comment]
The root cause of issue in pip (https://github.com/pypa/pip/issues/10851). Other users faced with the problem too: https://github.com/readthedocs/readthedocs.org/issues/8864

**Comment by dchigarev** [comment]
Reopen to track the status of this "FIXME":
https://github.com/modin-project/modin/blob/5de7f18f73910a0909853e7b22f2504ef2011f8f/docs/requirements-doc.txt#L16-L19
