### ISSUE TITLE
pydocstyle check is failing with `module 'cupy' has no attribute 'ndarray'`

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#4116]
### Describe the problem

The issue is observed in the CI of new PRs like #4109 

### Source code / logs

```bash
Run python scripts/doc_checker.py modin/core/execution/dask
Traceback (most recent call last):
  File "scripts/doc_checker.py", line 624, in <module>
    if not validate(args.paths, args.add_ignore, not args.disable_numpydoc):
  File "scripts/doc_checker.py", line 556, in validate
    if not numpydoc_validate(path):
  File "scripts/doc_checker.py", line 442, in numpydoc_validate
    results = list(map(validate_object, to_validate))
  File "scripts/doc_checker.py", line 359, in validate_object
    doc = Docstring(import_path)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/numpydoc/validate.py", line 128, in __init__
    obj = self._load_obj(name)
  File "scripts/doc_checker.py", line 517, in load_obj
    obj = old_load_obj(name)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/numpydoc/validate.py", line 158, in _load_obj
    obj = importlib.import_module(module)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/modin/modin/modin/core/execution/dask/common/task_wrapper.py", line 16, in <module>
    from distributed.client import default_client
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/distributed/__init__.py", line 7, in <module>
    from .actor import Actor, ActorFuture
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/distributed/actor.py", line 5, in <module>
    from .client import Future
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/distributed/client.py", line 103, in <module>
    from .worker import get_client, get_worker, secede
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/distributed/worker.py", line 47, in <module>
    from . import comm, preloading, profile, shuffle, system, utils
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/distributed/shuffle/__init__.py", line 9, in <module>
    from .shuffle import rearrange_by_column_p2p
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/distributed/shuffle/shuffle.py", line 6, in <module>
    from dask.dataframe import DataFrame
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from . import backends, dispatch, rolling
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/dataframe/backends.py", line 15, in <module>
    from dask.array.dispatch import percentile_lookup
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/array/__init__.py", line 3, in <module>
    from . import backends, fft, lib, linalg, ma, overlap, random
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/array/backends.py", line 13, in <module>
    from .percentile import _percentile
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/array/percentile.py", line 11, in <module>
    from .core import Array
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/array/core.py", line 76, in <module>
    from .chunk_types import is_valid_array_chunk, is_valid_chunk_type
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/dask/array/chunk_types.py", line 110, in <module>
    register_chunk_type(cupy.ndarray)
AttributeError: module 'cupy' has no attribute 'ndarray'
Error: Process completed with exit code 1.
```

**Comment by dchigarev** [comment]
Reopen to find out the actual problem why dask import flow [is failing without faking `cupy` module](https://github.com/modin-project/modin/pull/4114#discussion_r795626508)

**Comment by mvashishtha** [comment]
`python scripts/doc_checker.py modin/core/execution/dask` now passes.
