### ISSUE TITLE
`print(df)` fails after a number of filter operations using `omnisci` storage format

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#4155]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.3 LTS
- **Modin installed from (source or binary)**: source
- **Modin version**: 31e6a1061fffa774102335dfcfa8de9ed5ad63e6
- **Python version**: 3.8.12
- **Exact command to reproduce**:

<details><summary>Script to reproduce</summary>

```python
import modin.pandas as pd
import modin.config as cfg

cfg.StorageFormat.put("omnisci")


columns = [
    "vendor_id",
    "pickup_datetime",
    "dropoff_datetime",
    "passenger_count",
    "trip_distance",
    "pickup_longitude",
    "pickup_latitude",
    "rate_code",
    "store_and_fwd_flag",
    "dropoff_longitude",
    "dropoff_latitude",
    "payment_type",
    "fare_amount",
    "surcharge",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "total_amount",
]

df = pd.read_csv(
    "/localdisk/aprutsko/datasets/nyc_taxi_data.csv",
    parse_dates=["pickup_datetime", "dropoff_datetime"],
    names=columns,
    header=0,
)
df = df.drop(
    columns=[
        "vendor_id",
        "store_and_fwd_flag",
        "payment_type",
        "surcharge",
        "mta_tax",
        "tip_amount",
        "tolls_amount",
        "total_amount",
    ]
)

df = df[df.fare_amount > 1]

df["day"] = df["pickup_datetime"].dt.day
df = df.drop(columns=["passenger_count", "rate_code"])
df = df[df.day < 25]     # If you remove this line the flow successfully works without exceptions.

print(df)
```

</details>

Data is NY Taxi(https://s3-us-west-2.amazonaws.com/nyctlc/nyc_taxi_data.csv.gz). Decompressed csv is used.

### Describe the problem

Some combinations of filter operations can't be done via omnisci on native. Ray engine works without any error.

### Source code / logs

<details><summary>Traceback</summary>

```bash
Thrift: Fri Feb  4 08:04:02 2022 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused                                 Thrift: Fri Feb  4 08:04:02 2022 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused                                 Thrift: Fri Feb  4 08:04:02 2022 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused                                 Thrift: Fri Feb  4 08:04:02 2022 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused                                 Thrift: Fri Feb  4 08:04:02 2022 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused                                 Thrift: Fri Feb  4 08:04:02 2022 TSocket::open() error on socket (after THRIFT_POLL) <Host: localhost Port: 6279>: Connection refused                                 Traceback (most recent call last):
  File "test.py", line 53, in <module>
    print(df)
  File "/localdisk/aprutsko/modin/modin/pandas/base.py", line 3127, in __str__
    return repr(self)
  File "/localdisk/aprutsko/modin/modin/pandas/dataframe.py", line 211, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/localdisk/aprutsko/modin/modin/pandas/base.py", line 202, in _build_repr_df
    return self.iloc[indexer]._query_compiler.to_pandas()
  File "/localdisk/aprutsko/modin/modin/experimental/core/storage_formats/omnisci/query_compiler.py", line 182, in to_pandas
    return self._modin_frame.to_pandas()
  File "/localdisk/aprutsko/modin/modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py", line 2192, in to_pandas
    df = self._partition_mgr_cls.to_pandas(self._partitions)
  File "/localdisk/aprutsko/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 632, in to_pandas
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
  File "/localdisk/aprutsko/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 632, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
  File "/localdisk/aprutsko/modin/modin/core/dataframe/pandas/partitioning/partition_manager.py", line 632, in <listcomp>
    retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
  File "/localdisk/aprutsko/modin/modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition.py", line 85, in to_pandas
    return obj.to_pandas()
  File "pyarrow/array.pxi", line 757, in pyarrow.lib._PandasConvertible.to_pandas
  File "pyarrow/table.pxi", line 1748, in pyarrow.lib.Table._to_pandas
  File "/localdisk/aprutsko/miniconda/envs/modin_on_omnisci/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 789, in table_to_blockmanager
    blocks = _table_to_blocks(options, table, categories, ext_columns_dtypes)
  File "/localdisk/aprutsko/miniconda/envs/modin_on_omnisci/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1128, in _table_to_blocks
    result = pa.lib.table_to_blocks(options, block_table, categories,
  File "pyarrow/table.pxi", line 1156, in pyarrow.lib.table_to_blocks
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Casting from timestamp[s] to timestamp[ns] would result in out of bounds timestamp: -4588465558813019847
```

</details>

**Comment by vnlitvinov** [comment]
@modin-project/modin-omnisci  could someone please check if this still happens?

**Comment by AndreyPavlenko** [comment]
> @modin-project/modin-omnisci could someone please check if this still happens?

I'm unable to reproduce the issue, using a datafile, truncated to 10m lines. With the original data file, it falls to out of memory on my system.

**Comment by AndreyPavlenko** [comment]
The issue is reproducible, at least, on the first 85 millions of lines from the original dataset. However, it's not reproducible on 84m of lines:
head -85000001 < nyc_taxi_data.csv > nyc_taxi_data_tr.csv # Reproducible
head -84000001 < nyc_taxi_data.csv > nyc_taxi_data_tr.csv # Not reproducible 

Neither it's reproducible on the dataset, consisting of lines in the range 84m-85m:
head -1 < nyc_taxi_data.csv > nyc_taxi_data_tr.csv &&\
head -85000001 < nyc_taxi_data.csv | tail -10000000 >> nyc_taxi_data_tr.csv

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
