### ISSUE TITLE
`modin.pandas.read_csv` doesn't work against file type `tempfile.SpooledTemporaryFile`

### ISSUE THREAD

**Issue by KayyoungHL** [modin-project/modin#4216]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04 (WSL)
- **Modin version** (`modin.__version__`): 0.13.1
- **Python version**: Python 3.8.10
- **Code we can use to reproduce**:
```python
from fastapi import FastAPI, UploadFile
# import pandas as pd
import modin.pandas as pd
import modin
import ray

ray.init()
app = FastAPI()

@app.post("/uploadfile/")
async def create_upload_file(file: UploadFile):
    print("Modin Version: ",modin.__version__)  # Modin Version:  0.13.1
    print("File Type: ", type(file.file))       # File Type:  <class 'tempfile.SpooledTemporaryFile'>

    df = pd.read_csv(file.file)
    await file.close()
    print(df.head())

    return df.to_json()
```

### Describe the problem

I tried to make a dataframe using modin.pandas.read_csv function but it didn't work same as a pandas.

1. make FastAPI app
2. post csv file(kaggle titanic `train.csv` file) 
    Using chrome app ARC
    Header name: Content-Type, Header value: multipart/form-data
3. Try to make this file(`tempfile.SpooledTemporaryFile`) to dataframe using `read_csv` function
4. It works in pandas but it doesn't work in modin.pandas

I wrote full source code.

※ version of FastAPI : 0.73.0

This link may help you to understand
[https://fastapi.tiangolo.com/tutorial/request-files/](https://fastapi.tiangolo.com/tutorial/request-files/)

### Source code / logs

modin.pandas
```terminal
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [31488]
2022-02-17 19:35:41,750 INFO services.py:1374 -- View the Ray dashboard at http://127.0.0.1:8265
INFO:     Started server process [31490]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Modin Version:  0.13.1
File Type:  <class 'tempfile.SpooledTemporaryFile'>
INFO:     127.0.0.1:60734 - "POST /uploadfile/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/kayyoung/.local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/kayyoung/.local/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/kayyoung/python38/AIPlay/./x.py", line 16, in create_upload_file
    df = pd.read_csv(file.file)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/pandas/io.py", line 135, in read_csv
    return _read(**kwargs)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/pandas/io.py", line 60, in _read
    pd_obj = FactoryDispatcher.read_csv(**kwargs)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/core/execution/dispatching/factories/dispatcher.py", line 180, in read_csv
    return cls.__factory._read_csv(**kwargs)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/core/execution/dispatching/factories/factories.py", line 207, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/core/io/file_dispatcher.py", line 151, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/core/io/text/text_file_dispatcher.py", line 935, in _read
    else cls.get_path_or_buffer(filepath_or_buffer)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/core/io/text/text_file_dispatcher.py", line 72, in get_path_or_buffer
    if cls.file_exists(buffer_filepath):
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/site-packages/modin/core/io/file_dispatcher.py", line 271, in file_exists
    return os.path.exists(file_path)
  File "/home/kayyoung/anaconda3/envs/aiplay/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

pandas
```terminal
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [32163]
2022-02-17 19:53:36,544 INFO services.py:1374 -- View the Ray dashboard at http://127.0.0.1:8265
INFO:     Started server process [32165]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
Modin Version:  0.13.1
File Type:  <class 'tempfile.SpooledTemporaryFile'>
   PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
4            5         0       3                           Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S
INFO:     127.0.0.1:32818 - "POST /uploadfile/ HTTP/1.1" 200 OK
```

**Comment by amyskov** [comment]
Hi @KayyoungHL !
Thanks for the report! Modin's implementation of `read_csv` can't use buffers and always tries to extract source file name for further usage, but your case is not properly handled by Modin (this will be fixed in the further releases). For now you can use original file name (`file.filename`) if file is accessible in your case.

**Comment by KayyoungHL** [comment]
@amyskov 
Thank you for the answer!

I hope to see a new release as soon as possible.

Unfortunately, I can't access file directly but I think a little effort's enough to make dataframe using buffer.
Before fixing, I'm going to read this buffer then make dataframe.

Again, thank you!

**Comment by devin-petersohn** [comment]
@mvashishtha was working on something related to fixing #806, which appear to be similar to this issue.

**Comment by vnlitvinov** [comment]
I wonder if that is somewhat related to https://github.com/modin-project/modin/pull/4681

**Comment by anmyachev** [comment]
It seems that the case with `tempfile.SpooledTemporaryFile` works. Hower it defaults to pandas. The following reproducer can be used to check.

```python
import tempfile

def prepare_temp_file():
    temp_file = tempfile.SpooledTemporaryFile()
    with open("modin/pandas/test/data/issue_976.csv", mode="rb") as _f:
        temp_file.write(_f.read())
        temp_file.seek(0)
    return temp_file

import modin.pandas as pd
import pandas

names = [str(i) for i in range(11)]
read_kwargs = {
    "sep": ";",
    "names": names,
    "encoding": "windows-1251",
}

df = pandas.read_csv(prepare_temp_file(), **read_kwargs)
md_df = pd.read_csv(prepare_temp_file(), **read_kwargs)
print(df)
print(md_df)
```

@KayyoungHL feel free to reopen if needed.
