### ISSUE TITLE
Modin `merge_asof` fails when `on` parameter refers to an index

### ISSUE THREAD

**Issue by c3-andrewfitch** [modin-project/modin#4292]
### System information
ray 1.9.2
modin 0.12.0
pandas 1.3.4

### Describe the problem
In Modin, calling `pd.merge_asof()` where the `on` parameter refers to an index fails. 

Code to reproduce:
```
import modin.pandas as pd
left_df = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]}).set_index('a')
right_df = pd.DataFrame({'a': [4], 'c': [6]}).set_index('a')
pd.merge_asof(left_df, right_df, on='a')
``` 

Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "modin/pandas/general.py", line 209, in merge_asof
    left_column = to_pandas(left[left_on])
  File "modin/pandas/base.py", line 2967, in __getitem__
    return self._getitem(key)
  File "modin/pandas/dataframe.py", line 2959, in _getitem
    return self._getitem_column(key)
  File "modin/pandas/dataframe.py", line 2425, in _getitem_column
    raise KeyError("{}".format(key))
KeyError: 'a'
```

Expected output when ran in native pandas:
```
   a  b   c
0  1  4 NaN
1  2  5 NaN
2  3  6 NaN
```

**Comment by mvashishtha** [comment]
@c3-andrewfitch thanks for reporting the issue! I can reproduce it on the latest Modin source. I'll see if I can make a quick fix. Otherwise, we'll try to fix the bug soon.

**Comment by mvashishtha** [comment]
As a reference for whoever fixes this bug, here's a stack trace that shows how pandas determines the join key in `merge_asof`:

<details>
<summary>Show stack trace</summary>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [17], in <module>
----> 1 pd.merge_asof(left_df, right_df, on="a")

File /usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py:581, in merge_asof(left, right, on, left_on, right_on, left_index, right_index, by, left_by, right_by, suffixes, tolerance, allow_exact_matches, direction)
    326 def merge_asof(
    327     left: DataFrame | Series,
    328     right: DataFrame | Series,
   (...)
    340     direction: str = "backward",
    341 ) -> DataFrame:
    342     """
    343     Perform a merge by key distance.
    344
   (...)
    579     4 2016-05-25 13:30:00.048   AAPL   98.00       100     NaN     NaN
    580     """
--> 581     op = _AsOfMerge(
    582         left,
    583         right,
    584         on=on,
    585         left_on=left_on,
    586         right_on=right_on,
    587         left_index=left_index,
    588         right_index=right_index,
    589         by=by,
    590         left_by=left_by,
    591         right_by=right_by,
    592         suffixes=suffixes,
    593         how="asof",
    594         tolerance=tolerance,
    595         allow_exact_matches=allow_exact_matches,
    596         direction=direction,
    597     )
    598     return op.get_result()

File /usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1740, in _AsOfMerge.__init__(self, left, right, on, left_on, right_on, left_index, right_index, by, left_by, right_by, axis, suffixes, copy, fill_method, how, tolerance, allow_exact_matches, direction)
   1737 self.allow_exact_matches = allow_exact_matches
   1738 self.direction = direction
-> 1740 _OrderedMerge.__init__(
   1741     self,
   1742     left,
   1743     right,
   1744     on=on,
   1745     left_on=left_on,
   1746     right_on=right_on,
   1747     left_index=left_index,
   1748     right_index=right_index,
   1749     axis=axis,
   1750     how=how,
   1751     suffixes=suffixes,
   1752     fill_method=fill_method,
   1753 )

File /usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1626, in _OrderedMerge.__init__(self, left, right, on, left_on, right_on, left_index, right_index, axis, suffixes, copy, fill_method, how)
   1609 def __init__(
   1610     self,
   1611     left: DataFrame | Series,
   (...)
   1622     how: str = "outer",
   1623 ):
   1625     self.fill_method = fill_method
-> 1626     _MergeOperation.__init__(
   1627         self,
   1628         left,
   1629         right,
   1630         on=on,
   1631         left_on=left_on,
   1632         left_index=left_index,
   1633         right_index=right_index,
   1634         right_on=right_on,
   1635         axis=axis,
   1636         how=how,
   1637         suffixes=suffixes,
   1638         sort=True,  # factorize sorts
   1639     )

File /usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py:700, in _MergeOperation.__init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    693 self._cross = cross_col
    695 # note this function has side effects
    696 (
    697     self.left_join_keys,
    698     self.right_join_keys,
    699     self.join_names,
--> 700 ) = self._get_merge_keys()
    702 # validate the merge keys dtypes. We may need to coerce
    703 # to avoid incompatible dtypes
    704 self._maybe_coerce_merge_keys()

File /usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1835, in _AsOfMerge._get_merge_keys(self)
   1832 def _get_merge_keys(self):
   1833
   1834     # note this function has side effects
-> 1835     (left_join_keys, right_join_keys, join_names) = super()._get_merge_keys()
   1837     # validate index types are the same
   1838     for i, (lk, rk) in enumerate(zip(left_join_keys, right_join_keys)):

File /usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py:1110, in _MergeOperation._get_merge_keys(self)
   1108     right_keys.append(rk)
   1109 if lk is not None:
-> 1110     left_keys.append(left._get_label_or_level_values(lk))
   1111     join_names.append(lk)
   1112 else:
   1113     # work-around for merge_asof(left_index=True)

File /usr/local/lib/python3.9/site-packages/pandas/core/generic.py:1843, in NDFrame._get_label_or_level_values(self, key, axis)
   1840 other_axes = [ax for ax in range(self._AXIS_LEN) if ax != axis]
   1842 if self._is_label_reference(key, axis=axis):
-> 1843     self._check_label_or_level_ambiguity(key, axis=axis)
   1844     values = self.xs(key, axis=other_axes[0])._values
   1845 elif self._is_level_reference(key, axis=axis):

File /usr/local/lib/python3.9/site-packages/pandas/core/generic.py:1802, in NDFrame._check_label_or_level_ambiguity(self, key, axis)
   1794 label_article, label_type = (
   1795     ("a", "column") if axis == 0 else ("an", "index")
   1796 )
   1798 msg = (
   1799     f"'{key}' is both {level_article} {level_type} level and "
   1800     f"{label_article} {label_type} label, which is ambiguous."
   1801 )
-> 1802 raise ValueError(msg)

ValueError: 'a' is both an index level and a column label, which is ambiguous.
```

</details>

I got that stack trace with:

```python
import pandas as pd
left_df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]}).set_index("a")
left_df["a"] = [7, 8, 9]
right_df = pd.DataFrame({"a": [4], "c": [6]}).set_index("a")
pd.merge_asof(left_df, right_df, on="a")
```

Note that when we fix this bug, we should add a test for cases like this, where the join key name is both the name of the index and the name of a column.
