### ISSUE TITLE
TypeError: '>' not supported between instances of 'list' and 'int' in iloc

### ISSUE THREAD

**Issue by Bidek56** [modin-project/modin#43]
### System information
- **OS Platform and Distribution**: "Ubuntu 18.04 LTS"
- **Modin installed from (source or binary)**: binary
- **Modin version**: 0.1.0
- **Python version**: 3.6.5
- **Exact command to reproduce**: df.iloc[0:5,:]

Calling: **df.iloc[0:5,:]** results in the following error:

Traceback (most recent call last):
  File "bakeoffModin.py", line 15, in <module>
    print( f'Sample:\n {df.iloc[0:5,:]} ')
  File "/usr/local/lib/python3.6/dist-packages/modin/pandas/dataframe.py", line 230, in __str__
    return repr(self)
  File "/usr/local/lib/python3.6/dist-packages/modin/pandas/dataframe.py", line 325, in __repr__
    return repr(self._repr_helper_())
  File "/usr/local/lib/python3.6/dist-packages/modin/pandas/dataframe.py", line 235, in _repr_helper_
    return to_pandas(self)
  File "/usr/local/lib/python3.6/dist-packages/modin/pandas/utils.py", line 227, in to_pandas
    pandas_df = pandas.concat(ray.get(df._row_partitions), copy=False)
  File "/usr/local/lib/python3.6/dist-packages/modin/pandas/dataframe.py", line 198, in _get_row_partitions
    empty_rows_mask = self._row_metadata._lengths > 0
TypeError: '>' not supported between instances of 'list' and 'int'

**Comment by devin-petersohn** [comment]
Hi @Bidek56! Thanks for catching this bug! We will try to get this fixed by the end of the week.

In the meantime, we should still support `df.head(n)`

**Comment by avloss** [comment]
same issue - `df.loc[:,cols]` raises `TypeError: '>' not supported between instances of 'list' and 'int'`
