### ISSUE TITLE
Modin read_csv issue: "UserWarning: `read_*` implementation has mismatches with pandas:"

### ISSUE THREAD

**Issue by ccortez-formalloy** [modin-project/modin#4321]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro, 64bit
- **Modin version** (`modin.__version__`): 0.13.2
- **Python version**: 3.9
- **Code we can use to reproduce**:

df = pd.read_csv(filename, low_memory=False, on_bad_lines='skip')

### Describe the problem

I cannot share the file I am using but it is a CSV that reads just fine with pandas. The operation is simply just a read_csv, that worked just fine with pandas. When I first tried this on jupyter-lab it worked just fine, but now that I am running it on PyCharm it is causing this issue: (see logs section). I didnt do anything differently than what I did in my notebook. I used both dask and ray to try this on PyCharm and they both returned this same error. For some reason, when I run this on jupyter it works just fine. Not sure what else to do and the troubleshooting section in the docs doesn't include anything on this topic. The file I am trying to read in contains strings on the first row, but then the rest of the rows are all floats/ints. This worked smoothly on Pandas and when I tried it on jupyter-lab. Any help is appreciated. Let me know if there is need for clarification. 

### Source code / logs

UserWarning: `read_*` implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.
Traceback (most recent call last):
  File "M:\ParameterGenius\filereader.py", line 32, in <module>
    df = pd.read_csv('FormAlloy-Test_5_DATA002.txt', low_memory=False, on_bad_lines='skip')
  File "M:\ParameterGenius\venv\lib\site-packages\modin\pandas\io.py", line 135, in read_csv
    return _read(**kwargs)
  File "M:\ParameterGenius\venv\lib\site-packages\modin\pandas\io.py", line 60, in _read
    pd_obj = FactoryDispatcher.read_csv(**kwargs)
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\execution\dispatching\factories\dispatcher.py", line 180, in read_csv
    return cls.__factory._read_csv(**kwargs)
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\execution\dispatching\factories\factories.py", line 207, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\io\file_dispatcher.py", line 151, in read
    query_compiler = cls._read(*args, **kwargs)
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\io\text\text_file_dispatcher.py", line 1024, in _read
    new_query_compiler = cls._get_new_qc(
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\io\text\text_file_dispatcher.py", line 858, in _get_new_qc
    dtypes = cls.get_dtypes(dtypes_ids) if len(dtypes_ids) > 0 else None
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 242, in get_dtypes
    frame_dtypes = combined_part_dtypes.apply(
  File "M:\ParameterGenius\venv\lib\site-packages\pandas\core\frame.py", line 8827, in apply
    return op.apply().__finalize__(self, method="apply")
  File "M:\ParameterGenius\venv\lib\site-packages\pandas\core\apply.py", line 727, in apply
    return self.apply_standard()
  File "M:\ParameterGenius\venv\lib\site-packages\pandas\core\apply.py", line 851, in apply_standard
    results, res_index = self.apply_series_generator()
  File "M:\ParameterGenius\venv\lib\site-packages\pandas\core\apply.py", line 867, in apply_series_generator
    results[i] = self.f(v)
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 243, in <lambda>
    lambda row: find_common_type_cat(row.values),
  File "M:\ParameterGenius\venv\lib\site-packages\modin\core\storage_formats\pandas\parsers.py", line 135, in find_common_type_cat
    return find_common_type(list(types))
  File "M:\ParameterGenius\venv\lib\site-packages\pandas\core\dtypes\cast.py", line 1841, in find_common_type
    return np.find_common_type(types, [])
  File "M:\ParameterGenius\venv\lib\site-packages\numpy\core\numerictypes.py", line 649, in find_common_type
    array_types = [dtype(x) for x in array_types]
  File "M:\ParameterGenius\venv\lib\site-packages\numpy\core\numerictypes.py", line 649, in <listcomp>
    array_types = [dtype(x) for x in array_types]
TypeError: Cannot interpret 'nan' as a data type

Process finished with exit code 1

**Comment by devin-petersohn** [comment]
Hi @ccortez-formalloy thanks for posting!

cc @anmyachev are you aware of anything that would cause a difference between pycharm and jupyter?

**Comment by anmyachev** [comment]
Hi @ccortez-formalloy!

I'm not strong in pycharm usage, but it has the ability to create [virtual environments](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html) for the project. I suggest you make sure that in both cases the environment is the same (at least versions of the following modules: `modin`, `pandas`, `numpy`).

**Comment by ccortez-formalloy** [comment]
I appreciate the response! I will check that. Do either of you happen to know what the error
 `UserWarning: read_* implementation has mismatches with pandas:
Data types of partitions are different! Please refer to the troubleshooting section of the Modin documentation to fix this issue.`
might mean how it could be fixed? I didn't see it in the troubleshooting section of the docs.

**Comment by anmyachev** [comment]
@ccortez-formalloy the [section](https://modin.readthedocs.io/en/latest/getting_started/troubleshooting.html#importing-heterogeneous-data-by-read-csv) you are looking for. Hope this helps you :)

**Comment by anmyachev** [comment]
@ccortez-formalloy feel free to reopen the issue if needed :)
