### ISSUE TITLE
TEST: "build docs" CI action is broken with SphinxWarning: Invalid configuration value found: 'language = None'.

### ISSUE THREAD

**Issue by mvashishtha** [modin-project/modin#4552]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Monterey
- **Modin version** (`modin.__version__`): 0477c688972bee89250d75835ff543db27f2e0d5
- **Python version**:  3.9.12
- **Code we can use to reproduce**:
`cd docs && sphinx-build -T -E -W -b html . build`

### Describe the problem
Building docs fails with SphinxWarning: Invalid configuration value found: 'language = None'. Fails with latest Sphinx version, 5.0.1, as well as previous version, 5.0.0.

### Source code / logs

<details>
<summary>Stack trace </summary>

```
Running Sphinx v5.0.0

Traceback (most recent call last):
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/sphinx/config.py", line 172, in read
    logger.warning(__("Invalid configuration value found: 'language = None'. "
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 1812, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/sphinx/util/logging.py", line 122, in log
    super().log(level, msg, *args, **kwargs)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 1844, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 1512, in log
    self._log(level, msg, args, **kwargs)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 948, in handle
    rv = self.filter(record)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/Users/maheshvashishtha/opt/anaconda3/envs/modin-latest/lib/python3.9/site-packages/sphinx/util/logging.py", line 425, in filter
    raise exc
sphinx.errors.SphinxWarning: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).

Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
```

</details>

**Comment by mvashishtha** [comment]
It looks like we have to use `en` now, per this post : https://lore.kernel.org/all/bd0c2ddc-2401-03cb-4526-79ca664e1cbe@gmail.com/

```
One of the changes in Sphinx 5.0.0 [1] says [sic]:

    5.0.0 final

     - #10474: language does not accept None as it value.
       The default value of language becomes to 'en' now.

[1]: https://www.sphinx-doc.org/en/master/changes.html#release-5-0-0-released-may-30-2022

It results in a new warning from Sphinx 5.0.0 [sic]:

    WARNING: Invalid configuration value found: 'language = None'.
    Update your configuration to a valid langauge code. Falling
    back to 'en' (English).

Silence the warning by using 'en'.
It works with all the Sphinx versions required for building
kernel documentation (1.7.9 or later).
```

Sphinx 5.0.0 was released May 29, so I don't know why we only hit this bug now.
