### ISSUE TITLE
query and eval: accessing column data by position raises errors

### ISSUE THREAD

**Issue by pyrito** [modin-project/modin#4580]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.2.1
- **Modin version** (`modin.__version__`): 0.15.0+7.g4ec7f634
- **Python version**: 3.9.12
- **Code we can use to reproduce**:
```
import pandas as pd

df = pd.DataFrame({'A' : [3]})
print(df.eval('A[0]'))
```
### Describe the problem
The code above should have an expected result of `3` and instead errors out. The snippet above exposes two critical issues:
1. Calling `eval` on an empty DataFrame is not feasible since we can have queries that access different indices of a column.
2. Since DataFrames are partitioned row-wise, we can have cases where partitions access indices that are not local.

### Source code / logs

<details>
<summary>Show stack trace</summary>

```
Traceback (most recent call last):
  File "/Users/kvelayutham/Documents/test.py", line 4, in <module>
    print(df.eval('A[0]'))
  File "/Users/kvelayutham/Documents/modin/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/pandas/dataframe.py", line 842, in eval
    new_query_compiler = self._query_compiler.eval(expr, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/logging/logger_metaclass.py", line 68, in log_wrap
    return method(*args, **kwargs)
  File "/Users/kvelayutham/Documents/modin/modin/core/storage_formats/pandas/query_compiler.py", line 1798, in eval
    pandas.DataFrame(columns=self.columns)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 584, in visit_Subscript
    v = value.value[result]
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/site-packages/pandas/core/series.py", line 955, in __getitem__
    return self._values[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

</details>

**Comment by mvashishtha** [comment]
Note that this a problem for query as well:

```python
import pandas
import modin.pandas as pd

pdf = pandas.DataFrame({"a": [0, 1, 2]})
df = pd.concat([pd.DataFrame(pdf[:1]), pd.DataFrame(pdf[1:])])
print(pdf.query('a == a[0]'))
# modin raises an error because the second row partition's a column only has rows 1 and 2.
print(df.query('a == a[0]'))
```

I think we should implement `query` and `eval` the way pandas does, which is to 1) evaluate the string as a python expression to get a selector from the dataframe using its public methods, then 2) get `df.loc[selector, :]`
