### ISSUE TITLE
`read_csv` throws error during reading from s3

### ISSUE THREAD

**Issue by prutskov** [modin-project/modin#4658]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Modin version** (`modin.__version__`): 06ec64bedc2ace639af09759053182472fdd6544
- **Python version**: 3.8.13
- **Code we can use to reproduce**:

```python
import modin.pandas as pd

s3_path = "s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv"
df = pd.read_csv(s3_path, parse_dates=["tpep_pickup_datetime", "tpep_dropoff_datetime"], nrows=10,  storage_options={"anon": True})
print(df)

```

### Describe the problem
`read_csv` throws error during reading from s3. The root cause is unhandled exception here: https://github.com/modin-project/modin/blob/eddfda4b521366c628596dcb5c21775c7f50eec1/modin/core/io/file_dispatcher.py#L276

### Source code / logs

```shell
File "C:\Users\79049\Documents\projects\modin\modin\core\io\text\text_file_dispatcher.py", line 641, in check_parameters_support
    if not cls.file_exists(
  File "C:\Users\79049\Documents\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\Users\79049\Documents\projects\modin\modin\core\io\file_dispatcher.py", line 275, in file_exists
    exists = s3fs.exists(file_path) or exists
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\fsspec\asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\fsspec\asyn.py", line 66, in sync
    raise return_result
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\fsspec\asyn.py", line 26, in _runner
    result[0] = await coro
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 888, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 1140, in _info
    out = await self._call_s3(
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 325, in _call_s3
    await self.set_session()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 473, in set_session
    self._s3 = await s3creator.__aenter__()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\session.py", line 22, in __aenter__
    self._client = await self._coro
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\session.py", line 102, in _create_client
    credentials = await self.get_credentials()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\session.py", line 133, in get_credentials
    self._credentials = await (self._components.get_component(
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\credentials.py", line 814, in load_credentials
    creds = await provider.load()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\credentials.py", line 486, in load
    metadata = await fetcher.retrieve_iam_role_credentials()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\utils.py", line 175, in retrieve_iam_role_credentials
    token = await self._fetch_metadata_token()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\utils.py", line 88, in _fetch_metadata_token
    response = await session.send(request.prepare())
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\httpsession.py", line 211, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://169.254.169.254/latest/api/token"
```

**Comment by anmyachev** [comment]
I have another problem when trying to run the reproducer. Is it because I don't have credentials configured in some default folder?

Logs:
```python
Traceback (most recent call last):
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\httpsession.py", line 178, in send
    response = await self._session.request(
  File "...\Miniconda3\envs\modin\lib\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "...\Miniconda3\envs\modin\lib\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "...\Miniconda3\envs\modin\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerTimeoutError: Timeout on reading data from socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_read_csv.py", line 4, in <module>
    df = pd.read_csv(s3_path, parse_dates=["tpep_pickup_datetime", "tpep_dropoff_datetime"], nrows=10,  storage_options={"anon": True})
  File "C:\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\projects\modin\modin\pandas\io.py", line 140, in read_csv
    return _read(**kwargs)
  File "C:\projects\modin\modin\pandas\io.py", line 61, in _read
    pd_obj = FactoryDispatcher.read_csv(**kwargs)
  File "C:\projects\modin\modin\core\execution\dispatching\factories\dispatcher.py", line 185, in read_csv
    return cls.__factory._read_csv(**kwargs)
  File "C:\projects\modin\modin\core\execution\dispatching\factories\factories.py", line 217, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "C:\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\projects\modin\modin\core\io\file_dispatcher.py", line 152, in read
    query_compiler = cls._read(*args, **kwargs)
  File "C:\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\projects\modin\modin\core\io\text\text_file_dispatcher.py", line 989, in _read
    use_modin_impl = cls.check_parameters_support(
  File "C:\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\projects\modin\modin\core\io\text\text_file_dispatcher.py", line 641, in check_parameters_support
    if not cls.file_exists(
  File "C:\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\projects\modin\modin\core\io\file_dispatcher.py", line 275, in file_exists
    exists = s3fs.exists(file_path) or exists
  File "...\Miniconda3\envs\modin\lib\site-packages\fsspec\asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "...\Miniconda3\envs\modin\lib\site-packages\fsspec\asyn.py", line 66, in sync
    raise return_result
  File "...\Miniconda3\envs\modin\lib\site-packages\fsspec\asyn.py", line 26, in _runner
    result[0] = await coro
  File "...\Miniconda3\envs\modin\lib\site-packages\s3fs\core.py", line 888, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "...\Miniconda3\envs\modin\lib\site-packages\s3fs\core.py", line 1140, in _info
    out = await self._call_s3(
  File "...\Miniconda3\envs\modin\lib\site-packages\s3fs\core.py", line 325, in _call_s3
    await self.set_session()
  File "...\Miniconda3\envs\modin\lib\site-packages\s3fs\core.py", line 473, in set_session
    self._s3 = await s3creator.__aenter__()
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\session.py", line 22, in __aenter__
    self._client = await self._coro
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\session.py", line 102, in _create_client
    credentials = await self.get_credentials()
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\session.py", line 133, in get_credentials        
    self._credentials = await (self._components.get_component(
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\credentials.py", line 814, in load_credentials   
    creds = await provider.load()
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\credentials.py", line 486, in load
    metadata = await fetcher.retrieve_iam_role_credentials()
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\utils.py", line 176, in retrieve_iam_role_credentials
    role_name = await self._get_iam_role(token)
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\utils.py", line 200, in _get_iam_role
    return await (await self._get_request(
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\utils.py", line 127, in _get_request
    response = await session.send(request.prepare())
  File "...\Miniconda3\envs\modin\lib\site-packages\aiobotocore\httpsession.py", line 212, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
```

**Comment by anmyachev** [comment]
Yes, pandas works well here.

**Comment by anmyachev** [comment]
@prutskov What package versions are you using? (`s3fs` and `botocore`)

**Comment by prutskov** [comment]
> @prutskov What package versions are you using? (`s3fs`, `botocore`, and `aiobotocore`)

I'm using the next:
```shell
s3fs                      2022.5.0                 pypi_0    pypi
botocore                  1.24.21                  pypi_0    pypi
aiobotocore               2.3.2                    pypi_0    pypi
```

**Comment by anmyachev** [comment]
I have the same package versions, but the error is different, hm.

**Comment by anmyachev** [comment]
@YarShev can you run reproducer? Maybe you will get the same issue as @prutskov got. Then maybe my error appears due to the peculiarities of my network settings.
