### ISSUE TITLE
Tests fail for `test_sql.py` in CI because `dfsql` and its dependencies won't install

### ISSUE THREAD

**Issue by vnlitvinov** [modin-project/modin#4802]
### Describe the problem

I'm guessing some PyPI package released a broken version of `mindsdb_sql` which fails to install.
This breaks all CI tests running `test_sql` now.

### Source code / logs
Error looks like this:
```
Run pip install "dfsql>=0.4.2" "pyparsing<=2.4.7" && pytest modin/experimental/sql/test/test_sql.py
Collecting dfsql>=0.4.2
  Downloading dfsql-0.6.8-py3-none-manylinux1_x86_64.whl (27 kB)
Collecting pyparsing<=2.4.7
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/share/miniconda3/envs/modin/lib/python3.8/site-packages (from dfsql>=0.4.2) (1.4.3)
Collecting confi>=0.0.4.1
  Downloading confi-0.0.4.1.tar.gz (3.2 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting mindsdb-sql>=0.0.17
  Downloading mindsdb_sql-0.3.[11](https://github.com/modin-project/modin/runs/7764784298?check_suite_focus=true#step:35:12).tar.gz (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.2/54.2 kB [19](https://github.com/modin-project/modin/runs/7764784298?check_suite_focus=true#step:35:20).2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-suxfqk3m/mindsdb-sql_98e078d7f9f34547b[33](https://github.com/modin-project/modin/runs/7764784298?check_suite_focus=true#step:35:34)4a659d7501bd0/setup.py", line 8, in <module>
          with open('requirements.txt') as req_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by vnlitvinov** [comment]
Upstream released `mindsdb-sql==0.3.12` which fixed the issue.

**Comment by pyrito** [comment]
@vnlitvinov I'm actually still seeing this here: https://github.com/modin-project/modin/actions/runs/3092084044/jobs/5003001062

I'm not sure if this is a flake. Will try re-running.

**Comment by mvashishtha** [comment]
cc @anmyachev @modin-project/modin-contributors @modin-project/modin-core this bug may be breaking CI for your PRs.
