### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by Sundar0989** [modin-project/modin#4952]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.15.0
- **Python version**: 3.8.13
-**Ray version**:1.7.0
- **Exact command to reproduce**:
import ray
ray.init(dashboard_host='xyz.somehost.com', dashboard_port=6380)

### Describe the problem

When I am trying to run the code, it says 

### Source code / logs

(raylet) Traceback (most recent call last):
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 375, in <module>
(raylet)     raise e
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 363, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 152, in run
(raylet)     modules = self._load_modules()
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 106, in _load_modules
(raylet)     c = cls(self)
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 152, in __init__
(raylet)     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in __init__
(raylet)     prometheus_exporter.new_stats_exporter(
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 332, in new_stats_exporter
(raylet)     exporter = PrometheusStatsExporter(
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 265, in __init__
(raylet)     self.serve_http()
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 319, in serve_http
(raylet)     start_http_server(
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
(raylet)     TmpServer.address_family, addr = _get_best_family(addr, port)
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
(raylet)     infos = socket.getaddrinfo(address, port)
(raylet)   File "/users/usr_name/.conda/envs/3point8/lib/python3.8/socket.py", line 918, in getaddrinfo
(raylet)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(raylet) socket.gaierror: [Errno -2] Name or service not known
2022-09-09 15:03:12,280	WARNING worker.py:1227 -- The agent on node xyz.somehost.com failed with the following error:
Traceback (most recent call last):
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 363, in <module>
    loop.run_until_complete(agent.run())
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 152, in run
    modules = self._load_modules()
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/agent.py", line 106, in _load_modules
    c = cls(self)
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 152, in __init__
    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/metrics_agent.py", line 75, in __init__
    prometheus_exporter.new_stats_exporter(
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 332, in new_stats_exporter
    exporter = PrometheusStatsExporter(
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 265, in __init__
    self.serve_http()
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/ray/_private/prometheus_exporter.py", line 319, in serve_http
    start_http_server(
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
    TmpServer.address_family, addr = _get_best_family(addr, port)
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
    infos = socket.getaddrinfo(address, port)
  File "/users/usr_name/.conda/envs/3point8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by mvashishtha** [comment]
@Sundar0989 thanks for reporting this issue. It's an error with ray that doesn't come from Modin at all. I can't tell what's going wrong.

Could you please open the same issue in the ray repo: https://github.com/ray-project/ray/issues/new/choose and link it here?

**Comment by Sundar0989** [comment]
Opened the ticket and linked it here as per request - https://github.com/ray-project/ray/issues/28415

**Comment by mvashishtha** [comment]
@Sundar0989 thank you! I'll close this issue, then.
