### ISSUE TITLE
BUG: NoneType is not callable

### ISSUE THREAD

**Issue by giucesar** [modin-project/modin#4990]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
dummy = pd.DataFrame(np.random.uniform(size=(10, 3)), columns=["a", "b", "c"])
dummy["aux"] = 1
```

### Issue Description

When running a code similar to the example, at the assignment step, it returns an exception: `TypeError: 'NoneType' object is not callable`

I tried with `dummy.assign(aux=1)` and `dummy.assign(aux=np.full(10, 1, dtype=np.int_)` and both raised the same exception.

```
python_abi                3.10                    2_cp310    conda-forge
modin-all                 0.11.3          py310hca03da5_0  
modin-core                0.11.3          py310hca03da5_0  
modin-dask                0.11.3          py310hca03da5_0  
dask                      2022.9.1           pyhd8ed1ab_0    conda-forge
pandas                    1.3.4           py310hdead3df_1    conda-forge
numpy                     1.22.4          py310h0a343b5_0    conda-forge
```

### Expected Behavior

Running without exception.

### Error Logs

<details>

```python-traceback

Traceback (most recent call last):
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/numpy/core/getlimits.py", line 649, in __init__
    self.dtype = numeric.dtype(int_type)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "REDACTED_HOME_FOLDER/.vscode/extensions/ms-python.python-2022.15.12581032/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "REDACTED_HOME_FOLDER/.vscode/extensions/ms-python.python-2022.15.12581032/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "REDACTED_HOME_FOLDER/.vscode/extensions/ms-python.python-2022.15.12581032/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "REDACTED_HOME_FOLDER/.vscode/extensions/ms-python.python-2022.15.12581032/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "REDACTED_HOME_FOLDER/.vscode/extensions/ms-python.python-2022.15.12581032/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "REDACTED_HOME_FOLDER/.vscode/extensions/ms-python.python-2022.15.12581032/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "REDACTED_PROJECT_FOLDER/src/tests/tests_group_1.py", line 165, in <module>
    test_function()
  File "REDACTED_PROJECT_FOLDER/src/tests/tests_group_1.py", line 42, in test_function
    _run_test(config_specs, size, test_name)
  File "REDACTED_PROJECT_FOLDER/src/REDACTED/__init__.py", line 26, in wrap_func
    result = func(*args, **kwargs)
  File "REDACTED_PROJECT_FOLDER/src/tests/tests_group_1.py", line 83, in _run_test
    REDACTED = REDACTED.initialize(size)
  File "REDACTED_PROJECT_FOLDER/src/REDACTED", line 104, in initialize
    dummy["aux"] = np.full(
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/modin/pandas/dataframe.py", line 2548, in __setitem__
    self.insert(loc=len(self.columns), column=key, value=value)
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/modin/pandas/dataframe.py", line 1199, in insert
    new_query_compiler = self._query_compiler.insert(loc, column, value)
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/modin/backends/pandas/query_compiler.py", line 2315, in insert
    new_modin_frame = self._modin_frame.apply_full_axis_select_indices(
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/modin/engines/base/frame/data.py", line 1449, in apply_full_axis_select_indices
    dict_indices = self._get_dict_of_block_index(axis ^ 1, numeric_indices)
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/modin/engines/base/frame/data.py", line 994, in _get_dict_of_block_index
    cumulative = np.append(bins[:-1].cumsum(), np.iinfo(bins.dtype).max)
  File "REDACTED_CONDA_ENV_FOLDER/lib/python3.10/site-packages/numpy/core/getlimits.py", line 651, in __init__
    self.dtype = numeric.dtype(type(int_type))
TypeError: 'NoneType' object is not callable

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.10.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.4
numpy            : 1.22.4
pytz             : 2022.2.1
dateutil         : 2.8.2
pip              : 22.2.2
setuptools       : 59.8.0
Cython           : None
pytest           : 7.1.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2022.8.2
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.55.2

</details>

**Comment by giucesar** [comment]
Changed to python 3.9 and it worked.
