### ISSUE TITLE
read_excel(sheet_name=None) not working

### ISSUE THREAD

**Issue by marcomilov** [modin-project/modin#512]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.3
- **Modin installed from (source or binary)**: source
- **Modin version**: 0.4.0
- **Python version**: 3.6
- **Exact command to reproduce**: `df.read_excel('File', sheet_name=None)`

### Describe the problem
When loading an excel file using sheet_name=None, which loads in all sheets. The script crashes. The script works when using pandas directly, so that shouldn't be a problem...

### Source code / logs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/marcomilov/Thesis/reportAutomater/reportForm/views.py", line 41, in post
    df_tup = self.fileService.extractRawSourceSheetFromExcel(file)
  File "/Users/marcomilov/Thesis/reportAutomater/reportForm/file_service.py", line 41, in extractRawSourceSheetFromExcel
    df = pd.read_excel(f, sheet_name=None)
  File "/usr/local/lib/python3.6/site-packages/modin/pandas/io.py", line 222, in read_excel
    return DataFrame(query_compiler=BaseFactory.read_excel(**kwargs))
  File "/usr/local/lib/python3.6/site-packages/modin/data_management/factories.py", line 95, in read_excel
    return cls._determine_engine()._read_excel(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/modin/data_management/factories.py", line 99, in _read_excel
    return cls.io_cls.read_excel(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/modin/engines/base/io.py", line 340, in read_excel
    **kwds
  File "/usr/local/lib/python3.6/site-packages/modin/engines/base/io.py", line 13, in from_pandas
    return cls.query_compiler_cls.from_pandas(df, cls.block_partitions_cls)
  File "/usr/local/lib/python3.6/site-packages/modin/data_management/query_compiler/pandas_query_compiler.py", line 500, in from_pandas
    new_index = df.index
AttributeError: 'collections.OrderedDict' object has no attribute 'index'

**Comment by devin-petersohn** [comment]
Hi @marcomilov, thanks for reporting this!

The change to fix this is relatively simple, we just need to add a conditional check based on the return type of the code that defaults to pandas, and return the proper `OrderedDict` instead. This line: https://github.com/modin-project/modin/blob/master/modin/engines/base/io.py#L313 is where that code should go.

I am labeling this as "Help Wanted" for the time. We have a backlog of other robustness changes and features we are working on, but I will make sure this will make it in the next release. Let me know if you are interested in contributing!

**Comment by ipacheco-uy** [comment]
@devin-petersohn i try to fix this in https://github.com/modin-project/modin/pull/532 but i don't know if its correct. I couldn't use the modin_df_equals_pandas to check if the values in the returned dict of each implementation where equal (because the modin df in the value has no query_compiler.

**Comment by devin-petersohn** [comment]
Resolved by #532
