### ISSUE TITLE
BUG: can't unwrap virtual partitions with axis=None

### ISSUE THREAD

**Issue by kukushking** [modin-project/modin#5164]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
from modin.distributed.dataframe.pandas import unwrap_partitions
import modin.pandas as pd

df = pd.DataFrame({"c0": [0, 1], "c1": [2, 3]})
unwrap_partitions(df)
> [[ObjectRef(c8ef45ccd0112571ffffffffffffffffffffffff0100000001000000)]]

dfc = pd.concat([df for _ in range(100)])
unwrap_partitions(dfc)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/workplace/temp/modintest/.venv/lib/python3.9/site-packages/modin/distributed/dataframe/pandas/partitions.py", line 106, in unwrap_partitions
    raise ValueError(
ValueError: Do not know how to unwrap 'PandasOnRayDataframeColumnPartition' underlying partitions
```

### Issue Description

Hi, looks like an attempt to unwrap partitions on dataframe that contains virtual partitions (I assume that's what you call them) fails if I just want to unwrap partitions as they are (axis=None).

I confirm it's still an issue in main - `0.16.0+26.g87c8f70`.

### Expected Behavior

No exception

### Error Logs

<details>

```python-traceback

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/workplace/temp/modintest/.venv/lib/python3.9/site-packages/modin/distributed/dataframe/pandas/partitions.py", line 106, in unwrap_partitions
    raise ValueError(
ValueError: Do not know how to unwrap 'PandasOnRayDataframeColumnPartition' underlying partitions

```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 87c8f70da9f8021e5eb005b20af839979d9f9bdb
python           : 3.9.4.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.6.0
Version          : Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

Modin dependencies
------------------
modin            : 0.16.0+26.g87c8f70
ray              : 2.0.1
dask             : 2022.10.0
distributed      : 2022.10.0
hdk              : None

pandas dependencies
-------------------
pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.5
dateutil         : 2.8.2
setuptools       : 49.2.1
pip              : 22.3
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.5.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.10.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 9.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.10.0
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by mvashishtha** [comment]
@kukushking thanks for reporting this bug. I can reproduce it locally at commit 87c8f70da9f8021e5eb005b20af839979d9f9bdb.

Virtual partitions contain a list of object references to physical blocks in order along some axis, so really modin dataframes with virtual partitions have a 3d array of blocks. I think `unwrap_partitions` should collapse each virtual partition's block list into a single physical partition with `force_materialization()`, then return a 2d array of physical blocks by getting `list_of_blocks[0]` (implementations for block partitions [here](https://github.com/modin-project/modin/blob/39ae12fa74ffb5d242cfbf9d1bfa83a8dc9f71a5/modin/core/dataframe/pandas/partitioning/partition.py#L55) and virtual partitions [here](https://github.com/modin-project/modin/blob/d6d503ac7c3028d871c34d9e99e925ddb0746df6/modin/core/dataframe/pandas/partitioning/axis_partition.py#L32)) from each partition. This seems like a fairly straightforward fix. I think we can get to this soon.

With `axis=0` and `axis=1`, we flatten the blocks along each axis, so virtual partitions are not a problem.
