### ISSUE TITLE
BUG: modin-on-hdk have inconsistent types for dates with some pd.read_csv arguments

### ISSUE THREAD

**Issue by Egor-Krivov** [modin-project/modin#5210]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import modin.config as cfg
cfg.IsExperimental.put(True)
cfg.Engine.put('Native')
cfg.StorageFormat.put('HDK')

import pandas as pd
import modin.pandas as mpd


keep_cols = ["pickup_datetime"]


def write(path, content):
    with open(path, 'w') as f:
        f.write(content)
HDK
data_2014 = """pickup_datetime,store_and_fwd_flag

2014-01-09 20:45:25,N
"""

data_2015 = """pickup_datetime
2015-01-15 19:05:39
"""

write('2014.csv', data_2014)
write('2015.csv', data_2015)

data_types_2014 = {"store_and_fwd_flag": "object"}

data_types_2015 = {}


def clean(ddf):
    to_drop = ddf.columns.difference(keep_cols)
    if not to_drop.empty:
        ddf = ddf.drop(columns=to_drop)
    return ddf


def load(path, dtypes, pd):
    df = clean(pd.read_csv(path, parse_dates=['pickup_datetime'], dtype=dtypes))
    df.shape
    print('\n\n\nPandas API response\n', df.dtypes)
    try:
        print('\n\n\nHDK hidden API resonse:')
        print(df._query_compiler._modin_frame._partitions[0][0].get())
    except (TypeError, AttributeError):
        print('Problem: couldnt locate type data')
    return df


def reproduce(data_types_2014, data_types_2015, pd):
    df1 = load('2014.csv', data_types_2014, pd)
    df2 = load('2015.csv', data_types_2015, pd)

    print('\n\n\nResult shape is:')
    print(pd.concat([df1, df2]).shape)
    print('*****No error found*****')


for d1, d2 in ((None, None), (data_types_2014, data_types_2015)):
    print('\n\n\n**********dtype is None: ', d1 is None)
    print('\n\n\n**********Pandas')
    reproduce(d1, d2, pd)
    print('\n\n\n**********Modin')
    reproduce(d1, d2, mpd)
```

### Background:
I am using modin on hdk on a real dataset.  The data loading consists of loading many csvs of about 2GB each. After the load I perform concatenation of cleaned data. During concatenation I get an error. The error is not present on Pandas, it is not present with modin on ray, it is only present with modin on HDK.

### Reproduction example
The issue only appears with the following conditions:
1. I am reading from a file (hence I write my data to a file in an example)
2. I provide dtype argument with "object" dtype to one `pd.read_csv` but not the other (hence I show that without that argument everything is fine).

I guess that the problem could be that one of the read csv defaults to pandas implementation (you can see that from a log) and the other is not, later they end up with different data types. I think that's a bug, because behavior right now is inconsistent between (pandas or modin on ray) vs (modin on HDK) and in the end with that defaulting we end up with inconsistent data types. Another issue is that pd.dtype is different from the internal information (provided in the log)

### Expected Behavior

To get consistent behavior between pandas and modin on hdk

### Error Logs

Here is a stdout of a provided code sample
```


**********dtype is None:  True



**********Pandas



Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
Problem: couldnt locate type data



Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
Problem: couldnt locate type data



Result shape is:
(2, 1)
*****No error found*****



**********Modin
FutureWarning: the 'mangle_dupe_cols' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'mangle_dupe_cols'
FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.





Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
pyarrow.Table
F_pickup_datetime: timestamp[s]
----
F_pickup_datetime: [[2014-01-09 20:45:25]]
FutureWarning: the 'mangle_dupe_cols' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'mangle_dupe_cols'
FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.





Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
pyarrow.Table
F_pickup_datetime: timestamp[s]
----
F_pickup_datetime: [[2015-01-15 19:05:39]]



Result shape is:
(2, 1)
*****No error found*****



**********dtype is None:  False



**********Pandas



Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
Problem: couldnt locate type data



Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
Problem: couldnt locate type data



Result shape is:
(2, 1)
*****No error found*****



**********Modin
FutureWarning: the 'mangle_dupe_cols' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'mangle_dupe_cols'
FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


UserWarning: `read_csv` is not currently supported by ExperimentalHdkOnNative, defaulting to pandas implementation.
Please refer to https://modin.readthedocs.io/en/stable/supported_apis/defaulting_to_pandas.html for explanation.
FutureWarning: the 'mangle_dupe_cols' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'mangle_dupe_cols'
FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.





Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
pyarrow.Table
F_pickup_datetime: timestamp[ns]
----
F_pickup_datetime: [[2014-01-09 20:45:25.000000000]]
FutureWarning: the 'mangle_dupe_cols' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'mangle_dupe_cols'
FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.





Pandas API response
 pickup_datetime    datetime64[ns]
dtype: object



HDK hidden API resonse:
pyarrow.Table
F_pickup_datetime: timestamp[s]
----
F_pickup_datetime: [[2015-01-15 19:05:39]]



Result shape is:
Traceback (most recent call last):
  File "./taxi_ml/bug1.py", line 67, in <module>
    reproduce(d1, d2, mpd)
  File "./taxi_ml/bug1.py", line 58, in reproduce
    print(pd.concat([df1, df2]).shape)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/pandas/base.py", line 3429, in __getattribute__
    attr = super().__getattribute__(item)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 344, in shape
    return len(self.index), len(self.columns)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/pandas/base.py", line 3429, in __getattribute__
    attr = super().__getattribute__(item)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/pandas/base.py", line 540, in _get_index
    return self._query_compiler.index
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 471, in _get_index
    return self._modin_frame.index
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1892, in _get_index
    self._execute()
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1669, in _execute
    new_table = self._execute_arrow()
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1759, in _execute_arrow
    return self._arrow_concat(self._op.input)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1848, in _arrow_concat
    return pyarrow.concat_tables(frame._execute_arrow() for frame in frames)
  File "pyarrow/table.pxi", line 2338, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Schema at index 1 was different: 
F___index__: int64
F_pickup_datetime: timestamp[ns]
vs
F___index__: int64
F_pickup_datetime: timestamp[s]
```

### Installed Versions

<details>
>>> import pandas
>>> pandas.show_versions()
/nfs/site/home/ekrivov/large/tryrun1/miniconda3/envs/taxi/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

INSTALLED VERSIONS
------------------
commit           : 91111fd99898d9dcaa6bf6bedb662db4108da6e6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-124-generic
Version          : #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.1
numpy            : 1.23.4
pytz             : 2022.6
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.2.2
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.5
brotli           : None
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : 2.8.3
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by Egor-Krivov** [comment]
@modin-project/modin-hdk

**Comment by dchigarev** [comment]
the root cause may also be related to #3485

**Comment by jbrockmendel** [comment]
when i read data_2014 and data_2015 with pyarrow directly (not hdk) i get `timestamp[s]` for both.  so in the example here im going to manually cast one to `timestamp[ns]` to show how you can handle the mismatch

```
from io import BytesIO

import pyarrow as pa
import pyarrow.csv

import pandas as pd  # using pandas main 2022-11-14

data_2014 = """pickup_datetime,store_and_fwd_flag

2014-01-09 20:45:25,N
"""

data_2015 = """pickup_datetime
2015-01-15 19:05:39
"""

b1 = BytesIO(data_2014.encode("ascii"))
b2 = BytesIO(data_2015.encode("ascii"))

obj1 = pa.csv.read_csv(b1)
obj2 = pa.csv.read_csv(b2)

arr1 = obj1["pickup_datetime"]
arr2 = obj2["pickup_datetime"]

dtype1 = pd.ArrowDtype(pa.timestamp("s"))
dtype2 = pd.ArrowDtype(pa.timestamp("ns"))
```

Here I constructed dtype1 and dtype2 explicitly to get mismatched dtypes.  In practice, you should construct these with `dtype1 = pd.ArrowDtype(arr1.type)` and `dtype2 = pd.ArrowDtype(arr2.type)`.  Once you have these dtypes...

```
left = dtype1.construct_array_type()._from_sequence(arr1, dtype=dtype1)
right = dtype2.construct_array_type()._from_sequence(arr2, dtype=dtype2)

dtype = pd.core.dtypes.cast.find_common_type([left.dtype, right.dtype])
```

If you are concating these in modin and only need to cast them to a common dtype, then `dtype` here is what you want.  If you are concating them in pandas:

```
ser1 = pd.Series(left)
ser2 = pd.Series(right)

result = pd.concat([ser1, ser2])
```

**Comment by AndreyPavlenko** [comment]
@Egor-Krivov could you please check if the issue is still exists? The attached code works for me on the master branch.

**Comment by YarShev** [comment]
HDK engine is deprecated and will be removed in a future version.
