### ISSUE TITLE
setitem fails on a query result

### ISSUE THREAD

**Issue by williamma12** [modin-project/modin#525]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 10.14.3
- **Modin installed from (source or binary)**: source
- **Modin version**: current master (0.4.0)
- **Python version**: 3.6.1

### Describe the problem
doing a `__setitem__` operation after a `query` operation fails with a `RayTaskError` that is triggered by a `ValueError`

### Source code / logs
```
import modin.pandas as pd

df = pd.DataFrame({"col1": [0,1,2,3,4], "col2": [5,6,7,8,4]})
df1 = df.query("col1==col2")
df1['col1'] = df1['col1'] + 11
``` 
Fails with the following error
```
RayTaskError                              Traceback (most recent call last)
~/Documents/modin/venv/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/Documents/modin/venv/lib/python3.6/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403
    404             return _default_pprint(obj, self, cycle)

~/Documents/modin/venv/lib/python3.6/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

~/Documents/modin/modin/pandas/dataframe.py in __repr__(self)
    136         num_cols = 30
    137
--> 138         result = repr(self._build_repr_df(num_rows, num_cols))
    139         if len(self.index) > num_rows or len(self.columns) > num_cols:
    140             # The split here is so that we don't repr pandas row lengths.

~/Documents/modin/modin/pandas/dataframe.py in _build_repr_df(self, num_rows, num_cols)
    107
    108         if len(self.columns) <= num_cols:
--> 109             head_front = head.to_pandas()
    110             # Creating these empty to make the concat logic simpler
    111             head_back = pandas.DataFrame()

~/Documents/modin/modin/backends/pandas/query_compiler.py in to_pandas(self)
    468             Pandas DataFrame of the DataManager.
    469         """
--> 470         df = self.data.to_pandas(is_transposed=self._is_transposed)
    471         if df.empty:
    472             if len(self.columns) != 0:

~/Documents/modin/modin/engines/base/frame/partition_manager.py in to_pandas(self, is_transposed)
    457         else:
    458             retrieved_objects = [
--> 459                 [obj.to_pandas() for obj in part] for part in self.partitions
    460             ]
    461             if all(

~/Documents/modin/modin/engines/base/frame/partition_manager.py in _get_partitions(self)
     66                             if self.block_lengths[i] != 0 and self.block_widths[j] != 0
     67                         ]
---> 68                         for i in range(len(self._partitions_cache))
     69                     ]
     70                     if len(row)

~/Documents/modin/modin/engines/base/frame/partition_manager.py in <listcomp>(.0)
     66                             if self.block_lengths[i] != 0 and self.block_widths[j] != 0
     67                         ]
---> 68                         for i in range(len(self._partitions_cache))
     69                     ]
     70                     if len(row)

~/Documents/modin/modin/engines/base/frame/partition_manager.py in <listcomp>(.0)
     64                             self._partitions_cache[i][j]
     65                             for j in range(len(self._partitions_cache[i]))
---> 66                             if self.block_lengths[i] != 0 and self.block_widths[j] != 0
     67                         ]
     68                         for i in range(len(self._partitions_cache))

~/Documents/modin/modin/engines/ray/generic/frame/partition_manager.py in block_lengths(self)
     32             self._lengths_cache = np.array(
     33                 ray.get([obj.length().oid for obj in self._partitions_cache.T[0]])
---> 34                 if len(self._partitions_cache.T) > 0
     35                 else []
     36             )

~/Documents/modin/venv/lib/python3.6/site-packages/ray/worker.py in get(object_ids, worker)
   2200                 if isinstance(value, RayTaskError):
   2201                     last_task_error_raise_time = time.time()
-> 2202                     raise value
   2203             return values
   2204         else:

RayTaskError: ray_worker (pid=3676, host=airbears2-10-142-32-196.airbears2.1918.berkeley.edu)
ray.worker.RayTaskError: ray_worker (pid=3676, host=airbears2-10-142-32-196.airbears2.1918.berkeley.edu)
  File "/Users/William/Documents/modin/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 84, in deploy_ray_func
    return func(*args)
  File "/Users/William/Documents/modin/modin/engines/base/frame/axis_partition.py", line 187, in deploy_axis_func
    result = func(dataframe, **kwargs)
  File "/Users/William/Documents/modin/modin/backends/pandas/query_compiler.py", line 172, in helper
    return pandas_func(df, internal_indices=internal_indices, **kwargs)
  File "/Users/William/Documents/modin/modin/backends/pandas/query_compiler.py", line 2334, in setitem
    df[df.columns[internal_indices[0]]] = value
  File "/Users/William/Documents/modin/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3370, in __setitem__
    self._set_item(key, value)
  File "/Users/William/Documents/modin/venv/lib/python3.6/site-packages/pandas/core/frame.py", line 3446, in _set_item
    NDFrame._set_item(self, key, value)
  File "/Users/William/Documents/modin/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 3172, in _set_item
    self._data.set(key, value)
  File "/Users/William/Documents/modin/venv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1074, in set
    blk.set(blk_locs, value_getitem(val_locs))
  File "/Users/William/Documents/modin/venv/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 343, in set
    self.values[locs] = values
ValueError: assignment destination is read-only
```

**Comment by devin-petersohn** [comment]
Closing #525 via #545.
