### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by MikeHibbert** [modin-project/modin#536]
### System information
- Linux Ubuntu 16.04)
- installed from pip
- 0.4.0
- 3.6.8
- import modin.pandas as pd

### Describe the problem
after installing modin using 'pip install modin[dask]' I open the python shell and type:

import modin.pandas as pd

### Source code / logs
python traceback:

>>> import modin.pandas as pd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import modin.pandas as pd
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/pandas/__init__.py", line
 85, in <module>
    from .concat import concat
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/pandas/concat.py", line 7
, in <module>
    from .dataframe import DataFrame
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/pandas/dataframe.py", lin
e 38, in <module>
    from .utils import from_pandas, to_pandas, _inherit_docstrings
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/pandas/utils.py", line 5,
 in <module>
    from ..data_management.factories import BaseFactory
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/data_management/factories
.py", line 198, in <module>
    class PandasOnRayFactory(BaseFactory):
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/data_management/factories
.py", line 200, in PandasOnRayFactory
    from modin.engines.ray.pandas_on_ray.io import PandasOnRayIO
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray
/io.py", line 11, in <module>
    import py
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/py/__init__.py", line 153, in <
module>
    'Syslog'             : '._log.log:Syslog',
  File "/home/mike/Documents/python/dbi_cloud/lib/python3.6/site-packages/py/_vendored_packages/apipkg.py
", line 63, in initpkg
    for module in sys.modules.values():
RuntimeError: dictionary changed size during iteration

**Comment by devin-petersohn** [comment]
Hi @MikeHibbert, thanks for posting!

For the error you're seeing, does `pip install -U py` fix the issue? The `py` dependency is failing to load, and updating may fix the issue.

If you're trying to use the Dask engine, Modin needs an environment variable set so it connects to the correct library:

```
MODIN_ENGINE=dask ipython
```

This isn't documented anywhere because it's still a WIP, but feel free to try it out and let us know!

**Comment by MikeHibbert** [comment]
Hi @devin-petersohn 

Yep that sorted the issue out for me!

Thanks for the help!

**Comment by devin-petersohn** [comment]
Closing this. Feel free to reopen if the discussion should continue or if issue was not resolved.
