### ISSUE TITLE
AttributeError: module 'modin.pandas' has no attribute 'datetime'

### ISSUE THREAD

**Issue by jsrpy** [modin-project/modin#542]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14 
- **Modin installed from (source or binary)**: pip install 
- **Modin version**: 0.4.0
- **Python version**: 3.6.4
- **Exact command to reproduce**: 

```
import modin.pandas as pd
from datetime import datetime

def dateparse(x): return pd.datetime.strptime(x, '%Y-%m-%d %H:%M:%S')

df = pd.read_csv(
    "./GBPUSD_1H_stick.csv",
    parse_dates=["Gmt time"], date_parser=dateparse)
```

### Describe the problem

Basically the customised `date_parser` is causing the error. Without that latter part, everything is okay.

### Source code / logs

```
---------------------------------------------------------------------------
RayTaskError                              Traceback (most recent call last)
 in ()
      1 df = pd.read_csv(
      2     "./GBPUSD_1H_stick.csv",
----> 3     parse_dates=["GMT"], date_parser=dateparse)

~/miniconda3/lib/python3.6/site-packages/modin/pandas/io.py in parser_func(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
     94     ):
     95         _, _, _, kwargs = inspect.getargvalues(inspect.currentframe())
---> 96         return _read(**kwargs)
     97 
     98     return parser_func

~/miniconda3/lib/python3.6/site-packages/modin/pandas/io.py in _read(**kwargs)
    107         kwargs: Keyword arguments in pandas.read_csv
    108     """
--> 109     pd_obj = BaseFactory.read_csv(**kwargs)
    110     # This happens when `read_csv` returns a TextFileReader object for iterating through
    111     if isinstance(pd_obj, pandas.io.parsers.TextFileReader):

~/miniconda3/lib/python3.6/site-packages/modin/data_management/factories.py in read_csv(cls, **kwargs)
     53     @classmethod
     54     def read_csv(cls, **kwargs):
---> 55         return cls._determine_engine()._read_csv(**kwargs)
     56 
     57     @classmethod

~/miniconda3/lib/python3.6/site-packages/modin/data_management/factories.py in _read_csv(cls, **kwargs)
     57     @classmethod
     58     def _read_csv(cls, **kwargs):
---> 59         return cls.io_cls.read_csv(**kwargs)
     60 
     61     @classmethod

~/miniconda3/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/io.py in read_csv(cls, filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, doublequote, delim_whitespace, low_memory, memory_map, float_precision)
    361             "float_precision": float_precision,
    362         }
--> 363         return cls._read(**kwargs)
    364 
    365     @classmethod

~/miniconda3/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/io.py in _read(cls, filepath_or_buffer, **kwargs)
    431         else:
    432             return cls._read_csv_from_file_pandas_on_ray(
--> 433                 filepath_or_buffer, filtered_kwargs
    434             )
    435 

~/miniconda3/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/io.py in _read_csv_from_file_pandas_on_ray(cls, filepath, kwargs)
    211         index_col = kwargs.get("index_col", None)
    212         if index_col is None:
--> 213             new_index = pandas.RangeIndex(sum(ray.get(index_ids)))
    214         else:
    215             new_index_ids = get_index.remote([empty_pd_df.index.name], *index_ids)

~/miniconda3/lib/python3.6/site-packages/ray/worker.py in get(object_ids, worker)
   2200                 if isinstance(value, RayTaskError):
   2201                     last_task_error_raise_time = time.time()
-> 2202                     raise value
   2203             return values
   2204         else:

RayTaskError: ray_worker (pid=7133, host=Chings-MBP)
  File "", line 1, in dateparse
AttributeError: module 'modin.pandas' has no attribute 'datetime'

During handling of the above exception, another exception occurred:

ray_worker (pid=7133, host=Chings-MBP)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 3187, in converter
    dayfirst=dayfirst),
  File "pandas/_libs/tslibs/parsing.pyx", line 440, in pandas._libs.tslibs.parsing.try_parse_dates
  File "pandas/_libs/tslibs/parsing.pyx", line 437, in pandas._libs.tslibs.parsing.try_parse_dates
  File "", line 1, in dateparse
AttributeError: module 'modin.pandas' has no attribute 'datetime'

During handling of the above exception, another exception occurred:

ray_worker (pid=7133, host=Chings-MBP)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/modin/engines/ray/pandas_on_ray/io.py", line 647, in _read_csv_with_offset_pandas_on_ray
    pandas_df = pandas.read_csv(BytesIO(to_read), **kwargs)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 2068, in read
    names, data = self._do_date_conversions(names, data)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1820, in _do_date_conversions
    self.index_names, names, keep_date_col=self.keep_date_col)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers

.py", line 3223, in _process_date_conversion
    data_dict[colspec] = converter(data_dict[colspec])
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 3190, in converter
    return generic_parser(date_parser, *date_cols)
  File "/Users/jsnceo/miniconda3/lib/python3.6/site-packages/pandas/io/date_converters.py", line 40, in generic_parser
    results[i] = parse_func(*args)
  File "", line 1, in dateparse
AttributeError: module 'modin.pandas' has no attribute 'datetime'
```

Attached with a sample csv data:
[GBPUSD_1H_stick.csv.zip](https://github.com/modin-project/modin/files/3071456/GBPUSD_1H_stick.csv.zip)

**Comment by devin-petersohn** [comment]
Hi @jsrpy, thanks for posting!

Right now we are ignoring this import, though it is reasonable to add it. This is a useful addition, and a good first issue. We just need to add it to the `__init__` and remove it from the list of ignored modules in `modin/pandas/test/test_api.py`.

If this hasn't been picked up by someone by the time #522 is finished and merged, I will go ahead and do it to ensure it makes the next release. Thanks again for posting!

**Comment by jsrpy** [comment]
@devin-petersohn Hmmm right. Perhaps If I have time during the weekend I will fix it.

**Comment by devin-petersohn** [comment]
Closing #542 vis #564
