### ISSUE TITLE
BUG: Modin on HDK fails during apply call

### ISSUE THREAD

**Issue by Egor-Krivov** [modin-project/modin#5803]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
# %%
import modin.pandas as pd

import modin.config as cfg
cfg.StorageFormat.put('hdk')

# import pandas as pd

import random
import string

def get_random_string(length):
    return ''.join(random.choice(string.ascii_letters) for i in range(length))

# %%
s2id = {get_random_string(20): i for i in range(1000_000)}

# %%
df = pd.DataFrame({'user': list(s2id.keys()) * 10})

# %%
df['new_id'] = df['user'].apply(lambda x: s2id[x]).astype('int64')

# %%
print(df)
```

### Issue Description

Modin on HDK fails, executing the code

### Expected Behavior

It's a bug

### Error Logs

<details>

```python-traceback

UserWarning: Distributing <class 'dict'> object. This may take some time.
UserWarning: <function DataFrame.to_numpy> is not currently supported by ExperimentalHdkOnNative, defaulting to pandas implementation.
Please refer to https://modin.readthedocs.io/en/stable/supported_apis/defaulting_to_pandas.html for explanation.
UserWarning: <function DataFrame.applymap> is not currently supported by ExperimentalHdkOnNative, defaulting to pandas implementation.
Traceback (most recent call last):
  File "hdk_test.py", line 25, in <module>
    print(df)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/pandas/base.py", line 3948, in __str__
    return repr(self)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 246, in __repr__
    result = repr(self._build_repr_df(num_rows, num_cols))
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/pandas/base.py", line 185, in _build_repr_df
    if len(self.index) == 0 or (self._is_dataframe and len(self.columns) == 0):
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/pandas/base.py", line 4023, in __getattribute__
    attr = super().__getattribute__(item)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/pandas/base.py", line 591, in _get_index
    return self._query_compiler.index
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 471, in _get_index
    return self._modin_frame.index
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 2109, in _get_index
    self._execute()
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 1895, in _execute
    new_partitions = self._partition_mgr_cls.run_exec_plan(
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/logging/logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py", line 302, in run_exec_plan
    at = omniSession.executeRA(cmd_prefix + calcite_json)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py", line 91, in executeRA
    return cls._executeRelAlgJson(ra)
  File "/nfs/site/home/ekrivov/large/miniconda3/envs/hm/lib/python3.8/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/hdk_worker.py", line 76, in _executeRelAlgJson
    res = rel_alg_executor.execute()
  File "_sql.pyx", line 103, in pyhdk._sql.RelAlgExecutor.execute
RuntimeError: Hash join failed, reason(s): Could not build a 1-to-1 correspondence for columns involved in equijoin | Cannot join on rowid | Cannot fall back to loop join for non-trivial inner table size


```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : a6862b51cc1d4be328f8f52a5fb69fb0650f7e97
python           : 3.8.15.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-136-generic
Version          : #153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US
LOCALE           : en_US.ISO8859-1

Modin dependencies
------------------
modin            : 0.19.0+6.ga6862b51
ray              : 2.2.0
dask             : 2023.3.0
distributed      : 2023.3.0
hdk              : present

pandas dependencies
-------------------
pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2022.7
dateutil         : 2.8.2
setuptools       : 65.5.0
pip              : 22.3.1
Cython           : 0.29.32
pytest           : 7.2.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.1.2
IPython          : 8.7.0
pandas_datareader: None
bs4              : 4.11.2
bottleneck       : 1.3.5
brotli           : 
fastparquet      : None
fsspec           : 2022.11.0
gcsfs            : None
matplotlib       : 3.6.2
numba            : None
numexpr          : 2.8.4
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 8.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.9.3
snappy           : None
sqlalchemy       : 1.4.39
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

**Comment by Garra1980** [comment]
can't reproduced for
modin-hdk                 0.19.0          py310hff52083_0    conda-forge
pyhdk                     0.4.0           py310h1234567_0_cpu    conda-forge
