### ISSUE TITLE
BUG: Columns insertion doesn't work with `.loc` accessor

### ISSUE THREAD

**Issue by dchigarev** [modin-project/modin#6774]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
from modin.pandas.test.utils import create_test_dfs

md_df, pd_df = create_test_dfs({"a": [1, 2, 3, 4]})

pd_df.loc[:, "b"] = [10, 20, 30, 40] # works correctly
print(pd_df) 
md_df.loc[:, "b"] = [10, 20, 30, 40] # fails
print(md_df)
```

### Issue Description

Should match pandas

### Expected Behavior

Should match pandas

### Error Logs

<details>

```python-traceback

   a   b
0  1  10
1  2  20
2  3  30
3  4  40
Traceback (most recent call last):
  File "/repos/modin/t3.py", line 7, in <module>
    md_df.loc[:, "b"] = [10, 20, 30, 40]
  File "/repos/modin/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
  File "/repos/modin/modin/pandas/indexing.py", line 794, in __setitem__
    self._setitem_with_new_columns(row_loc, col_loc, item)
  File "/repos/modin/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
  File "/repos/modin/modin/pandas/indexing.py", line 822, in _setitem_with_new_columns
    raise ValueError(
ValueError: Must have equal len keys and value when setting with an iterable


```

</details>

### Installed Versions

<details>

Replace this line with the output of pd.show_versions()

</details>

**Comment by dchigarev** [comment]
a workaround would be:
```python
# df.loc[:, "col_name"] = [1, 2, 3]
df["col_name"] = [1, 2, 3]
```
