### ISSUE TITLE
BUG: HDK raises exception in nunique

### ISSUE THREAD

**Issue by gshimansky** [modin-project/modin#6895]
### Modin version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest released version of Modin.

- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)

### Reproducible Example

```python
import sys
import time
from collections import OrderedDict
import os
os.environ["MODIN_EXPERIMENTAL"] = "true"
os.environ["MODIN_STORAGE_FORMAT"] = "hdk"
os.environ["MODIN_ENGINE"] = "native"
import modin.pandas as pd

def read(filename):
    column_types = {
        "trip_id": "int64",
        "vendor_id": "string",
        "pickup_datetime": "object",
        "dropoff_datetime": "object",
        "store_and_fwd_flag": "string",
        "rate_code_id": "int64",
        "pickup_longitude": "float64",
        "pickup_latitude": "float64",
        "dropoff_longitude": "float64",
        "dropoff_latitude": "float64",
        "passenger_count": "int64",
        "trip_distance": "float64",
        "fare_amount": "float64",
        "extra": "float64",
        "mta_tax": "float64",
        "tip_amount": "float64",
        "tolls_amount": "float64",
        "ehail_fee": "float64",
        "improvement_surcharge": "float64",
        "total_amount": "float64",
        "payment_type": "string",
        "trip_type": "float64",
        "pickup": "string",
        "dropoff": "string",
        "cab_type": "string",
        "precipitation": "float64",
        "snow_depth": "int64",
        "snowfall": "float64",
        "max_temperature": "int64",
        "min_temperature": "int64",
        "average_wind_speed": "float64",
        "pickup_nyct2010_gid": "float64",
        "pickup_ctlabel": "float64",
        "pickup_borocode": "float64",
        "pickup_boroname": "string",
        "pickup_ct2010": "float64",
        "pickup_boroct2010": "float64",
        "pickup_cdeligibil": "string",
        "pickup_ntacode": "string",
        "pickup_ntaname": "string",
        "pickup_puma": "float64",
        "dropoff_nyct2010_gid": "float64",
        "dropoff_ctlabel": "float64",
        "dropoff_borocode": "float64",
        "dropoff_boroname": "string",
        "dropoff_ct2010": "float64",
        "dropoff_boroct2010": "float64",
        "dropoff_cdeligibil": "string",
        "dropoff_ntacode": "string",
        "dropoff_ntaname": "string",
        "dropoff_puma": "float64",
    }

    all_but_dates = {
        col: valtype
        for (col, valtype) in column_types.items()
        if valtype not in ["timestamp"]
    }
    dates_only = [
        col for (col, valtype) in column_types.items() if valtype in ["timestamp"]
    ]

    df = pd.read_csv(
        filename,
        header=0,
        dtype={**all_but_dates, "payment_type_class": "string"},
        parse_dates=dates_only,
    )

    df.shape  # to trigger real execution on omnisci
    return df

def hdk_warmap_query():
    # Trigger HDK initialization by executing a quick trivial
    # query. It is necessary for correct time measurement of ETL part.
    df = pd.DataFrame({"a": [1, 2, 3]})
    df = df + 1
    df.shape


def measure(func, *args, **kw):
    t0 = time.time()
    res = func(*args, **kw)
    t1 = time.time()
    return res, t1 - t0
    
def run(input_file):
    hdk_warmap_query()

    res = OrderedDict()
    df, res["Reading"] = measure(read, input_file)
    df["pickup_datetime"] = df["pickup_datetime"].astype("object")
    df["dropoff_datetime"] = df["dropoff_datetime"].astype("object")

    # Begin RandomForestClassifier part here
    payment_mapping = {
        "cash": 0,
        "credit": 1,
        "other": 2
    }

    # Create a new column 'payment_type_class' with the mapped values
    df["payment_type_class"] = df["payment_type"].map(payment_mapping)
    df["payment_type_class"] = df["payment_type_class"].astype(int)  # Convert to int

    # Check the number of unique classes in the target variable
    target = df["payment_type_class"]
    num_classes = target.nunique()
    print(f"Number of classes: {num_classes}")
    return res

def main():
    if len(sys.argv) != 2:
        print(f"USAGE: python taxi.py <data file name>")
        return
    result = run(sys.argv[1])
    print(result)


if __name__ == "__main__":
    main()
```

### Issue Description

This code runs successfully on pandas and modin on ray but fails on HDK.

### Expected Behavior

To run successfully as python backends do.

### Error Logs

<details>

```python-traceback
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 394, in serialize_dtype
    type_info = {"type": self._DTYPE_STRINGS[dtype.name], "nullable": True}
                         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'object'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/tests/dspw/taxi.py", line 145, in <module>
    main()
  File "/home/jovyan/tests/dspw/taxi.py", line 140, in main
    result = run(sys.argv[1])
             ^^^^^^^^^^^^^^^^
  File "/home/jovyan/tests/dspw/taxi.py", line 132, in run
    num_classes = target.nunique()
                  ^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/pandas/series.py", line 2171, in nunique
    return super(Series, self).nunique(dropna=dropna)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/pandas/base.py", line 2191, in nunique
    self._query_compiler.nunique(axis=axis, dropna=dropna)
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 99, in method_wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 430, in nunique
    return self._agg("nunique")
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 99, in method_wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/storage_formats/hdk/query_compiler.py", line 472, in _agg
    new_frame = new_frame._set_index(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 2255, in _set_index
    obj = self._execute()
          ^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 2041, in _execute
    result = frame()
             ^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py", line 2081, in _materialize
    partitions = self._partition_mgr_cls.run_exec_plan(self._op)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/logging/logger_decorator.py", line 129, in run_and_log
    return obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py", line 254, in run_exec_plan
    calcite_json = CalciteSerializer().serialize(calcite_plan)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 106, in serialize
    return json.dumps({"rels": [self.serialize_item(node) for node in plan]})
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 106, in <listcomp>
    return json.dumps({"rels": [self.serialize_item(node) for node in plan]})
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 139, in serialize_item
    return self.serialize_node(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 178, in serialize_node
    return self.serialize_obj(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 207, in serialize_obj
    res[k] = self.serialize_item(v)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 145, in serialize_item
    return [self.serialize_item(v) for v in item]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 145, in <listcomp>
    return [self.serialize_item(v) for v in item]
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 141, in serialize_item
    return self.serialize_expr(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 252, in serialize_expr
    return self.serialize_typed_obj(expr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 228, in serialize_typed_obj
    res["type"] = self.serialize_dtype(obj._dtype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/.conda/envs/modin/lib/python3.11/site-packages/modin/experimental/core/execution/native/implementations/hdk_on_native/calcite_serializer.py", line 400, in serialize_dtype
    raise TypeError(f"Unsupported dtype: {dtype}")
TypeError: Unsupported dtype: object
```

</details>

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.11.7.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.0-91-generic
Version             : #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : None
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.3
pytz                : 2023.3.post1
dateutil            : 2.8.2
setuptools          : 69.0.3
pip                 : 23.3.2
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.3
IPython             : None
pandas_datareader   : None
bs4                 : None
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2023.12.2
gcsfs               : None
matplotlib          : None
numba               : None
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 12.0.1
pyreadstat          : None
pyxlsb              : None
s3fs                : 2023.12.2
scipy               : 1.12.0
sqlalchemy          : None
tables              : None
tabulate            : None
xarray              : None
xlrd                : None
zstandard           : None
tzdata              : 2023.4
qtpy                : None
pyqt5               : None
</details>

**Comment by gshimansky** [comment]
[taxi.csv](https://github.com/modin-project/modin/files/14087634/taxi.csv)
Attached is a data file for the reproducer.

**Comment by anmyachev** [comment]
Thanks @gshimansky!

@AndreyPavlenko shouldn't pandas be called when `TypeError: Unsupported dtype: object` occurs?

**Comment by AndreyPavlenko** [comment]
> @AndreyPavlenko shouldn't pandas be called when `TypeError: Unsupported dtype: object` occurs?

On this stage we can't fall back to pandas.

**Comment by YarShev** [comment]
@gshimansky, how urgent is this issue?

**Comment by gshimansky** [comment]
> @gshimansky, how urgent is this issue?

If the fix is easy then it would be nice to have it by the next modin release. If it is not then I suppose it is not hard just to plug the function with a pandas fallback.

**Comment by YarShev** [comment]
@gshimansky, from the discussion with @AndreyPavlenko, it is not that easy to fix the issue and we would have to look into the code. Since HDK is not the primary priority for now, I am tagging the issue with P3. Hope you will find a workaround.

**Comment by AndreyPavlenko** [comment]
@gshimansky The exception is not caused by ``nunique``, but ``.astype("object")``. ``nunique`` triggers lazy execution and it can not fall back to pandas. Do you really need these casts? As I see, the same types are specified in column_types for these columns?

**Comment by gshimansky** [comment]
Ok I see. This is the user code, not mine, so if you are saying that this cannot be done I will talk with the person who wrote this code to convince to change it.

**Comment by gshimansky** [comment]
Removing conversion into object type fixes this problem.
