### ISSUE TITLE
Some operations (e.g. `applymap`, `groupby`) are not working with Dask

### ISSUE THREAD

**Issue by devin-petersohn** [modin-project/modin#977]
### Describe the problem

Dask has a serialization issue with some of the way we submit the functions. It appears as if the serializer is attempting to pickle the whole package and send that to the workers. It fails because we start a `LocalCluster` if there isn't one already, and the workers are not authorized to start their own cluster. See logs below.

### Source code / logs

```
UserWarning: 
Port 8787 is already in use. 
Perhaps you already have a cluster running?
Hosting the diagnostics dashboard on a random port instead.
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py:530> exception=AssertionError('daemonic processes are not allowed to have children',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 537, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 251, in start
    response = await self.instantiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 334, in instantiate
    result = await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/nanny.py", line 522, in start
    await self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 34, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/distributed/process.py", line 202, in _start
    process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

**Comment by devin-petersohn** [comment]
This looks isolated to MacOSX 10.12, which is no longer supported. I'm going to close as wontfix because the OS is too old, but please reopen if the issue occurs again.
